### ISSUE TITLE
Questions on script writing

### ISSUE THREAD

**Issue by Reaper10** [olivierkes/manuskript#120] opened 2017-06-18 21:13 UTC
can you write screenplay like you can in Trelby  or Celtx with auto formatting of text?  Can you all so write comic bock script?
screenplays formatting
https://www.youtube.com/watch?v=XZszextv6yE
stage play formatting
https://www.youtube.com/watch?v=QnTOxfu2RXw&t=82s
comic book formatting
https://www.youtube.com/watch?v=hlHdxjjnK-0
Comic Script Template - Comics Experience.pdf
radio play formatting
http://downloads.bbc.co.uk/writersroom/script
[How to write a video game script.pdf]
video games
(https://github.com/olivierkes/manuskript/files/1326943/How.to.write.a.video.game.script.pdf)
is that helpful?

**Comment by olivierkes** [comment] 2017-06-20 12:10
You can write anything in plain text.

What kind of autoformating do you expect? There is only a markdown highlighter for now. But you can still write in any format you like.

**Comment by Reaper10** [comment] 2017-09-15 16:09
screenplays formatting
https://www.youtube.com/watch?v=XZszextv6yE

stage play formatting
https://www.youtube.com/watch?v=QnTOxfu2RXw&t=82s

comic book formatting
https://www.youtube.com/watch?v=hlHdxjjnK-0

radio play formatting
http://downloads.bbc.co.uk/writersroom/scripts/radious.pdf

is that helpful?

**Comment by olivierkes** [comment] 2017-10-15 22:11
Duplicate of #32.

This might be added in the future, but right now it's not a priority.

**Closed by olivierkes** 2017-10-15 22:11 UTC
Labels: enhancement
