### ISSUE TITLE
Web site is down

### ISSUE THREAD

**Issue by theglauber** [olivierkes/manuskript#1182] opened 2023-06-22 12:35 UTC
http://www.theologeek.ch/manuskript  displays errors.

**Comment by theglauber** [comment] 2023-06-22 12:35
Is there an alternative place to download the installer?

**Comment by victorkane** [comment] 2023-06-22 14:37
Do you need help fixing your WordPress website? I'm not a great expert but I have some experience with WordPress and the new changes in it. You do so much work for the community with this great open source project, I'd be happy to help you get it up again without charging. If you are interested let me know how to best contact you here. Thanks for Manuskript!

**Comment by TheJackiMonster** [comment] 2023-06-22 17:06
The issue is already known: https://github.com/olivierkes/manuskript/issues/1175

@theglauber You can still download the binary releases from Github [here](https://github.com/olivierkes/manuskript/releases).

The problem is that only the host of the website has the access to fix it.

@victorkane Thanks for the offering.

I'll close this issue as duplicate now.

**Closed by TheJackiMonster** 2023-06-22 17:06 UTC
Labels: duplicate

**Comment by theglauber** [comment] 2023-06-22 20:07
Thank you
