### ISSUE TITLE
Cannot open a project.

### ISSUE THREAD

**Issue by chopin2712** [olivierkes/manuskript#529] opened 2019-03-07 09:12 UTC
Dear !

I recently discover this tool, it is very helpful but  I cannot re-open a recent project (on ubuntu 18.10) 

My project is this one : http://www.mediafire.com/file/5dhgch7wyhagj18/WALL-E+est+un+chef-d%27oeuvre.msk

But this project works : 

http://www.mediafire.com/file/6m6zwf3e26pfwiw/d.msk/file

Can you help me ?

**Comment by gedakc** [comment] 2019-03-07 18:24
When I try to open the project in the first link I see the following in the console log:

```
$ bin/manuskript 
Debug: Web rendering engine used: QWebView
Running manuskript version 0.8.0.
Found translation in settings: 
Note: No translator found or loaded from system locale for locale en_CA.
Last accessed directory "/home/gedakc/tmp" loaded.
Loading: /home/gedakc/tmp/WALL-E est un chef-doeuvre.msk
Detected file format version: 1. Zip: True.
Traceback (most recent call last):
  File "/home/gedakc/workspace/manuskript.gedakc/bin/../manuskript/ui/welcome.py", line 163, in openFile
    self.mw.loadProject(filename)
  File "/home/gedakc/workspace/manuskript.gedakc/bin/../manuskript/mainWindow.py", line 565, in loadProject
    self.loadDatas(project)
  File "/home/gedakc/workspace/manuskript.gedakc/bin/../manuskript/mainWindow.py", line 792, in loadDatas
    errors = loadSave.loadProject(project)
  File "/home/gedakc/workspace/manuskript.gedakc/bin/../manuskript/loadSave.py", line 66, in loadProject
    v1.loadProject(project, zip=isZip)
  File "/home/gedakc/workspace/manuskript.gedakc/bin/../manuskript/load_save/version_1.py", line 883, in loadProject
    appendRevisions(mdl, root)
  File "/home/gedakc/workspace/manuskript.gedakc/bin/../manuskript/load_save/version_1.py", line 964, in appendRevisions
    appendRevisions(mdl, child)
  File "/home/gedakc/workspace/manuskript.gedakc/bin/../manuskript/load_save/version_1.py", line 964, in appendRevisions
    appendRevisions(mdl, child)
  File "/home/gedakc/workspace/manuskript.gedakc/bin/../manuskript/load_save/version_1.py", line 969, in appendRevisions
    ID = root.attrib["ID"]
  File "src/lxml/lxml.etree.pyx", line 2452, in lxml.etree._Attrib.__getitem__ (src/lxml/lxml.etree.c:73200)
KeyError: 'ID'
```

**QUESTION**:  Did you have two copies of manuskript open at the same time editing the same WALL-E project?

This looks like a duplicate of [Issue 315 - File Load Failure - Corrupted? Multiple Concurrent Manuskript Instances not supported](https://github.com/olivierkes/manuskript/issues/315).

Note that the `.msk` file is in `.zip` format.  If you unzip the `.msk` file you should have access to all the contents.

To retrieve your work you might consider the following manual recovery steps:

1. Rename `WALL-E....msk` to `WALL-E....zip` so that the operating system will recognize it as a ZIP file.

2. Create a `WALLE` folder.

3. Unzip `WALL-E....zip` into the `WALLE` folder.

4. Create a new `WALL-E2....msk` project

5. Under **Edit -> Settings -> Revisions** disable **Keep revisions**.

6. Manually rebuild each piece of your project by coping and pasting the relevant file contents into the new WALL-E2 Manuskript project.

'Hope that helps.

**Comment by worstje** [comment] 2019-03-07 18:24
Here you go, this is a fixed version with one caveat: I had to remove the revision history to get it back to work. I am not quite sure in what sense it got screwed up. However, I suspect you'd rather have your project loading in its current state rather than have me hold your project hostage for a while longer.

[Rescue-WALL-E.zip](https://github.com/olivierkes/manuskript/files/2942749/Rescue-WALL-E.zip)

I did run into a weird issue other than that, though.

**Comment by gedakc** [comment] 2019-03-07 18:26
Thank you @worstje for posting a rescued version of the project.  I'm sure that @chopin2712 will be very appreciative.

**Comment by gedakc** [comment] 2019-03-07 18:39
Responses to @worstje follow:

> Would you happen to know why compressing the file tree using 7zip causes the load process to screw up?

I don't know for sure, but my guess would be that the default "zip" format used by 7zip is not the same as that used by manuskript.  There might be a flag to pass to 7zip that makes the format the same, but I do not know this for sure.

> Have you seen this before?

No, but then again I don't use 7zip or Windows for development.

If you have a set of steps that someone can use to recover from this issue then it would help others if you can post the steps.

Cheers,
Curtis

**Comment by worstje** [comment] 2019-03-07 18:45
I am frankly more inclined to figure out the cause and making Manuskript work with it. For as far I was able to identify, 7zip was creating a completely valid zip file, if a slightly unconventional one for the purposes of the iteration happening in python / Manuskript.

My guess is that it somehow stores all folders as separate entries whereas some other tools might consider them implied because of the other files in them. Or maybe it is as simple a problem as putting the folder information first or last in the file listing.

In the end, a zip file is a zip file, and merely for the sake of debugging, it would be nice to figure this out. I spent thirty minutes barking up the wrong tree after removing the revisions file because I thought some other file was also messed up.

I'll look into this some more, I guess.

**Comment by chopin2712** [comment] 2019-03-07 19:48
> Here you go, this is a fixed version with one caveat: I had to remove the revision history to get it back to work. I am not quite sure in what sense it got screwed up. However, I suspect you'd rather have your project loading in its current state rather than have me hold your project hostage for a while longer.
> 
> [Rescue-WALL-E.zip](https://github.com/olivierkes/manuskript/files/2942749/Rescue-WALL-E.zip)
> 
> I did run into a weird issue other than that, though.
> 
> @gedakc : Would you happen to know why compressing the file tree using 7zip causes the load process to screw up? I debugged it for a while and only got it to work after I made Manuskript save the file in its compressed format. I uncommented one of the logs and turned logging on, and ran into:
> 
> ```
> Reading outline:
> *  []
> *  ['0-Introduction']
> *  ['0-Introduction', '0-Introduction.md']
> Traceback (most recent call last):
>   File "C:\Portable\Manuskript\bin\..\manuskript\ui\welcome.py", line 146, in loadRecentFile
>     self.mw.loadProject(act.data())
>   File "C:\Portable\Manuskript\bin\..\manuskript\mainWindow.py", line 565, in loadProject
>     self.loadDatas(project)
>   File "C:\Portable\Manuskript\bin\..\manuskript\mainWindow.py", line 792, in loadDatas
>     errors = loadSave.loadProject(project)
>   File "C:\Portable\Manuskript\bin\..\manuskript\loadSave.py", line 66, in loadProject
>     v1.loadProject(project, zip=isZip)
>   File "C:\Portable\Manuskript\bin\..\manuskript\load_save\version_1.py", line 874, in loadProject
>     parent[i] = files[f]
> TypeError: 'str' object does not support item assignment
> ```
> 
> For some reason the iteration seems to be intent on stopping at every different folder as opposed to going all the way down to the file level like with Manuskript-saved files, and as a side-effect fails to produce the nested OrderedDict()s the code expects. Have you seen this before?
> 
> Edit: Crap, I got ninja'd. smile

THANKS YOU SO MUCH !!! But I do not understand ? How do  you do that ?

**Closed** 2019-03-07 19:53 UTC
