### ISSUE TITLE
[Windows Version] Two program windows pop up

### ISSUE THREAD

**Issue by BrianBlowtasky** [olivierkes/manuskript#327] opened 2018-03-16 01:47 UTC
When double clicking the executable, the command prompt opens up as well as the main program.
It seems  the fix to this problem is to use pythonw.exe to run your script instead of python.exe.

**Comment by gedakc** [comment] 2019-01-11 16:37
This issue is related to PyInstaller packaging.

The command prompt window contains the program debug output.  The open window makes it easier for users to report issues and copy and paste this output into the issue.  This is useful while we work to improve the functionality and stability of Manuskript.

When Manuskript is more stable we can look into different packaging options for Windows.

A user reported the [following Windows 10 workaround](https://www.theologeek.ch/manuskript/2018/08/15/manuskript-0-7-0/#comment-1465):

> If you’re on Windows 10 you can create a new Desktop Workspace and put Manuskript’s command prompt in to hide it.
>
> Press “Windows Key + Tab” (A Windows Key is between CTRL and ALT at the bottom left on a keyboard) => Hover your mouse cursor over the Manuskript command prompt then “Right Click” => Select “Move to” from the popup context menu => Select “New Desktop”.
>
> This will create a Desktop 2 workspace and move Manuskript’s command prompt there.
>
> You can switch between your Desktop workspaces by pressing “CTRL + Windows Key + Left/Right Arrow”.
>
> Read more about Windows workspace shortcuts online. =)

**Comment by sprite-1** [comment] 2019-01-12 05:34
I made a simple launcher that you just put in the Manuskript directory. It will automatically hide the console window when the main program is open.

[Source](https://gist.github.com/sprite-1/60897397fd7061b0d14d14d17ecc2987) -- [Compiled Binary](https://nofile.io/f/H1XQN8N6EC8) (32 and 64-bit compatible):

**Comment by Muttsuri** [comment] 2021-01-25 00:47
This seems silly since in `manuskript.spec` it has this:
```python3
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='manuskript',
          debug=False,
          strip=False,
          upx=True,
          console=True,
          icon=os.path.join(SPECPATH, 'icons/Manuskript/manuskript.ico') )
```
Unless I'm realy missing something, that `console=True` parameter seems like the culprit, since for development Manuskript already expects a `--console` parameter to be passed.
Would changing this flag fix it ?

**Comment by worstje** [comment] 2021-04-13 18:31
@TheJackiMonster Resurrecting this oldie now that all the logging code has been merged.

This is the one final thing we probably want to consider before an official release is how to modify the Windows build to no longer show the console window as that one will now stay black if all is well. The existence of that thing has long been an unnecessary, ugly wart on this platform.

Right now I don't have the time to dig into the build environment, but based on the above discussion I'd recommend adjusting `manuskript.spec` to build **an additional binary** `manuskriptw.exe` with `console=False`.

We cannot change the original one because `console=False` causes STDOUT and other pipes to be unavailable, which would in turn mean that **_all_** the commandline stuff that has been added with recent patches (like --help, --verbose, etc.) would become unavailable. (Windows GUI stuff isn't meant to interact in that manner, after all.)

The end result would be that Windows users use `manuskriptw.exe` for shortcuts, and `manuskript.exe` when interacting from a terminal or other process.

(If a neater one-binary solution exists, then that is nice and something we could explore in the future, but that would take way more testing, whereas this solution should be simple and mirrors the way Python does its own Windows port.)

I could look at it in one of the next few days, or you can work on implementing this if you want to release 0.12 sooner. It shouldn't be much more work as someone else already figured out the cause.

**Comment by TheJackiMonster** [comment] 2021-04-21 19:38
Okay, so I got a working binary built with Wine on Linux and I could also send it someone I know to check if it works... and it does. ^^'

The thing about the command prompt opening is that it can actually help users to see that Manuskript is loading or saving. So if we want to fix this issue properly we should also look for a good replacement. Especially considering how long the new build can take at startup when using LanguageTool. Obviously improving performance is the better solution here but this will require way more time, I assume.

So I will also look into hiding the command prompt but at the moment I would probably suggest users to create a desktop shortcut and set its settings to `console=False` or add this as parameters (I'm not a Windows user but I think this is possible... ^^').

**Comment by SvetaKrava** [comment] 2021-12-28 19:55
If you follow the directions of this gist, you can get rid of the window when launching the program using powershell. 

https://gist.github.com/SvetaKrava/78c45e1ef07fd5192ba85c94066f316c.js

**Comment by TheJackiMonster** [comment] 2022-05-17 10:27
> If you follow the directions of this gist, you can get rid of the window when launching the program using powershell.
> 
> https://gist.github.com/SvetaKrava/78c45e1ef07fd5192ba85c94066f316c

Technically we could do this put the problem is: How do we know the installation path on the local system?

I mean, we can't expect all users to correct the shortcut file pointing to the Powershell script, I suppose. I haven't used Windows for quite some time but I would expect most users to either double-click the executable or making a shortcut to the executable on their desktop.

The solution I could think of would be adding an option into the application to create the shortcut because we know the absolute path of the application during runtime. But this would require platform dependent branching in the code and it wouldn't work when running from source probably (being an inconsistent solution).

I'll try to add a `manuskriptw.exe` as [worstje](https://github.com/worstje) suggested.

**Comment by TheJackiMonster** [comment] 2022-05-28 10:32
I've added a `manuskriptw.exe` as second target for the Windows build. Maybe someone can test whether it solves this issue. Otherwise I wait for confirmation after next release.

**Closed** 2022-06-08 11:48 UTC
Labels: windows, packaging

**Comment by ws132** [comment] 2022-07-11 07:42
> 我添加了一个 `manuskriptw.exe`作为 Windows 构建的第二个目标。 也许有人可以测试它是否解决了这个问题。 否则，我等待下一次发布后的确认。

manuskriptw.exe doesn't work, report bug.

os: win10 LTSC 21H2 19044.1806

error window title:
```
Unhandled exception in script
```
detail
```
Failed to execute script 'manuskript' due to unhandled exception:'NullWriter' object has no attribute 'fileno'

Traceback (most recent call last):
  File "manuskript", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "manuskript\main.py", line 17, in <module>
AttributeError: 'NullWriter' object has no attribute 'fileno'
```
Currently I use the [ps1 script](https://gist.github.com/SvetaKrava/78c45e1ef07fd5192ba85c94066f316c) above and it works just fine.

**Comment by TheJackiMonster** [comment] 2022-07-13 10:45
@ws132 Yes, the issue will be tracked here: #1044 

The reason I don't just package a PowerShell script is that either a user needs to create a symbolic link for such a script (which I'm not aware of how convenient that is... since such scripts would probably not have icons and similar). But shipping a precreated symbolic link does not work either since Windows uses absolute paths for them.
