### ISSUE TITLE
languages mix = Babel :)

### ISSUE THREAD

**Issue by j2l** [olivierkes/manuskript#448] opened 2018-12-26 13:14 UTC
Manuskript is mixing languages within the interface (c'est Babel !):
![image](https://user-images.githubusercontent.com/65325/50446967-413ea380-0918-11e9-9197-9d68dd58d75d.png)

Chosen language is English, but my windows is in French.
It looks like it doesn't follow the language setting all over.

**Comment by gedakc** [comment] 2019-01-01 17:52
This issue is fixed in the **develop** branch with pull request #433 and is planned for inclusion in the next release of Manuskript.

Closing this issue as a duplicate of issue #411.

**Closed by gedakc** 2019-01-01 17:52 UTC
