### ISSUE TITLE
One-time glitch: dragged "World" entry to top of list and it disappeared

### ISSUE THREAD

**Issue by tinkicker** [olivierkes/manuskript#1122] opened 2023-01-29 14:14 UTC
I'm not sure this is actionable or repeatable. I have set up my "World" area by making new entries that are simply dashed-line placeholders so that I can separate different group different world items by type. People, locations, etc. I have one at the very top of the list just to visually set things apart from the box borders, and as I made a new group, I dragged another dashed divider entry to the top to begin inserting items beneath it.

When I dropped the dashed line item in the first line position it simply disappeared. Didn't fall back to the bottom of the list due to misalignment when dropping or anything like that. Just disappeared. I made a new dashed line item and it then dropped correctly. So, not sure if this is truly a bug, some intended consequence of dropping the item maybe beyond the top of the list (which I'm not sure I even actually did), or just a random planetary alignment event. I haven't been able to reproduce it again.

Just wanted to make everyone aware of the event in case it happens to someone else. You're not crazy. Or at least any crazier than I am.

**Comment by TheJackiMonster** [comment] 2023-02-09 22:30
Can you try double-clicking the item at the top? Because I think the dragged item was just grouped one depth below and your top item is just not expanded. At least this would look very similar to it disappearing and I can not reproduce an actual issue.

But maybe we could add some visual hint in the future to make something like that more obvious? Anyway I will wait whether you can confirm this is an visual issue or rather actual data loss.

**Comment by TheJackiMonster** [comment] 2023-02-13 20:42
This should be fixed with #305 now.

**Closed by TheJackiMonster** 2023-02-13 20:42 UTC
Labels: bug
