### ISSUE TITLE
[Feature Suggestion]: Pictures

### ISSUE THREAD

**Issue by koliseo** [olivierkes/manuskript#543] opened 2019-03-29 21:48 UTC
I've been developed my own writer software... and I abandoned it when I discover Manuskript. This is a great software! The only thing I miss about it is the ability to attach images to elements such as characters, places, etc.
I like to draw/download maps, photographs of faces, buildings, etc. that help me to remember and to describe the world of my stories and I do not find that ability in Manuskript.
It's just a suggestion. I repeat: This software is magnificent.

**Comment by gedakc** [comment] 2019-03-31 16:18
I believe that this request is a duplicate of other existing issues.

Closing this issue and labeling it as a duplicate of [Issue #349 - Image attachments for character/world/plot items](https://github.com/olivierkes/manuskript/issues/349).

See also [Issue #22 - Adding images to docs](https://github.com/olivierkes/manuskript/issues/22).

**Closed by gedakc** 2019-03-31 16:18 UTC
