### ISSUE TITLE
Crash in Windows 10 when drag and drop

### ISSUE THREAD

**Issue by Phieldar** [olivierkes/manuskript#559] opened 2019-04-21 16:58 UTC
In Windows 10, latest version of Manuskript. I try dragging and dropping one or many folder (including scenes) in another folder and it crashs. I tried with one folder... and many folders and still it crash. In fact. When I drag and drop individual folder. The first transfer don't crash, but the second crash.

**Comment by worstje** [comment] 2019-04-21 17:43
Before I dig into it and chase my own tail trying to figure out how to reproduce it, can you offer any more information?

Does it work with an empty folder?
Are there nested folders?
How many files are inside?
What types of files?

**Comment by Phieldar** [comment] 2019-04-21 17:48
In "plan" mode, I have 4 folders (chapters) including 4 scenes. I created a new folder and wanted to move all four chapter in that new folder that I wanted to name Book 1, (inspired by the trilogy preset). I selected first the 4 folders at once and dragged them in the new folder (5th in the list) and it crashed. I  tried the same but on folder (chapter) at a time... and after the 2nd, it crashed again.

**Comment by worstje** [comment] 2019-04-21 18:13
I have noticed a crash once in the past when I was organising way back when, but I wasn't particularly interesting in figuring out the cause back then.

Anyway, I have tried moving around some folders in a test project just now and I can't seem to reproduce it though, even when following your instructions. (I assume you mean the outline screen when you talk about 'plan' mode).

Two more questions that come to mind:

1. Are you saving to a single file? (See settings menu.)

2. Do you have auto-saving turned on? If so, do you have revisions turned on? The latter slows down saving considerably and may make it more likely to trigger.

My guess is that you might be noticing some sort of race condition / inconsistency bug that is caused by the auto-save feature saving while the UI is trying to move files about when other parts of the code aren't expecting those bits to change. I've noticed things like those pop up once or twice in the past.

**Comment by Phieldar** [comment] 2019-04-21 18:21
I'm sorry to be so unprecise. I try to be clearer in the future. 
1. Indeed. I'm saving in a single file
2. I do have auto-saving turned on and also revisions (+ intelligent supression)

I disabled revisions and now the drag and drop is working just fine. Thanks a lot! I believe that I can reactivate revision now.

**Comment by worstje** [comment] 2019-04-25 11:53
I am currently digging into the saving and outline drag-n-drop code, and I am not quite sure how those two interact as of yet. I did manage to cause a crash while messing around so far but it does not seem to involve saving functionality.

Can you run Manuskript from a command prompt and reproduce the bug (preferably with a sample project) to see exactly what kind of messages and traceback it produces, and then share it with us? I'll experiment a bit more to see what else I can do to make it crash, but I want to fully understand the problem before I start to try and patch the one thing I have observed myself.

**Comment by gedakc** [comment] 2019-05-16 16:59
Can someone provide an exact list of steps that reproduce this crash?

Following is the testing I performed.

### Test 1 - Drag and Drop Chapter into other Chapter

1. Create a new Manuskript project using the **Novel** template
2. Select the **Editor** pane
3. Select **Chapter 2**
4. Drag and drop into **Chapter 3**
5. Select **Chapter 8** plus **Chapter 9** using shift+click
6. Drag and drop into **Chapter 6**

OBSERVATIONS:

- Manuskript 0.9.0 on Kubuntu 16.04: no crash observed.
- Manuskript 0.9.0 on Windows 10: no crash observed.


### Test 2 - Drag and Drop Chapter beside other Chapters

1. Create a new Manuskript project using the **Novel** template
2. Select the **Editor** pane
3. Select **Chapter 2**
4. Drag and drop between **Chapter 3** and **Chapter 4**
5. Select **Chapter 8** plus **Chapter 9** using shift+click
6. Drag and drop between **Chapter 5** and **Chapter 6**

OBSERVATIONS:

- Manuskript 0.9.0 on Kubuntu 16.04: no crash observed.
- Manuskript 0.9.0 on Windows 10: no crash observed.


### SUMMARY

So far I am unable to reproduce the crash.

Note that I do have **Edit -> Settings -> Revisions** enabled.

**Comment by kakaroto** [comment] 2019-05-16 18:07
It only crashes IF a text being moved (a child of the chapter) is open in the editor pane AND you do the move in the Outline pane, AND you move the chapter down not up in the order (For example, moving chapter 2 between chapters 3 and 4 would crash, it wouldn't crash if you move chapter 3 between chapters 1 and 2)

**Comment by gedakc** [comment] 2019-05-16 18:26
Thanks @kakaroto for the tip. Unfortunately I am still unable to reproduce the crash (I tested on Kubuntu 16.04). 

Following are the steps I used to test.

### Test 3 - Drag and Drop Chapter with Open Text beside other Chapters

1. Create a new Manuskript project using the **Novel** template
2. Select the **Editor** pane
3. Expand **Chapter 2** to show the scene texts
4. Select **Scene 3**
5  Select the **Outline** pane
6. Select **Chapter 22**
7. Drag and drop between **Chapter 3** and **Chapter 4**

No crash observed.

Please let me know what I need to change to recreate the crash.

**Comment by kakaroto** [comment] 2019-05-16 18:35
Ha! I just tested and confirmed the issue, came to say I don't know why you don't get the crash, and saw the edit!
Looks like you confirmed the crash and the fix as well :)

**Comment by gedakc** [comment] 2019-05-16 18:41
'Just finished testing with Windows 10.

Both Windows 10 and Kubuntu 16.04 crash using the above **Test 3** steps with Manuskript 0.9.0.

When PR 571 is applied, both Windows 10 and Kubuntu 16.04 **do not** crash.

**Comment by worstje** [comment] 2019-05-16 18:43
@gedakc After having all those emails while out for dinner giving me a serious pit-of-my-stomach feeling about screwing up the fix, that is literally the best comment you could have posted tonight. 😄

**Comment by gedakc** [comment] 2019-05-16 18:49
@worstje sorry about that.  My bad not using the **master** branch to confirm the original crash report.

**Comment by gedakc** [comment] 2019-05-19 15:55
This issue has been resolved in the **develop** branch and will be included in the next release of Manuskript.

**Closed by gedakc** 2019-05-19 15:55 UTC
Labels: bug
