### ISSUE TITLE
Fails to create a project in Linux

### ISSUE THREAD

**Issue by theodotos** [olivierkes/manuskript#65] opened 2016-12-09 07:42 UTC
I just downloaded the latest Linux version (0.3.0). When I try to create a new project I get:

```
Warning: failed to load translator for locale en_US...
Traceback (most recent call last):
  File "manuskript/ui/welcome.py", line 159, in createFile
  File "manuskript/ui/welcome.py", line 344, in loadDefaultDatas
  File "manuskript/ui/welcome.py", line 344, in <listcomp>
IndexError: list index out of range
```

and nothing happens. The open/recent/create dialog does not go away even after I 'save' the new project.

Loading a sample project seems to be working.

**Comment by techieinak** [comment] 2016-12-09 07:45
I've got the same issue, although the very first time I started Manuskript I was able to create a test project, just not any other times when I start or try from within the app. Opening the existing project I created at first works fine and I can also save it as another project.

**Comment by olivierkes** [comment] 2016-12-09 08:06
Duplicate of #44.

The "translator" thing is just a warning, you can ignore it. As for the crash, please see issue #44 or try the develop branch.

**Closed** 2016-12-09 08:07 UTC
Labels: bug

**Comment by theodotos** [comment] 2016-12-11 10:27
Double clicking on the type of project solved the issue. Thanks!
