### ISSUE TITLE
Unable to start Manuskript after chaning theme

### ISSUE THREAD

**Issue by aizenimr** [olivierkes/manuskript#754] opened 2020-04-15 21:44 UTC
I have changed the theme of manuskript, and since then the application exits and refuses to start.
I have tried unsinstalling and reinstalling several times from git but no change.
My OS is Linux Manajro.
This is what I get when trying to activate from the terminal:

/opt/manuskript/bin/../manuskript/main.py:104: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if platform.system() is not 'Windows':
Debug: Web rendering engine used: QWebView
qt5ct: using qt5ct plugin
Running manuskript version 0.11.0.
Preferred translation: ['en-IL'] (based on available ui languages)
No translation found or loaded. (manuskript_en_IL.qm)
Using the builtin translation.
/opt/manuskript/bin/../manuskript/importer/opmlImporter.py:124: SyntaxWarning: "is" with a literal. Did you mean "=="?
  return len(s) is 0
/opt/manuskript/bin/../manuskript/exporter/pandoc/abstractPlainText.py:78: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if self.formats is "":
qt5ct: D-Bus global menu: no
Empty filename passed to function
Empty filename passed to function
Loading: /home/aizenimr/MEGA/כתיבה/סיפורים/רומאן ישראמן!/Israman.msk
Detected file format version: 1. Zip: True.
Project /home/aizenimr/MEGA/כתיבה/סיפורים/רומאן ישראמן!/Israman.msk loaded.
Fatal Python error: Segmentation fault

Current thread 0x00007f9eee5d3740 (most recent call first):
  File "/opt/manuskript/bin/../manuskript/ui/views/treeDelegates.py", line 41 in paint
  File "/opt/manuskript/bin/../manuskript/main.py", line 221 in launch
  File "/opt/manuskript/bin/../manuskript/main.py", line 234 in run
  File "/usr/bin/manuskript", line 13 in <module>
Segmentation fault (core dumped)

Any thoughts?

**Comment by obw** [comment] 2020-04-16 10:05
You can reset your changes if you delete the conf file. You can also try to edit it.

It should be here: `~/.config/manuskript/manuskript.conf`

In your case:
~ = `/home/aizenimr/`

Also no Idea what happens.

**Comment by aizenimr** [comment] 2020-04-16 10:13
Thanks, I'll give it a try.
I think some of themes in the Settings menu do not work properly. If I'm not mistaken, I used the second theme from the top of the list (the default is last one - Fusion).

**Comment by TheJackiMonster** [comment] 2021-02-22 19:31
I close this as a duplicate of #467. Themes are pretty much broken in Qt or at least it seems like it at the moment.

**Closed by TheJackiMonster** 2021-02-22 19:31 UTC
Labels: bug
