### ISSUE TITLE
Crash on interacting with anything

### ISSUE THREAD

**Issue by tryhardsnipehrd** [olivierkes/manuskript#1168] opened 2023-05-28 04:53 UTC
Hi all, I was trying to get Manuskript working, specifically 0.15.0.
I did not need sections outside of the chapters, so I went to delete the automatic sections that are created with the Novella template. Upon doing this, I was immediately greeted with a crash.
I restarted from terminal, and did it again, and the crash report is the following
```
CRITICAL> An unhandled exception has occurred!
Traceback (most recent call last):
  File "/usr/share/manuskript/manuskript/ui/welcome.py", line 349, in deleteTemplateRow
    self.updateTemplate()
  File "/usr/share/manuskript/manuskript/ui/welcome.py", line 329, in updateTemplate
    self.updateWordCount()
  File "/usr/share/manuskript/manuskript/ui/welcome.py", line 370, in updateWordCount
    self.template[1][templateIndex][1])
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
IndexError: list index out of range

```
This happens in both 0.15.0 and 0.14.0
If anyone could perhaps clue me into a fix for this, it is quite annoying that I am unable to even begin to move my project over to this amazing piece of software!

**Comment by TheShadowOfHassen** [comment] 2023-05-28 11:12
What operating system are you using?

**Comment by tryhardsnipehrd** [comment] 2023-05-28 22:41
Apologies, I thought I had gotten that specified.
Kali Linux, so a Debian based system, latest releases.

**Comment by TheShadowOfHassen** [comment] 2023-05-28 22:53
Can you post your latest log? it's in .local/share/manuskript/logs. It's a bug that probably need fixed, we will need a bit more information to do it.

0.15.on Ubuntu and haven't had that problem. For a quick fix, you could try deleting the manuskript file in .cache. and  .config. 

P.S. I don't use the templates, they're a pain. I just create the files and folders I need in a program. It's easier that way

Also, I would disable save to single file and save Manuksript as a .msk file and a folder instead of a zipped archive. It's more secure, also, please make backups. People have been having problems with manuskript crashing and loosing their stories. I haven't ever had it happen myself, but I'd hate to have it.

**Comment by tryhardsnipehrd** [comment] 2023-05-29 00:54
[2023-05-28_18-51-40_manuskript#2034557.log](https://github.com/olivierkes/manuskript/files/11587144/2023-05-28_18-51-40_manuskript.2034557.log)

Hi again!
The newest log is here, I made sure to trigger the bug before dropping this log so that I'm sure it's there!

**Comment by TheShadowOfHassen** [comment] 2023-05-29 01:03
Thanks! Can use the program by skipping the template and just create an empty project?

**Comment by tryhardsnipehrd** [comment] 2023-05-29 04:26
I was able to get it working that way, just seems a small bit annoying to not be able to use the templates.
For now however, this works beautifully, and I appreciate the effort to get it working!

**Comment by marosoft** [comment] 2023-05-30 21:36
I could not reproduce it. Could it be related to a version of Qt used?

I can see that the code depends on setting and using the properties of the
widgets in the logic which potentially may work differently for a different
version of the library.

**Comment by XVicarious** [comment] 2023-07-09 18:46
I am seeing this crash as well. I'm on Arch, with QT5 5.15.10. With manuskript 0.15.0-1. All while clicking through the templates on the welcome screen.

**Comment by samrosenf** [comment] 2023-08-15 10:17
Hey, I am experiencing the same problem. 
When I go through the templates, in the third or forth template I go through it crashes with the same error.
 
[2023-08-15_13-04-54_manuskript#3426.log](https://github.com/olivierkes/manuskript/files/12343194/2023-08-15_13-04-54_manuskript.3426.log)

**Comment by bufalo1973** [comment] 2023-10-02 20:21
It happens when you select a template that is not empty and then you click on any empty template (empty fiction/non-fiction). If you select an empty template from another empty template it doesn't crash.

**Comment by TheJackiMonster** [comment] 2023-12-07 14:12
I can reproduce this. However the issue seems to be a duplicate of #1163.

**Comment by TheJackiMonster** [comment] 2023-12-07 14:34
Got solved via commit: https://github.com/olivierkes/manuskript/commit/14392909c3592a7546e9c76f914349c98749e02d

**Closed by TheJackiMonster** 2023-12-07 14:34 UTC
Labels: duplicate
