### ISSUE TITLE
UnicodeDecodeError when opening a file with bad characters

### ISSUE THREAD

**Issue by TheHeadlessSourceMan** [olivierkes/manuskript#532] opened 2019-03-08 15:08 UTC
I have a file with (evidently) bad characters in it.  It gives the following backtrace:

> `Debug:`
> `Web rendering engine used: QWebView`
> `Running manuskript version 0.8.0.`
> `Note: No translator found or loaded for locale en_US.`
> `Traceback (most recent call last):`
>   `File "manuskript\ui\welcome.py", line 71, in showEvent`
>   `File "manuskript\mainWindow.py", line 565, in loadProject`
>  ` File "manuskript\mainWindow.py", line 792, in loadDatas`
>   `File "manuskript\loadSave.py", line 58, in loadProject`
>  ` File "c:\python34\lib\encodings\cp1252.py", line 23, in decode`
> `UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 51: character maps to <undefined>`

I suggest not only the incident on hand be fixed, but the code be examined wherever new data can enter the application (cut&paste?  ui controls?  import features? etc) and the input be normalized by calling the string.decode("utf-8", "replace") or "ignore" so that the data is guaranteed to be in a useable form.

**Comment by gedakc** [comment] 2019-03-12 20:55
Thank you for your interest in Manuskript.

This report looks like a duplicate of issue #470.

Would you please try one of the following to test if the problem has already been fixed?

Either:
  - Download `manuskript-0.8.0-issue502-test1-win32.zip` from [Manuskript SourceForge Testing-only folder](https://sourceforge.net/projects/manuskript/files/manuskript/testing-only/), extract, and test to see if the problem is resolved.

Or:
  -  [Run Manuskript from Source Code on Windows](https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Windows) to test if the problem is resolved.

**Comment by gedakc** [comment] 2019-03-29 17:04
Since there has been no response I am closing this as a duplicate of issue #470.

**Closed by gedakc** 2019-03-29 17:04 UTC
