### ISSUE TITLE
feature request: target goals

### ISSUE THREAD

**Issue by writer12** [olivierkes/manuskript#814] opened 2020-11-08 12:02 UTC
Right now, you can only put word count goals for scenes and chapters, but I would like to be able to do this for writing sessions as well.

**Comment by SConard** [comment] 2020-11-08 14:48
One way that you can set a session goal is by using the Fullscreen mode. Once in Fullscreen, you can push your mouse to the middle of the left side of your screen and a fly-out menu will appear. It gives you the option of word or time targets. It 'enforces' by making the X close option on the top right disappear until you have accomplished your goal. I tested it, and it appears that the goals need to be accomplished within only one file. (Using the arrows along the top I scrolled to other files and any changes there didn't seem to add to my word count,)

I hope this helps.

**Comment by TheJackiMonster** [comment] 2021-02-21 23:05
This is a duplicate of #459. So I would close this issue here. There is already a PR https://github.com/olivierkes/manuskript/pull/460 addressing this feature.

**Closed by TheJackiMonster** 2021-02-21 23:05 UTC
Labels: duplicate, enhancement
