### ISSUE TITLE
Saved progress deleted by reordering scenes.

### ISSUE THREAD

**Issue by lbenedetto** [olivierkes/manuskript#1019] opened 2022-03-12 22:19 UTC
I have auto save turned on. I wrote a scene. I created a new scene, it was automatically called 'New'. I moved it above the one I just wrote. Both scenes were suddenly called 'New' and all my work was gone. I quickly went into settings and disabled auto save, but it was too late. When I opened the msk file, the scene was gone. Just '4-New-642.md' and '5-New-642.md', both only a few bytes in size.

I tried to hit Ctrl z in both files, but it didn't work.
It seems revisions were turned off by default.

I an running on commit 9e8e7a234f05f02c80621c648fb6af042d593f7f. The issue persists after restart, and on different computers.

To reproduce, have a folder with multiple scenes in it. 
```
1-A.md
2-B.md
3-C.md
```
Move the one at the bottom up 1 spot. 
```
1-A.md
2-C.md
3-B.md
```
It will overwrite the scene, causing both to have the same name, with a number appended.
```
1-A.md
2-C-645.md
3-C-645.md
```

It also breaks in certain circumstances if you move the scene up multiple places.

**Comment by TheJackiMonster** [comment] 2022-03-12 22:53
I assume the data is lost if you don't have a backup, sadly.

**Comment by TheJackiMonster** [comment] 2022-05-17 09:59
I'll close this as duplicate of issue #1001. Further progress will be available over there.

**Closed by TheJackiMonster** 2022-05-17 09:59 UTC
Labels: duplicate
