### ISSUE TITLE
[Feature request] Timeline 

### ISSUE THREAD

**Issue by Eusorph** [olivierkes/manuskript#634] opened 2019-09-09 20:29 UTC
First of all, the Storyline is very useful and works pretty well. Now, though, I'd love to see an actual Timeline incorporated in the Storyline window. That would be a killer feature, because it would render the use of an external app like Aeon Timeline obsolete. Since you already have a very nice and neat tracking system for all the various items in the story, I think (hope is more the word) that it shouldn't be too difficult to add timestamps as tracking items too, and a Timeline in the same category as Plots and Characters -- although it should work in reverse of course, because timestamps would be put in the Reference window of scenes and not in the Timeline window, unless you want to make it work as another Outline window, I guess, which could work too. That way, we would have an easy and effective Timeline incorporated into Manuskript. Also, I do think the whole Storyline should be able to go full screen or detach to be maximized better.

**Comment by gedakc** [comment] 2019-09-10 15:30
Closing issue as duplicate of issue #118.

**Closed by gedakc** 2019-09-10 15:30 UTC

**Comment by Eusorph** [comment] 2019-09-10 17:16
Frankly I didn't think it was a duplicate. That conversation was very confused and never mentioned a timeline. I do specifically mention a time and I think that's clearer.
