### ISSUE TITLE
Link to website not working

### ISSUE THREAD

**Issue by Quirinea** [olivierkes/manuskript#1184] opened 2023-06-27 13:17 UTC
The contribute link 

"https://www.theologeek.ch/manuskript/contribute/" gives

Fatal error: __autoload() is no longer supported, use spl_autoload_register() instead in /home/clients/90412ec2d8e55d60c960a48d035ee4d5/web/manuskript/wp-includes/compat.php on line 502

This is linked also from e.g. AlternativeTo

I thought of recommending Manuskript on a forum and checking the source gave me this mess!

(see if this gets posted now, and not gives 404)

**Comment by TheJackiMonster** [comment] 2023-06-29 08:43
We are already aware. I'll close this as duplicate of issue https://github.com/olivierkes/manuskript/issues/1175.

Information to get binary downloads are already mentioned on that issue in case it's needed.

**Closed by TheJackiMonster** 2023-06-29 08:43 UTC
Labels: duplicate

**Comment by Quirinea** [comment] 2023-06-29 11:13
OK I tried to search if this was reported but did not find the issue. Sorry for duplicate.
