### ISSUE TITLE
Crash when edit text

### ISSUE THREAD

**Issue by bepolymathe** [olivierkes/manuskript#555] opened 2019-04-17 11:33 UTC
I have a crash when I try to edit a file (after clicking on the file and then moving the cursor to the text). 

```
Debug: Web rendering engine used: QWebView
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Running manuskript version 0.9.0.
Found translation in settings: manuskript_fr.qm
Loaded translation from settings: manuskript_fr.qm.
Loading: /home/manu//RECC.msk
Detected file format version: 1. Zip: True.
Le projet /home/manu/RECC.msk a été chargé.
Fatal Python error: Segmentation fault

Current thread 0x00007f238e5b7740 (most recent call first):
  File "/usr/share/manuskript/manuskript/main.py", line 145 in launch
  File "/usr/share/manuskript/manuskript/main.py", line 158 in run
  File "/usr/bin/manuskript", line 30 in <module>
Erreur de segmentation (core dumped)
```

Is there a way to solve this problem?

**Comment by worstje** [comment] 2019-04-17 12:16
I am on Windows myself and haven't experienced that.

Is this an official 0.9.0 release? And what linux distribution are you using?

This backtrace doesn't show anything of interest; the last thing it shows is the start-up process for the Qt library. But you've clearly already been interacting with the window. What version of Qt is on your system?

**Comment by bepolymathe** [comment] 2019-04-17 13:34
I am under Fedora 29, official 0.9.0 release Manuskript. Qt5 installed

**Comment by gedakc** [comment] 2019-04-17 16:20
It would seem that you are using Wayland instead of the traditional X11 on GNU/Linux.

Have you tried doing what the console messages suggests?

> Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.

To test, open a terminal window, `export QT_QPA_PLATFORM=wayland`, and then invoke `manuskript` from the terminal window

**Comment by bepolymathe** [comment] 2019-04-17 16:52
I have tested this but the problem remains the same...

![image](https://user-images.githubusercontent.com/29939805/56306041-dd97ea80-6141-11e9-8456-21795b9f995e.png)

**Comment by bepolymathe** [comment] 2019-04-17 17:04
Maybe I spoke too quickly... it looks better. I continue the tests....

**Comment by bepolymathe** [comment] 2019-04-17 17:09
No, the problem remains the same... i confirm.

Maybe appear after i tried to click on the icon "fullscreen"

**Comment by gedakc** [comment] 2019-04-17 17:56
@bepolymathe please try to identify the exact set of steps that cause the crash.

I am unable to reproduce the issue.  I have tried Manuskript 0.9.0 on Fedora 29 (64-bit) and even clicked on **Fullscreen** and  I do not experience any crashes.  I even tried changing the language setting to French and still no crashes.

**Comment by bepolymathe** [comment] 2019-04-17 18:38
It is difficult to say what is causing the problem. I open a project (with the same problem) and when I approach the smile of the "fullscreen" icon it crashes... The proof in video

[Link to see video](https://cloud.palimpsestes.net/s/DJtn3QQfcBLTJde)

**Comment by gedakc** [comment] 2019-04-17 18:42
@bepolymathe it is possible that the issue is with the specific project you are using.

Can you try creating a new project to see if the issue occurs?

Also you might consider uploading the Manuskript project that crashes so that we can try to re-create the issue.

**Comment by bepolymathe** [comment] 2019-04-17 19:06
Same problem with new projet --» [New projet](https://cloud.palimpsestes.net/s/xHyTDatWkozT4Xo)
And the projet itself --» [Projet](https://cloud.palimpsestes.net/s/W2GcBigfgzDJSag)

**Comment by gedakc** [comment] 2019-04-17 19:10
Can you provide answers to the questions that @worstje originally asked for?

Did you install from RPM, run from source code, etc?

What software versions of Python and Qt are you using?
See **Help -> About**.

**Comment by bepolymathe** [comment] 2019-04-17 19:17
Yes of course. 

Installed from RPM version and for the below

![image](https://user-images.githubusercontent.com/29939805/56314751-38d3d800-6156-11e9-9394-75209bc85195.png)

**Comment by gedakc** [comment] 2019-04-17 19:23
Interesting.  I am unable to reproduce the issue, but my Fedora 29 VM has:

Python 3.7.0
PyQt 5.11.2
Qt 5.11.2

**Comment by bepolymathe** [comment] 2019-04-17 19:28
I'm not crazy then ;-) 

Maybe too fresh Python version ?

**Comment by gedakc** [comment] 2019-04-17 22:28
I did an Internet search on "`qt.qpa.wayland: Wayland does not support QWindow::requestActivate()`" that you reported in an earlier comment and get lots of matches.

Quote from [Comparing Qt Widgets App under Gnome wayland using platform wayland-egl to xcb](https://forum.qt.io/topic/90639/comparing-qt-widgets-app-under-gnome-wayland-using-platform-wayland-egl-to-xcb/8):

> > `qt.qpa.wayland: Wayland does not support QWindow::requestActivate()`
>
> This means your window tried to grab focus in the compositor, which is not allowed in wayland. Don't create a bug for it, there's nothing we can do.

Quote from [Qt Creator / QTCREATORBUG-20400: Fails to go into Full Screen on Wayland](https://bugreports.qt.io/browse/QTCREATORBUG-20400):

> This should be fixed when QtCreator starts using Qt 5.12

> As a workaround, you can try to set QT_WAYLAND_SHELL_INTEGRATION=xdg-shell-v5 or QT_WAYLAND_SHELL_INTEGRATION=wl-shell.
>
> Depends on your compositor whether it's supported.

It seems as if there a issues with Qt, Wayland, and the compositor.  One user reported switching to KDE to avoid the issue.  You might also consider downgrading to earlier versions of Python, PyQt, and Qt.

**Comment by bepolymathe** [comment] 2019-04-18 06:04
Thank you for that clarification. That's a pity. I hope this problem will be fixed because other distributions will switch to Wayland later this year. 

Is there a Flatpak version of Manuskript?

**Comment by gedakc** [comment] 2019-04-18 15:20
Manuskript does run under Wayland.  The problem you encountered appears to be a problem with the versions of Qt, Wayland, and the compositor.  Manuskript runs properly on my Fedora 29 VM with Wayland, and the above mentioned Qt versions.

Can you try the workarounds listed above to see if they help in your situation?

For example:
    `export QT_WAYLAND_SHELL_INTEGRATION=xdg-shell-v5` 
or  
     `export QT_WAYLAND_SHELL_INTEGRATION=wl-shell`  
before invoking manuskript.

**Comment by bepolymathe** [comment] 2019-04-18 19:39
With   "export QT_WAYLAND_SHELL_INTEGRATION=xdg-shell-v5" --» same problem
With  "export QT_WAYLAND_SHELL_INTEGRATION=wl-shell" --» same problem

**Comment by bepolymathe** [comment] 2019-05-21 13:24
After upgrading to Fedora 30... problem seems be solve. Why ? I don't know

**Comment by gedakc** [comment] 2019-05-21 15:26
@bepolymathe thanks for reporting back that manuskript 0.9.0 works for you on Fedora 30.

My guess is that Fedora 30 includes newer versions of Qt that may include some bug fixes.

Would you please provide the software versions of Python and Qt are you are now using?
See **Help -> About**.

**Comment by bepolymathe** [comment] 2019-05-21 16:30
Yes, new version of Qt

![image](https://user-images.githubusercontent.com/29939805/58113726-79f85580-7bf6-11e9-9054-4ed3c2dd35eb.png)

**Comment by gedakc** [comment] 2019-05-21 16:35
It seems that Qt was updated from 5.11.3 to 5.12.1 with the upgrade from Fedora 29 to 30.

It is possible that the cause of the issue was a problem with Qt 5.11.3.  In my testing with Qt 5.11.2 the crash did not occur.

Shall we close this issue as resolved?

**Comment by bepolymathe** [comment] 2019-05-22 08:08
Yes, we can close. Thank you.

**Closed** 2019-05-22 15:16 UTC
