### ISSUE TITLE
Crash on export

### ISSUE THREAD

**Issue by WildCerebrus** [olivierkes/manuskript#344] opened 2018-05-03 22:23 UTC
I hope this isn't a doublon but everytime I try to compile manuskript shut down

win10 x64
manuskript 0.6.0

stay connected for more informations

**Comment by gedakc** [comment] 2018-05-04 15:40
To get more debug information please run manuskript from the command prompt.

If you are running the EXE from the PyInstaller package then change into the directory in which manuskript was extracted and run the `manuskript.exe` file:
```
cd \path-to-where-manukript-was-unzipped
manuskript.exe
```
Information, debug, and error messages should be shown in the terminal window while manuskript is running.

**Comment by WildCerebrus** [comment] 2018-05-04 18:39
Actually, I did but the command window shut down at the same moment

**Comment by gedakc** [comment] 2018-05-04 20:43
Strange.  You might try to [Run Manuskript from Source Code on Windows](https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Windows).

**Comment by gedakc** [comment] 2018-08-16 21:31
This issue might be a duplicate of issue #331.

**Comment by gedakc** [comment] 2018-08-21 17:06
Closing this issue as a duplicate of issue #331.

If you discover that the issue remains when using the latest **develop** branch then please add steps to reproduce the crash and we can re-open the issue.

**Closed by gedakc** 2018-08-21 17:06 UTC
Labels: bug
