### ISSUE TITLE
[Enhancement Request] change Editor to a more "Outline Overview"

### ISSUE THREAD

**Issue by Mannshoch** [olivierkes/manuskript#805] opened 2020-09-14 18:02 UTC
Add drag and drop to move passage between scenes and chapters

Current view:
![OldList](https://user-images.githubusercontent.com/7795891/93120830-3a475e00-f6c4-11ea-9349-37c22721d1c1.png)

New List:
![NewList](https://user-images.githubusercontent.com/7795891/93120855-44695c80-f6c4-11ea-9619-8a95fc45d7bf.png)

**Comment by TheJackiMonster** [comment] 2021-02-21 23:31
I would close this being a duplicate of #64. I also think this should be addressed soon.

**Closed by TheJackiMonster** 2021-02-21 23:31 UTC
Labels: duplicate, enhancement
