### ISSUE TITLE
Wrong layout on first screen

### ISSUE THREAD

**Issue by rfog** [olivierkes/manuskript#718] opened 2020-01-19 14:44 UTC
See attached capture. Computer is a HP Spectre x360 13" 4K screen with a zoom of 250%. 

![image](https://user-images.githubusercontent.com/1958131/72682900-88bf4100-3ad2-11ea-9f81-19195247acfa.png)

**Comment by rfog** [comment] 2020-01-19 14:48
Here the screen configuration:

"Horizontal" is "Landscape" in Spanish.

![image](https://user-images.githubusercontent.com/1958131/72682943-11d67800-3ad3-11ea-86e8-1b2476d71ee0.png)

**Comment by gedakc** [comment] 2020-01-19 17:25
You might try the suggestions mentioned in issue #463 in an effort to work around issues with your HiDPI 4k screen.

**Comment by gedakc** [comment] 2020-01-20 16:31
Thank you @rfog for reporting back with how you plan to proceed.

Manuskript is a Free Software project run by volunteers.  If someone volunteers to build other Windows packages then we can look into making these available too.

'Closing this report as a duplicate of issue #463.

**Closed by gedakc** 2020-01-20 16:31 UTC
