### ISSUE TITLE
Jumbled Keys

### ISSUE THREAD

**Issue by Glotto** [olivierkes/manuskript#311] opened 2018-01-29 09:27 UTC
I've been using the windows executable to get a feel for Manuskript and for the most part am enjoying it quite a lot. 

The main reason I decided to try it was for the linux version (a total linux newb but I wanted something portable and I've been using 'Linux Deploy' to run Ubuntu (and tested with Debian) on my android tablet. 

This seems to work very well for everything but Manuskript. In the terminal and Firefox for example the keys work exactly as expected, however... Manuskript seems to jumble them all up. It isn't totally random as each key does appear assigned to something ('5' is backspace, 'enter' is space, etc.) 

[Screenshot_20180129-074422.png](https://postimg.org/image/7fzs7cb9h/)

As you can see from the create new project screen name has come out as 'ngbn' when I had typed 'test' (note the bar at the bottom that shows what I actually typed).

As implied, I have no idea what I'm really doing in linux so the problem may be on my end :) Any ideas?

Edit: This is on a bluetooth keyboard.

**Comment by gedakc** [comment] 2018-01-29 18:03
Although I have not encountered the issue described, my guess is that something is incorrect in the environment.  My first thought was that the wrong keyboard layout was selected, but the report indicates that the correct characters appear for Firefox and Terminal.  *Could there be a Python3 specific keyboard setting?*

I've run Manuskript on many GNU/Linux distributions including Debian, Ubuntu, Fedora, and openSUSE and have not encountered the issue of incorrect key mapping in a single application.

**Comment by Glotto** [comment] 2018-02-02 04:43
I'm not sure how to check that, but I've used a few other word processors and they all seem to be working accurately. 
What I have noticed though is _how_ the letters are jumbled. If for example I try to type...
abcdefghijklmnopqrstuvwxyz (the alphabet) 

It comes out as...
asdfghjkl;'`\zxcvbnm,./* (pretty much the UK keyboard layout - the letters are the bottom two rows in order)

**Comment by gedakc** [comment] 2018-02-09 17:41
Are you trying to run the Windows version of manuskript under GNU/Linux?

The reason I ask is because the screen shot you provided does not look like the usual Windows desktop.

If you are running Linux, can you try using the Linux packages instead?

**Comment by gedakc** [comment] 2018-11-21 18:19
Closing this issue because no further input has been provided and I have not been able to reproduce the issue.  I am marking this issue as **invalid** so that it does not get included in the automatically generated CHANGELOG.md file.

**Closed by gedakc** 2018-11-21 18:19 UTC
