### ISSUE TITLE
Don't open msk from command line

### ISSUE THREAD

**Issue by Mte90** [olivierkes/manuskript#993] opened 2022-01-14 21:01 UTC
```
$ manuskript romanzo.msk 
usage: manuskript [-h] [--console] [-v] [-L LOGFILE] [FILENAME]
manuskript: error: unrecognized arguments: romanzo.msk
```
An example of what I get.
Instead if I open the program and use open feature everything is fine.

**Comment by katafrakt** [comment] 2022-02-09 21:59
What system are you using and how did you install manuskript? I have just checked on Linux and manuskript from git and it seems to work as expected (opens a project).

**Comment by Mte90** [comment] 2022-02-10 12:27
I tried with the debian one and the code of this repository (I am using that now)

**Comment by katafrakt** [comment] 2022-02-10 15:53
So you actually call `bin/manuskript` from repository root or `manuskript` from `bin` directory? Or do have it added to `PATH`?

**Comment by Mte90** [comment] 2022-02-12 13:47
So In the laptop I have the one from the debian repository and I have the issue.
When I had the dev version I think that I had the same issue but i don't remember now.

**Comment by TheJackiMonster** [comment] 2023-02-10 21:55
Seems to work fine with release 0.14.0 and newer... so I'll close this because I can't reproduce the issue.

**Closed by TheJackiMonster** 2023-02-10 21:55 UTC
Labels: bug
