### ISSUE TITLE
Application language still the same after changing it in the settings.

### ISSUE THREAD

**Issue by din-din** [olivierkes/manuskript#411] opened 2018-11-14 19:25 UTC
On first startup Manuskript is forced into the system language of the machine (which, while not exactly my favourite, is fine)
However, upon changing the language in settings from German to English and restarting, the app was still in German, even though the settings said it should be in English. The console even said that it had loaded the German translation file on startup.
Deleting the app folder completely and redownloading gave the same issue.
I could resolve it by deleting the German localisation files from the i18n folder, which switches everything to English, but shouldn't be necessary if there's already a switch language option in the settings.

**Comment by gedakc** [comment] 2018-11-14 19:35
Can you provide additional information such as:
- Operating System?
- Manuskript version?
- Console log?  (text messages displayed when manuskript started from a terminal window)
- Screen Shot?

On my Kubuntu 16.04 GNU/Linux system I've tried switching from English to French to German and back again to English.  In each case when I restarted Manuskript it started up in the chosen language.

**Comment by din-din** [comment] 2018-11-14 19:48
Of course, sorry. It only turned into a sort of bug report while writing it and then I forgot.

I run Windows 7 64 bit, Manuskript 0.7.0

This is a screenshot from the **console** of the one where I deleted the German localisation files
![2018-11-14 20_42_32-c__program files_manuskript_manuskript exe](https://user-images.githubusercontent.com/33520104/48508094-ebbda400-e84d-11e8-99de-576087666b24.png)
Screenshot of the **settings:**
![image](https://user-images.githubusercontent.com/33520104/48508147-1871bb80-e84e-11e8-8e84-39bd63b0e0b5.png)



I downloaded a fresh copy just now to test, opened it and left everything untouched with these results:
**Console log:**
![image](https://user-images.githubusercontent.com/33520104/48508264-6981af80-e84e-11e8-879d-1520b13bfb9c.png)

**Settings window:**
![image](https://user-images.githubusercontent.com/33520104/48508290-743c4480-e84e-11e8-864a-3eeb2475d822.png)

The application itself is in German.

**Comment by gedakc** [comment] 2018-11-14 19:54
Would you be able to describe the problem further?

From the Console Log I can see that the `manuskript_de_DE.qm` translation file was loaded.

From both of the above screen shots the language is listed as English and the screenshot shows English.  Is there some part of the application that is in German when the language has been specified as English?

**Comment by din-din** [comment] 2018-11-14 19:57
Sure thing.
Everything except the settings window is in the language from the translation file. German in this case.

![image](https://user-images.githubusercontent.com/33520104/48508784-c9c52100-e84f-11e8-8822-7d500da7e833.png)

**Comment by din-din** [comment] 2018-11-14 20:00
Changed it to Dutch and after a restart eveerything is in English, even though the Dutch translation file is supposed to be loaded.

![image](https://user-images.githubusercontent.com/33520104/48509000-435d0f00-e850-11e8-920b-85c6d33f0f51.png)

**Comment by gedakc** [comment] 2018-11-14 20:14
Thanks for providing both screen shots.

The Dutch screen shot had me really confused.  Then I looked at the Dutch translation file and learned that many words are not yet translated.  For example [the word "**General**" in the main window ](https://github.com/olivierkes/manuskript/blob/97e4679d83313f367b8b65f4e865a4bdec6bb984/i18n/manuskript_nl.ts#L451) is not translated.  This explains why Manuskript is falling back to use the English language because the Dutch translation is missing.

The German screen shot shows both English and German.  From a peak at the German translation file it appears that ["**General**" in the main window](https://github.com/olivierkes/manuskript/blob/97e4679d83313f367b8b65f4e865a4bdec6bb984/i18n/manuskript_de.ts#L468) and ["**General settings**" in the settings window](https://github.com/olivierkes/manuskript/blob/97e4679d83313f367b8b65f4e865a4bdec6bb984/i18n/manuskript_de.ts#L1450) have both been translated.  However we have a discrepancy in which language/translation is displayed in the main window and the settings window.

More investigation is required to determine the cause of this inconsistency.

**Comment by din-din** [comment] 2018-11-14 20:21
Ah yes, that would make sense for the Dutch screenshot. I was thinking the same after posting the screenshot and remembering that the translations are still somewhat of a WIP.


However the German issue confuses me. That first screenshot I posted, where the settings said English and the app itself was in German was from the fresh copy that had the `manuskript_de_DE.qm` loaded, although going by the settings the app was supposed to be in English.

I've also had this issue with German/English on both machines I've tested this on (both Windows 7, 64bit, same 0.7.0 Manuskript version), where even though I had changed it to English in the settings, it would still force-load the `manuskript_de_DE.qm` and thus leave my Manuskript in German.

**Comment by gedakc** [comment] 2018-11-14 20:33
The source code that loads the language translation is in the [manuskript/main.py](https://github.com/olivierkes/manuskript/blob/97e4679d83313f367b8b65f4e865a4bdec6bb984/manuskript/main.py#L38) file.  I suspect the issue with the use of the German translation, even when English has been specified, is in this section of code because there is no special handling for the default language "English".

Are you up to the challenge of trying to fix this issue?
If so a good place to start is to [Run Manuskript from Source Code on Windows](https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Windows).

**Comment by din-din** [comment] 2018-11-14 20:43
I will definitely look into it, but since I've only just gotten into Python (as in just starting out and it's a very slow start) I don't think I can be of much help.

**Comment by gedakc** [comment] 2018-11-14 20:59
That would be Great!

There is no pressure or time deadline.  The pace can be dictated by your own curiousity and drive.  :-)

**Comment by lingsamuel** [comment] 2018-12-07 14:58
I believe this bug is something about PyQt `QApplication`. 
I don't know much about Qt, but I noticed that manuskript init a `QApplication(sys.argv)` in `main.py`, and install `translator` for it.

And then I write some test code for `welcome_ui.py` and `settings_ui.py` because I found that translation for `welcome` always work but for `settings` always does not work.

Test Code:
```python
# welcome_ui.py
    def setupUi(self, welcome):
        welcome.setObjectName("welcome")
        print(QtCore.QCoreApplication.translate("Settings", "General settings"))
        print(QtCore.QCoreApplication.translate("welcome", "Next time, automatically open last project"))
```
I just copy and paste them to `settings_ui.py`.

These two sentences are both in `welcome`, but it's does not matter because I just want to test if the translator still works.
Then the result is: **`welcome_ui.py` always print translated sentences, `settings_ui.py` always print original sentences.**

The facts are already obvious, the translator works properly, but it didn't install in `application`, maybe because the application of `settings_ui` is different from the one which initialed at `main.py`.

**Comment by lingsamuel** [comment] 2018-12-07 16:16
Yes my guess is right.
The core is `appTranslator = QTranslator(app) # register parent`

**Comment by gedakc** [comment] 2018-12-09 18:49
@din-din we commited a fix for this issue.

Would you be able to [Run Manuskript from Source Code](https://github.com/olivierkes/manuskript/wiki#install-source-code-more-work-runs-on-more-os-platforms), checkout the **develop** branch, and then test to see if this issue is fixed for you?

**Closed** 2018-12-11 16:17 UTC
Labels: bug
