### ISSUE TITLE
Project not opening 

### ISSUE THREAD

**Issue by Vaikriya** [olivierkes/manuskript#319] opened 2018-02-19 02:52 UTC
So I have a project that I've been working on all day and then suddenly the program crashed. Since this isn't too uncommon I wasn't worried that much, but then when I tired to open it back up this happened 

![error](https://user-images.githubusercontent.com/36613490/36360871-6ea610c6-151f-11e8-85ec-05e918e81be0.png)

I have seen the other issue report similar to this and tried the method you suggested to fix it, however it hasn't worked due to the project being saved to a single msk file, so I can't even go into the xml files to fix it. 

Please help.

**Comment by gedakc** [comment] 2018-02-19 18:41
Hi @Vaikriya.  We are sorry to hear that you encoutered this problem.

I think the similar report you referred to is issue #315.  In that case two instances of manuskript were opened on the same project file.  Unfortunately running multiple instances of manuskript on the same project file is neither supported nor prevented.

When the project **is not saved as a single file** then the work-around discovered by @siliconserf involved "*... Wiping out all but the basic outline markers...*".

Following are some steps to try to resolve the issue when the manuskript project **is saved as a single file**:

In the following steps we will create a manuskript project called "myrestore.msk" which is stored in multiple folders and files.

1. Make a backup copy of the manuskript project.  (E.g. copy myproject.msk to myproject.msk.backup).
2. Open a terminal window / command prompt.
3. Navigate to the directory that contains the manuskript project.
4. Make a subdirectory for the project contents.  E.g., `mkdir myrestore`
5. Change into the `myrestore` directory.  E.g., `cd myrestore`
6. Extract the single project file into multiple files.  E.g., `unzip ../myproject.msk` for Linux, `unzip ..\myproject.msk` for Windows.
   *At this point you should have direct access to the content of your novel stored in separate folders and text files in case you wish to try rebuilding manually.*
7. Now use a text editor to open the file `revisions.xml`.
    - remove `text="..."` contents from the from `<outlineItem> ... </outlineItem>` sections.
    - remove lines containing `<revision ... />`
9. Save the file and exit the editor.
10. Create `myrestore.msk` file which only contains the number "1".  E.g., `echo 1 > myrestore.msk` in Linux, try notepad in Windows.
12. Start manuskript and try to open `myrestore.msk` to see if it will load.

Please let us know how you make out.

**Comment by siliconserf** [comment] 2018-02-19 20:36
On my Linux machine is the program Engrampa Archive Manager. I used it to open the MSK file and directly edit the contents. It won't let you delete a file from the archive, but you can edit. But MAKE A BACKUP before you mess with the internals of the project file. Come to think of it, Manuskript is still a little raw. Make independent file backups every day you run the program.

**Comment by siliconserf** [comment] 2018-02-19 21:19
BTW, if you un-check the Single File save option you get an extracted file version of the project when a revision is saved. Saves a lot of steps if you gorp the Revisions data base. From what I found exploring my problem, the ID section for some entries was getting deleted. But efforts to finesse that error didn't work, so I just brute forced the problem by deleting everything but the first line. I've yet needed to go back a revision so losing that trail didn't worry me. (I save to a new name when making major changes, usually _filename-n_.)

**Comment by gedakc** [comment] 2018-08-16 18:40
Following is the console log re-typed (may contain errors) in case it will be useful in the future.

```
Traceback (most recent call last):
  File "manuskript\ui\welcome.py", line 127, in loc
  File "manuskript\mainWindow.py", line 517, in loadProject
  File "manuskript\mainWindow.py", line 742, in loadDatas
  File "manuskript\loadSave.py", line 66, in loadProject
  File "manuskript\load_save\version_1.py", line 877, in loadProject
  File "manuskript\load_save\version_1.py", line 958, in appendRevisions
  File "manuskript\load_save\version_1.py", line 958, in appendRevisions
  File "manuskript\load_save\version_1.py", line 958, in appendRevisions
  File "manuskript\load_save\version_1.py", line 958, in appendRevisions
  File "manuskript\load_save\version_1.py", line 958, in appendRevisions
  File "manuskript\load_save\version_1.py", line 958, in appendRevisions
  File "manuskript\load_save\version_1.py", line 963, in appendRevisions
  File "lxml.etree.pyx", line 2366, in lxml.etree._Attrib.__getitem__ (src\lxml\lxml.etree.c:62258) Key Error: 'ID'
```

I am closing this issue with tag 'invalid' because we have received no further feedback on this issue.  Additionally I have been unable to reproduce the error.

**Closed by gedakc** 2018-08-16 18:40 UTC
Labels: invalid
