### ISSUE TITLE
[MacOS Sierra] Crash when clear format 

### ISSUE THREAD

**Issue by cfrancois7** [olivierkes/manuskript#285] opened 2018-01-01 19:27 UTC
The edition menu goes wrong on MacOs.
When I try to clear the format (CTRL+P), manuskript crashes.

The version is the experimental one: [0.6.1](https://github.com/katafrakt/manuskript/releases/download/0.6.1/manuskript-0.6.1-osx.zip).

<img width="385" alt="capture d ecran 2018-01-01 a 20 21 15" src="https://user-images.githubusercontent.com/11422336/34470460-5ec1567a-ef31-11e7-9231-011792c198d3.png">

MacOs version: 10.13.2

See also https://github.com/olivierkes/manuskript/issues/286 that is related.

**Comment by gedakc** [comment] 2018-01-02 17:15
I have been able to confirm this issue with Manuskript 0.6.0 on Kubuntu 16.04.

Note that this issue does not occur in the git **develop** branch with last commit 3c140d755f so it appears that the bug has already been fixed.  I suspect the problem was fixed with the removal of the formatting buttons.

This bug is a duplicate of issue #250 which is a duplicate of issue #59.  The fix will be included in the next release of manuskript (0.7.0).

For anyone wishing to recreate the problem the steps to recreate are:

1. Open a project in manuskript.
2. Type in some text surrounded by double asterisks.  E.g.  **sample**
3. Position the cursor inside the "sample" text.
4. Type **Ctrl+P**, and manuskript crashes with the following console output.

```
$ manuskript &
Debug: Web rendering engine used: QWebView
Running manuskript version 0.6.0.
Note: No translator found or loaded for locale en_CA.
Loading: /home/gedakc/tmp/deleteme-3.msk
Detected file format version: 1. Zip: True.
Project /home/gedakc/tmp/deleteme-3.msk loaded.
Traceback (most recent call last):
  File "/home/gedakc/workspace/manuskript/bin/../manuskript/ui/editors/textFormat.py", line 68, in setFormat
    self._textEdit.applyFormat(act.text())
  File "/home/gedakc/workspace/manuskript/bin/../manuskript/ui/views/textEditView.py", line 554, in applyFormat
    MDFormatSelection(self)
TypeError: MDFormatSelection() missing 1 required positional argument: 'style'
```

**Closed** 2018-01-02 17:15 UTC
Labels: duplicate
