### ISSUE TITLE
Manuskript : CRITICAL An unhandled exception has occurred

### ISSUE THREAD

**Issue by quiltedstars** [olivierkes/manuskript#970] opened 2021-12-01 04:52 UTC
Hiya,

Downloaded Manuskript on my Void Linux (kernel 5.13.19_1), but it won't open. I get the following output when I try and open via terminal:

```
[void@void conky-themes]$ manuskript
CRITICAL> An unhandled exception has occurred!
Traceback (most recent call last):
  File "/bin/manuskript", line 13, in <module>
    main.run()
  File "/usr/share/manuskript/bin/../manuskript/main.py", line 291, in run
    app, MW = prepare(arguments)
  File "/usr/share/manuskript/bin/../manuskript/main.py", line 170, in prepare
    from manuskript.mainWindow import MainWindow
  File "/usr/share/manuskript/bin/../manuskript/mainWindow.py", line 23, in <module>
    from manuskript.models.worldModel import worldModel
  File "/usr/share/manuskript/bin/../manuskript/models/worldModel.py", line 11, in <module>
    from manuskript.ui import style as S
  File "/usr/share/manuskript/bin/../manuskript/ui/style.py", line 36, in <module>
    highlightLight = F.mixColors(highlight, window, .3)
  File "/usr/share/manuskript/bin/../manuskript/functions/__init__.py", line 197, in mixColors
    return QColor(r, g, b) if not fromString else QColor(r, g, b).name()
TypeError: arguments did not match any overloaded call:
  QColor(Qt.GlobalColor): argument 1 has unexpected type 'float'
  QColor(int): argument 1 has unexpected type 'float'
  QColor(QRgba64): argument 1 has unexpected type 'float'
  QColor(Any): too many arguments
  QColor(): too many arguments
  QColor(int, int, int, alpha: int = 255): argument 1 has unexpected type 'float'
  QColor(str): argument 1 has unexpected type 'float'
  QColor(Union[QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'
```

**Comment by TheJackiMonster** [comment] 2021-12-01 11:05
This should be a duplicate of #957. So this problem has been fixed on the develop branch already with commit 15edb6e. You could try [run Manuskript from source](https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Linux).

**Comment by quiltedstars** [comment] 2021-12-01 15:09
Thanks so much! Running from source works :D

**Closed** 2021-12-01 17:41 UTC
Labels: duplicate
