### ISSUE TITLE
Bug in 'World' section

### ISSUE THREAD

**Issue by Dreamy-pen** [olivierkes/manuskript#126] opened 2017-06-29 17:25 UTC
Great Project!

I may have found a bug. Every time when I try to  add a 'description' or a 'source of passion' in a 
World-item   Manuskript crashes after a few seconds.

I use version 4.0 (downloaded it yesterday on a Windows 7 computer and apart from the possible bug above, it works great).

**Comment by gedakc** [comment] 2017-07-01 16:45
@Dreamy-pen, so far I have been unable to reproduce this crash you experienced.

Would you be able to provide more information, such as the exact steps used, and also the log from manuskript?

To capture the manuskript log of actions:
1.  Open a command prompt
2.  Change into the directory that contains `manuskript.exe`
3.  Type in `manuskript.exe` and press enter to start the program running
4.  Perform the steps that cause the crash.
5.  Copy the manuskript log text from the command prompt and paste it into this report.

**Comment by Dreamy-pen** [comment] 2017-07-01 18:20
Thanks for your help @gedakc 

This is the log:
---
Microsoft Windows [versie 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Alle rechten voorbehouden.

C:\Users\DELL>manuskript\manuskript.exe
Running manuskript version 0.4.0.
Warning: failed to load translator for locale nl_NL...
Loading: F:/00000xxx/Poging Sterre in Manuskript.msk
Detected file format version: 1. Zip: False.
There are some doublons: ['2', '2']
Project F:/00000xxx/Poging Sterre in Manuskript.msk loaded.
Could not parse stylesheet of object 0x45db548
Could not parse stylesheet of object 0x45db548
Could not parse stylesheet of object 0x45db548
Could not parse stylesheet of object 0x45db548
Could not parse stylesheet of object 0x45db548
Traceback (most recent call last):
  File "manuskript\mainWindow.py", line 488, in saveDatas
  File "manuskript\loadSave.py", line 21, in saveProject
  File "manuskript\load_save\version_1.py", line 363, in saveProject
  File "os.py", line 237, in makedirs
FileExistsError: [WinError 183] Kan geen bestand maken dat al bestaat: 'F:/00000
xxx\\Poging Sterre in Manuskript\\outline\\00-Inleiding\\0-'

C:\Users\DELL>

===

Error 183 is Dutch for: 'Can't make a file that already exists'.

This is what I did: 
I opened the program. 
I went to 'Recents' and selected a file.
I went to 'World' , selected an item and typed something in the field 'description'. After a few seconds the program crashed.

---
This is the exact problem I wrote about above. Hopefully this makes any sense

**Comment by gedakc** [comment] 2017-07-01 18:48
Thanks for providing the log and the translation.

As you indicated it appears that Manuskript is trying to create a directory that already exists.  See [manuskript/load_save/version_1.py](https://github.com/olivierkes/manuskript/blob/0.4.0/manuskript/load_save/version_1.py#L363).

`Detected file format version: 1. Zip: False.`

The above log line indicates that in menu **Edit -> Settings** the setting for _Save to one single file_ is not checked.  This would be consistent with a project save needing a directory for some of the project contents.

I have tried this setting both checked and unchecked and both worked fine.  This leads me to believe that there might be a file permission error or something like that.

Can you check to see if your userid has "write" access to the directory?

Also it might help to at least once enable the setting to _Save to one single file_ and then save the project to see if that continues to work.

**Comment by Dreamy-pen** [comment] 2017-07-01 19:01
To start with your last sentence. Yes, when I enabled 'save to one single file' and now everything went fine when I did the same things that earlier caused the program to crash.

When I started this project the default value was 'save to one single file'. After some time I changed that and perhaps the changing of this setting did cause the trouble.

I haven't got a clue how I can find my userid and find out whether I have 'write' access to the directory. This coding stuff is very new to me, but as a lifelong learner, I will find out how things work, sooner or later. 

Thank you so much for helping me!

**Comment by gedakc** [comment] 2017-07-02 16:28
Perhaps this link on how to view/modify permissions in Windows 7 will help.

[Windows - Set, View, Change, or Remove Permissions on Files and Folders](https://technet.microsoft.com/en-us/library/cc754344(v=ws.11).aspx)

**Comment by Dreamy-pen** [comment] 2017-07-03 07:44
Thanks!  There's a whole new world opening for me. ;) 

As a 'user' I did not have 'writing' permissions in the Manuskript directory. Now I do. Is this what I was meant to do?

Before I enabled the 'writing' permission, I tried to make a project with 'not saving in a single file' from the very beginning. The program crashed just like I reported earlier.  

 Anyway, one of these days,  I'll have another try at using Manuskript. And then I will know whether enabling the writing permissions in the Manuskript folder did the trick.

**Comment by gedakc** [comment] 2017-07-03 15:07
> As a 'user' I did not have 'writing' permissions in the Manuskript directory. Now I do. Is this what I was meant to do?

Yes.  In order to save your work you require write access to be able to create new directories and update files.

'Let us know how you make out.

**Comment by olivierkes** [comment] 2017-10-15 21:23
Do you think this is fixed with changes made for #138 ?

**Comment by Dreamy-pen** [comment] 2017-10-16 07:14
Problem solved. Thanks!

**Closed** 2017-10-16 07:15 UTC
Labels: bug
