### ISSUE TITLE
Outline not showing properly

### ISSUE THREAD

**Issue by phil123456** [olivierkes/manuskript#840] opened 2021-03-14 20:51 UTC
Hi

the outline is not working properly, compared to the screenshots on the web site

![image](https://user-images.githubusercontent.com/13568652/111083796-7c384c00-850f-11eb-80f7-2771aeecc5f4.png)

can you fix it ?

thanks

**Comment by TheJackiMonster** [comment] 2021-03-14 21:02
Do you use any specific theme? Also which OS do you use?

Does it help if you resize the story line vertically? (I can't reproduce it on my system)

**Comment by phil123456** [comment] 2021-03-14 21:16
just a fresh install, I dont even know where to change the theme, it's a first try
I use win 10, resizing does not change anything

**Comment by phil123456** [comment] 2021-03-14 21:21
I tried changing the style in the settings, but it does not help

**Comment by TheJackiMonster** [comment] 2021-03-14 22:31
Do you use a HiDPI monitor? The issue #632 looks quite similar.

**Comment by phil123456** [comment] 2021-03-15 13:08
I have 4k and 8k monitors, but the issue persists no matter which monitor I use

I am a dev too so maybe I could check some logs or try some python code to debug it or something
just let me know

here is a screenshot in 1920x1080

![image](https://user-images.githubusercontent.com/13568652/111157960-cb29c400-8597-11eb-91d8-2160e3512bd2.png)

**Comment by TheJackiMonster** [comment] 2021-03-15 13:53
So I would close this issue as duplicate then because it seems to be the same bug as reported in #632. I would recommend looking into [storyLineView.py](https://github.com/olivierkes/manuskript/blob/develop/manuskript/ui/views/storylineView.py) then. The problem is probably related to the story line being rendered in a custom way instead of using or table or other widgets.

```
        LINE_HEIGHT = 18
        SPACING = 3
        TEXT_WIDTH = self.sldTxtSize.value()
        CIRCLE_WIDTH = 10
        LEVEL_HEIGHT = 12
```
You will find in the code that most sizes and offsets are fixed. I would assume this could be adjusted in relation to a higher DPI to fix this but I haven't really looked into it.

**Closed** 2021-03-15 13:53 UTC
Labels: UI, bug, duplicate

**Comment by phil123456** [comment] 2021-03-15 14:42
1920 is rather standard nowadays :-)
also a pixel is a pixel, especialy if values are fixed and not calculated
I'll have a look
