### ISSUE TITLE
Italian translation not applied, application still english.

### ISSUE THREAD

**Issue by broh999** [olivierkes/manuskript#599] opened 2019-07-02 12:45 UTC
OS Win 10
When I change language settings to "Italian", closing and restarting the application, the UI is still in english. In the console I see 
```
Found translation in settings: manuskript_it.qm
Loaded translation from settings: manuskript_it.qm.
```
I also tried with other languages (Es, Fr..) and the UI correctly change in the selected language.

I'm available for details, thank you.

**Comment by gedakc** [comment] 2019-07-06 17:00
Please provide addition details, such as the version of manuskript, and also provide a screen shot or otherwise describe what area of Manuskript and specific text strings do not show an "Italian" translation?

Were you aware that language translation is a work-in-progress?  See [Manuskript Translation Status](https://hosted.weblate.org/projects/manuskript/translations/).

According to the following screen shot taken when we released Manuskript 0.9.0 the Italian translation was about 85% complete.

![manuskript-translations-20190404](https://user-images.githubusercontent.com/10405019/60759146-03b08680-9fdd-11e9-926f-e395e6ed47db.png)

**Comment by broh999** [comment] 2019-07-08 14:23
Version 0.9.0
No words in Italian, English only everywhere.

![Cattura](https://user-images.githubusercontent.com/34166233/60817782-9e0af880-a19c-11e9-93d8-fd55938b1ce3.JPG)

**Comment by gedakc** [comment] 2019-07-08 21:08
I see the same lack of Italian translations.

From looking deeper it would appear that many of the text strings in Manuskript have not been translated and instead have been left blank.  For example see the missing string translations from the  main window contained in the [`i18n/manuskript_it.ts`](https://github.com/olivierkes/manuskript/blob/761be5784a9ca44efd25d40fc285f11131835b83/i18n/manuskript_it.ts#L456) file.

For example:
https://github.com/olivierkes/manuskript/blob/761be5784a9ca44efd25d40fc285f11131835b83/i18n/manuskript_it.ts#L456-L512

The problem is that there is no Italian text between the `<translation>` and `</translation>` tags.

Hence it looks like we need volunteer(s) to fill out the Italian translations.

**Comment by gedakc** [comment] 2019-07-14 16:35
I have updated the **develop** branch with the current state of translations from [Weblate](https://hosted.weblate.org/projects/manuskript/translations/).  Following is a screen shot of the Main Window with the **Italian** translation enabled.

![Manuskript-Main-Window-Italian](https://user-images.githubusercontent.com/10405019/61186441-c4a8b380-a622-11e9-8479-c9e46da985a6.png)

These language translation updates will be included in the next release of Manuskript.  If you wish to take advantage of these updates sooner than the next release then consider [Running Manuskript from Source Code](https://github.com/olivierkes/manuskript/wiki#install-source-code-more-work-runs-on-more-os-platforms).

**Closed by gedakc** 2019-07-14 16:35 UTC

**Comment by gedakc** [comment] 2019-09-11 22:26
The fix for the Italian translation is currently only available in the git **develop** branch.  You would need to [Run Manuskript from Source Code](https://github.com/olivierkes/manuskript/wiki#install-source-code-more-work-runs-on-more-os-platforms) if you wish to use the **develop** branch.
