### ISSUE TITLE
Renaming texts leads to occasional crashes - Windows 260 char MAX_PATH limit exceeded

### ISSUE THREAD

**Issue by worstje** [olivierkes/manuskript#517] opened 2019-02-28 10:51 UTC
I am currently planning a plot arc and setting up all the various texts to denote the rough time span and developments within. This means I am creating new texts and renaming them, assigning perspectives, and so forth. Alas: it has been crashing regularly while doing this.

    Traceback (most recent call last):
      File "manuskript\mainWindow.py", line 765, in saveDatas
      File "manuskript\loadSave.py", line 21, in saveProject
      File "manuskript\load_save\version_1.py", line 382, in saveProject
    FileNotFoundError: [Errno 2] No such file or directory: 'P:/Projects/Writing/AOitNoL\\AOitNoL\\outline\\5-2004_-WIP-\\21-August_-_C_is_dragged_off_to_the_mall_by_S_to_spend_time_together-_He_is_confused_by_her_spending_more_attention_to_the_people_than_the_shop_windows-.md'

I suspect the bug involves the autosave feature either getting **new** information **before** the rename happens, or **old** information **after** the rename happens.

**Reproduction steps:**

I think it is some sort of timing issue, so this is hard to be sure on. I was creating and renaming texts on the Outline screen, so all I can suggest is creating a text there and continuously changing the name until it crashes at some point.

I am not using zipped files / multiple files. (But the traceback probably gave that away already.)

Edit: I am not sure it is limited to the auto part of the autosave feature anymore, but I am currently very consistently crashing Manuskript trying to rename this particular text. Hmm. It happens whenever Manuskript freezes post-rename. It figures that I'd finally get a reproducible crash involving renaming after all the other ones were one-time-only affairs.

Edit #2: I think it might not be renaming the original file to begin with. I've got the relevant 2004-WIP folder open on explorer and even after I rename the file in the Outline, it doesn't change name there.

Edit #3: Nevermind, renames only happen when the project saves to begin with. That's a dead end.

**Comment by worstje** [comment] 2019-02-28 11:17
I think I figured it out. Screw me for anonimizing my story name while pasting the traceback. It turns out my renamed file runs afoul of the MAX_PATH limit that Windows is so fond of. I am not sure what the best way to handle this would be in Manuskript, although a sanity check to make sure a path is <255 for any files would be good. The actual title is after all stored in the file itself, and the leading number already guarantees uniqueness. But this would only work up to a certain degree; the path could still be long enough to where not even the numbers could fit in the available space.

As for me... I'll find a way to work around this issue for now. Having my story title worth 30 characters in the path twice is definitely not helping here.

**Comment by gedakc** [comment] 2019-02-28 16:29
Thank you @worstje for reporting this error and doing the investigative leg work to track down the root cause.

The problem sounds like [issue #313 - Main program does not load (FileNotFound error) - filename path too long > 260 chars](https://github.com/olivierkes/manuskript/issues/313).  There are some work arounds listed in issue #313 that you might try.  Otherwise shortening the overall filename path is the best option.

Shall I label this issue as a duplicate of issue #313?

**Comment by worstje** [comment] 2019-03-01 00:53
I think it is fine to label it as a duplicate. Go ahead. :-)

That said, as a programmer who knows some of the maintenance pains I do feel it is an odd design choice to still target Windows XP so strongly if that prevents a proper implementation for all paths loading/saving given how likely people are to bump into this limit when using Manuskript given the file structures it creates behind the scenes. Given how outdated Windows XP is at this point, should the 'extra effort' onus of using an different (older) version not be put on people who knowingly stick with what might as well be considered digital antiques? Manuskript hails from 2016, two full years after even the most super-extended support for Windows XP ended. Not to mention that Qt5 needs a special build flag for Windows XP, too. Given all the platforms Manuskript supports (Win, Mac, Linux), is it really desired to handicap the project with even more implementation hurdles?

FYI: I don't consider that 'disable path length limit' a viable solution because it affects all programs on my system by means of a registry key: the crappy design of old Windows APIs implies that breaking those APIs open for larger paths means possible weird failures that are even harder to track down.

Maybe once a new version for Manuskript comes out I'll look into running that from source, assuming that alone is enough to do away with the path length limitation for just Manuskript. (If I didn't spend far too many hours importing and adjusting over my existing texts the past weekend I might be a bit more adventurous, but some of the data loss stories I've seen in the issues as well as the rough edges I myself have come across mean I'm not willing to play it quite as risky as I typically would. The official release is the most tested / a known quantity, and thus the most trusted for me right now.)

**Comment by gedakc** [comment] 2019-03-01 16:10
Our hands are tied on this limitation because the root cause lies with the Windows operating system.

All I can do is provide suggestions.  The choice of how to address the Windows MAX_PATH 260 character limitation is up to you.  Personally I choose to use GNU/Linux.

Closing this issue as a duplicate of issue #313.

**Closed by gedakc** 2019-03-01 16:10 UTC
Labels: windows
