### ISSUE TITLE
Upgraded from 0.11 to 0.12, open from command line and dolphin broken

### ISSUE THREAD

**Issue by bame55** [olivierkes/manuskript#898] opened 2021-07-01 13:51 UTC
Environment: Ubuntu 20.04, Kernel 5.9.12, KDE 5.22.2, Qt 5.15.3

After upgrading from 0.11 to 0.12 (via download+dpkg) double-clicking icons in file manager (Dolphin) no longer opens msk projects.  I can only open files from within the GUI.

Attempting to run via bash with an existing msk file yields the following:
$ manuskript p1.msk
usage: manuskript [-h] [--console] [-v] [-L LOGFILE] [FILENAME]
manuskript: error: unrecognized arguments: p1.msk

Tried the git version with the same result.

**Comment by worstje** [comment] 2021-07-09 20:51
Regarding the argument error, I have reproduced this on Windows and identified the problem. **It is completely my fault, sorry!**

I am not sure how it slipped through, but it appears to have been an unfortunate combination of events. Obviously the filename was the first functionality I ever implemented, and I am sure it worked at the time.

Given that I forgot to adjust one line of the filename parsing code over from `sys.argv[1]` to the `argparse`d version, it seems obvious that calls that used to work continued to work by accident. But why args[1] instead of args[0], and why wasn't it a problem before?

When starting Manuskript, `sys.argv` resembles `['bin/manuskript', ...]`, which means `argparse` was consuming the script name as the `filename` parameter in the rewritten functionality... but it went completely unseen because it accidentally appeared to work still.

And when things stopped to work as work on the new logging facilities progressed, it was still likely to continue unseen because the functionality that autoloads the last project would have hidden it. (But even now it continues to go hidden, because all the argument parsing happens before the logging framework is set up... Now I want to add a line that at least logs we are loading an existing project file...)

Regardless, it is completely my fault for not catching this. Given the fact that I wrote and used this code for over a year before it got merged into manuskript without ever noticing the problem, it feels really damn stupid. Sorry!

**As I am currently seeing how many little fixes I can create during my spare time this weekend, I'll end up creating a PR with the fix for this included soon.**

**Comment by TheJackiMonster** [comment] 2021-07-09 23:12
@worstje  I will try to review the PR when it's ready as soon as possible to merge. So at least people can run the source from Github to fix this. I personally never noticed this because most of the time I just write on the same project which gets opened automatically when I start Manuskript. I guess, we could add tests for functionality like this to the CI later on. So it can't slip through.

**Closed** 2021-07-10 17:57 UTC
Labels: bug
