### ISSUE TITLE
Compile remains empty

### ISSUE THREAD

**Issue by fdf2** [olivierkes/manuskript#342] opened 2018-04-25 06:33 UTC
Hello,
I am using the 0.6, directly from the .deb ( I am running Debian stable)
I am writing with it since a couple of month, and was trying to use the export yesterday. But the files remain empty.
I have tried export to html, txt, epub (with pandoc)… same result.  Actually not exactly, at least with Epub, I have the book name and author name written on the second page (the book is otherwise empty and have then only two pages while it should be about 15 at least I guess).

I have checked that the already written part are checked for "compile"

I have then closed, created a new empty file and filed it with two random text, then save and launch the compile again, with the same result.
So I guess something is blocking the compile option. But I don't know how to look more about it and give you more details.
When launch from the terminal, I have this feedback
`wethica@Desktop:~$ manuskript 
Debug: Web rendering engine used: QWebView
Running manuskript version 0.6.0.
Found translation in settings: /usr/share/manuskript/i18n/
Note: No translator found or loaded for locale fr_FR.
Loading: /home/wethica/test.msk
Detected file format version: 1. Zip: True.
Project /home/wethica/test.msk loaded.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Error: content is empty. Nothing saved.
Project /home/wethica/test.msk saved.
`

We see the content is empty when trying to save the empty export

How can I help you more?

Have a good day.

**Comment by gedakc** [comment] 2018-04-25 16:37
Have you seen the tutorial [Using Manuskript to Write a Fiction Novel](http://gedakc.users.sourceforge.net/display-doc.php?name=manuskript-novel-writing)?  It contains tips on how to use manuskript.

If reviewing the article does not help you, then perhaps you could provide the exact steps you use to compile and export your document when this issue occurs.

**Comment by fdf2** [comment] 2018-04-26 01:16
Hello,

I check the tutorial before writing here. 
I am attaching the example file + epub export, hoping it can help.
[test.zip](https://github.com/olivierkes/manuskript/files/1949297/test.zip)


I have followed bellow: F6, select the format (EPUB for example), click Export, select the file name and save.
With Epub, I only have a 2 pages book with title and author on page two only.
With other (plain text, html…) I have nothing at all, and actually even not the request to save at the file is empty.


I am not clear on the Chapter summary section, but I guess you'll be able to see in the sample file.
Moreover, in the Editor mode, you have the tree on the left, the main writing part in the middle and different things on the right (including the summary). I have indeed the main writing part in the central panel, not on the right side.

**Comment by gedakc** [comment] 2018-04-26 16:07
Using the `test.msk` file you provided, I was able to successfully open the project and export it using pandoc.  Hence you have entered the data correctly using manuskript, and this suggests that perhaps there is an issue with your Debian stable GNU/Linux installation.

The following screen shot is from my kubuntu 16.04 computer with a pandoc export PDF preview of the test project:

![test-export-pdf](https://user-images.githubusercontent.com/10405019/39317017-d5a06f64-4937-11e8-8b9b-218147cb2364.png)

1. Can you provide the output from the following command to see the version of pandoc?

```
pandoc --version
```

2. Can you test using the built-in manuskript HTML export?

Following is a screen shot using the built-in manuskript HTML export preview.

![test-export-manuskript-html](https://user-images.githubusercontent.com/10405019/39317638-574052d6-4939-11e8-9bf8-2f994fe4b009.png)

**Comment by gedakc** [comment] 2018-04-28 01:29
So far I have been unable to reproduce the issue @fdf2 encountered.

The only error message from the original post that I have not seen myself is the following:

```
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Error: content is empty. Nothing saved.
```

From a search of the Internet it appears that the [Gtk-Message is not a concern](https://www.linuxquestions.org/questions/showthread.php?p=5775830#post5775830).

If anyone else has ideas on troubleshooting this issue then please feel free to add to this thread.

**Comment by fdf2** [comment] 2018-04-30 00:29
Hello,
I have tried on another computer, with Debian stable, Manuscript 0.6 and pandoc 1.17.02, and all is working fine.
I can preview, I can export. 

So obviously, there is something specific on my setting of the main computer.
I have tried to purge (dpkg -P) removed the local directory (.config) and reinstall.
Same situation, can't see anything in the preview or make an export.

**Comment by gedakc** [comment] 2018-05-02 17:06
Thanks @fdf2 for confirming that the issue appears to be specific to one computer.

Do you have any Python packages installed via pip or some other process?  If so it is possible that these might be adversely impacting Manuskript compile/export.

**Comment by fdf2** [comment] 2018-05-03 07:19
Hello,

I wasn't sure, so I checked. No pip… not installed. 

`wethica@Desktop:~$ python -m pip list
/usr/bin/python: No module named pip
`

As for modules, a big list from the Python help() command:
`help> modules

Please wait a moment while I gather a list of all available modules...

/usr/lib/python2.7/dist-packages/matplotlib/cbook.py:136: MatplotlibDeprecationWarning: The matplotlib.delaunay module was deprecated in version 1.4. Use matplotlib.tri.Triangulation instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)
BaseHTTPServer      aifc                gzip                quopri
Bastion             antigravity         hashlib             random
BeautifulSoup       anydbm              heapq               re
BeautifulSoupTests  apsw                hmac                readline
CDROM               apt                 hotshot             regex
CGIHTTPServer       apt_inst            html5lib            reportbug
Canvas              apt_pkg             htmlentitydefs      repoze
ConfigParser        aptsources          htmllib             repr
Cookie              argparse            httplib             requests
Crypto              array               httplib2            resource
DLFCN               ast                 idjcmonitor         rexec
Dialog              asynchat            idna                rfc822
DocXMLRPCServer     asyncore            ihooks              rlcompleter
FileDialog          atexit              imaplib             robotparser
FixTk               atk                 imghdr              routes
HTMLParser          audiodev            imp                 runpy
IN                  audioop             importlib           samba
Image               base64              imputil             sched
ImageChops          bdb                 inspect             select
ImageColor          binascii            io                  serial
ImageCrackCode      binhex              ipaddress           sets
ImageDraw           bisect              irc                 setuptools
ImageEnhance        bonobo              itertools           sgmllib
ImageFile           bs4                 json                sha
ImageFileIO         bsddb               keyword             shelve
ImageFilter         bz2                 ldb                 shlex
ImageFont           cPickle             lib2to3             shutil
ImageGL             cProfile            libexiv2python      signal
ImageGrab           cStringIO           libxml2             sip
ImageMath           cairo               libxml2mod          sipconfig
ImageOps            calendar            linecache           sipconfig_nd
ImagePalette        cgi                 linuxaudiodev       site
ImagePath           cgitb               locale              sitecustomize
ImageQt             chardet             logging             six
ImageSequence       cherrypy            lsb_release         smtpd
ImageStat           chunk               lxml                smtplib
ImageTk             cmath               macpath             sndhdr
ImageWin            cmd                 macurl2path         socket
MimeWriter          code                mailbox             spwd
ORBit               codecs              mailcap             sqlite3
OpenSSL             codeop              markdown            sre
PIL                 collada             markupbase          sre_compile
PSDraw              collections         marshal             sre_constants
PngImagePlugin      colorsys            math                sre_parse
PyQt4               commands            matplotlib          ssl
PyQt5               compileall          md5                 stat
PySide              compiler            mechanize           statvfs
Queue               contextlib          mhlib               string
ScrolledText        cookielib           mimetools           stringold
SimpleDialog        copy                mimetypes           stringprep
SimpleHTTPServer    copy_reg            mimify              strop
SimpleXMLRPCServer  crypt               mmap                struct
SocketServer        cryptography        modulefinder        subprocess
StringIO            cssselect           mpl_toolkits        subprocess32
TYPES               cssutils            multifile           sunau
Tix                 csv                 multiprocessing     sunaudio
Tkconstants         ctypes              mutagen             symbol
Tkdnd               curl                mutex               symtable
Tkinter             curses              mysql               sys
UserDict            cycler              ndiff               sysconfig
UserList            datetime            netifaces           syslog
UserString          dateutil            netrc               tabnanny
_LWPCookieJar       dbhash              new                 talloc
_MozillaCookieJar   dbm                 nis                 tarfile
__builtin__         dbus                nntplib             tdb
__future__          deb822              nose                telnetlib
_abcoll             debconf             ntpath              tempfile
_ast                debian              nturl2path          termios
_bisect             debian_bundle       numbers             test
_bsddb              debianbts           numpy               test_regex
_cffi_backend       decimal             opcode              textwrap
_codecs             difflib             operator            this
_codecs_cn          dircache            optparse            thread
_codecs_hk          dis                 os                  threaded
_codecs_iso2022     distutils           os2emxpath          threading
_codecs_jp          dns                 ossaudiodev         tidy
_codecs_kr          doctest             pango               time
_codecs_tw          drv_libxml2         pangocairo          timeit
_collections        dsextras            paramiko            tkColorChooser
_csv                dumbdbm             parser              tkCommonDialog
_ctypes             dummy_thread        pdb                 tkFileDialog
_ctypes_test        dummy_threading     pdfshuffler         tkFont
_curses             easy_install        pexpect             tkMessageBox
_curses_panel       ecdsa               pickle              tkSimpleDialog
_dbus_bindings      email               pickletools         toaiff
_dbus_glib_bindings encodings           pipes               token
_elementtree        encutils            pivy                tokenize
_functools          ensurepip           pkg_resources       tools
_hashlib            enum                pkgutil             trace
_heapq              errno               platform            traceback
_hotshot            espefuse            plistlib            ttk
_io                 espsecure           ply                 tty
_json               esptool             popen2              turtle
_ldb_text           exceptions          poplib              types
_locale             eyed3               poppler             unicodedata
_lsprof             fcntl               posix               unittest
_md5                feedparser          posixfile           urlhandler
_multibytecodec     filecmp             posixpath           urllib
_multiprocessing    fileinput           pprint              urllib2
_osx_support        fnmatch             profile             urllib3
_posixsubprocess    formatter           pstats              urlparse
_pyio               fpectl              pty                 user
_random             fpformat            ptyprocess          uu
_regex              fractions           pwd                 uuid
_regex_core         ftplib              pyPdf               warnings
_sha                functools           py_compile          wave
_sha256             functools32         pyaes               weakref
_sha512             future_builtins     pyasn1              webbrowser
_socket             gc                  pyclbr              webencodings
_sqlite3            gconf               pycurl              webob
_sre                genericpath         pydoc               whichdb
_ssl                getopt              pydoc_data          wnck
_strptime           getpass             pyexiv2             wsgiref
_struct             gettext             pyexpat             wx
_symtable           gi                  pygame              wxversion
_sysconfigdata      gio                 pygments            xdg
_sysconfigdata_nd   glib                pygtk               xdrlib
_tdb_text           glob                pygtkcompat         xml
_testcapi           gnome               pylab               xmllib
_threading_local    gnomecanvas         pynotify            xmlrpclib
_tkinter            gnomevfs            pyodbc              xxsubtype
_warnings           gobject             pyparsing           yaml
_weakref            grp                 pysideuic           zeitgeist
_weakrefset         gtk                 pysimplesoap        zipfile
_yaml               gtkunixprint        pysqlite2           zipimport
abc                 gtweak              pytz                zlib
`

**Comment by fdf2** [comment] 2018-08-17 03:31
After checking the logs, I can’t see
        anything significant, but I am not good at reading logs.
    Here they are for the time of the
        attempt.
    Attempt of export
          with Pandoc
      
    11:23:42 gnome-logs: GtkListBox with
        a model will ignore sort and filter functions
        11:23:32 tracker-extract: unable to create file
        '/run/user/1001/dconf/user': Permission non accordée.  dconf
        will not work properly.
        11:23:18 systemd: Started Hostname Service.
        11:23:18 dbus-daemon: [system] Successfully activated service
        'org.freedesktop.hostname1’
        11:23:18 gnome-shell: Window manager warning: Buggy client sent
        a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x3e006f1
        (Chose outp)
        11:23:18 systemd: Starting Hostname Service...
        11:23:18 dbus-daemon: [system] Activating via systemd: service
        name='org.freedesktop.hostname1'
        unit='dbus-org.freedesktop.hostname1.service'
        11:23:18 python3: GtkDialog mapped without a transient parent.
        This is discouraged.
      
    
      
    Attempt of export directly from
          Manuskript converter.
    11:27:40 gnome-logs: GtkListBox with
        a model will ignore sort and filter functions
        11:27:39 gnome-logs: GtkListBox with a model will ignore sort
        and filter functions
        11:27:23 systemd: Started Hostname Service.
        11:27:23 dbus-daemon: [system] Successfully activated service
        'org.freedesktop.hostname1’
        11:27:23 gnome-shell: Window manager warning: Buggy client sent
        a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x3e0125b
        (Chose outp)
        11:27:23 systemd: Starting Hostname Service...
        11:27:23 dbus-daemon: [system] Activating via systemd: service
        name='org.freedesktop.hostname1'
        unit='dbus-org.freedesktop.hostname1.service'
        11:27:23 python3: GtkDialog mapped without a transient parent.
        This is discouraged.
      
    
      
    
      
    I guess it is just the window opening for the saving choice.
    
    
    I hope it might help, but doubt it.
    Pierig
    
    
    
    
    On 17/08/2018 05:33, Curtis Gedak
      wrote:
    
    
      
      @fdf2
        did you ever get this to work correctly on the one problem
        computer?
      If it is not fixed, would you please try Manuskript 0.7.0
        released on Aug 15, 2018?
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or mute the thread.
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/olivierkes/manuskript","title":"olivierkes/manuskript","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/olivierkes/manuskript"}},"updates":{"snippets":[{"icon":"PERSON","message":"@gedakc in #342: @fdf2 did you ever get this to work correctly on the one problem computer?\r\n\r\nIf it is not fixed, would you please try Manuskript 0.7.0 released on Aug 15, 2018?"}],"action":{"name":"View Issue","url":"https://github.com/olivierkes/manuskript/issues/342#issuecomment-413691586"}}}
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/olivierkes/manuskript/issues/342#issuecomment-413691586",
"url": "https://github.com/olivierkes/manuskript/issues/342#issuecomment-413691586",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [olivierkes/manuskript] Compile remains empty (#342)",
"sections": [
{
"text": "",
"activityTitle": "**Curtis Gedak**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@gedakc",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"olivierkes/manuskript\",\n\"issueId\": 342,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"olivierkes/manuskript\",\n\"issueId\": 342\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/olivierkes/manuskript/issues/342#issuecomment-413691586"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 327902684\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by gedakc** [comment] 2018-08-17 20:50
Which Operating System are you using?

Is your compile/export file still empty?

On Fedora 25 when I run manuskript and choose **F6** compile to export a project to Pandoc **HTML**, the export succeeds and is not-empty.  In the terminal window I see the following log:

```
$ manuskript
Debug: Web rendering engine used: QWebView
Running manuskript version 0.7.0.
Note: No translator found or loaded for locale en_CA.
Loading: /home/fedora/deleteme-manuskript.msk
Detected file format version: 1. Zip: False.
Project /home/fedora/deleteme-manuskript.msk loaded.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Project deleteme-manuskript.msk saved.
$
```

Note that I do not see the `Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.` message on other operating systems such as Kubuntu 16.04.

**Comment by gedakc** [comment] 2018-11-21 18:02
Closing this issue because no further information has been provided and I am also unable to reproduce the issue.  Also marking this issue as **invalid** so that it does not get included in the automatically generated CHANGELOG.md file.

**Closed by gedakc** 2018-11-21 18:02 UTC
