### ISSUE TITLE
Caracters count

### ISSUE THREAD

**Issue by bepolymathe** [olivierkes/manuskript#552] opened 2019-04-15 15:02 UTC
In the academic world, many projects are quantified with objectives in terms of number of characters and not number of words. Would it be possible to integrate the possibility of choosing between these two options?
Thank you in advance for your interest in this request. This software is necessary!

**Comment by gedakc** [comment] 2019-05-01 15:51
Closing this as a duplicate of Issue #334.

**Closed by gedakc** 2019-05-01 15:51 UTC
