### ISSUE TITLE
Editor crashing with non-fusion themes

### ISSUE THREAD

**Issue by kaptem** [olivierkes/manuskript#800] opened 2020-08-28 01:08 UTC
When selecting the Adwaita, Adwaita-dark, or Breeze theme, (All on defaults) the editor crashes when moving the cursor from the main editor towards the top of the screen. Has been occurring to me every time I try to try use this software and has happened on Ubuntu and Fedora over the course of multiple separate installations with Gnome or KDE.

**Comment by kaptem** [comment] 2020-08-28 01:49
> /usr/share/manuskript/manuskript/main.py:104: SyntaxWarning: "is not" with a literal. Did you mean "!="?
>   if platform.system() is not 'Windows':
> Debug: Web rendering engine used: QWebView
> Running manuskript version 0.11.0.
> Preferred translation: ['en-US'] (based on available ui languages)
> Using the builtin translation.
> /usr/share/manuskript/manuskript/importer/opmlImporter.py:124: SyntaxWarning: "is" with a literal. Did you mean "=="?
>   return len(s) is 0
> /usr/share/manuskript/manuskript/exporter/pandoc/abstractPlainText.py:78: SyntaxWarning: "is" with a literal. Did you mean "=="?
>   if self.formats is "":
> Icon theme "NumixMsk" not found.
> Loading: /home/kaptem/Documents/testfile.msk
> Detected file format version: 1. Zip: True.
> Project /home/kaptem/Documents/testfile.msk loaded.
> qt.qpa.xcb: QXcbConnection: XCB error: 5 (BadAtom), sequence: 696, resource id: 0, major code: 19 (DeleteProperty), minor code: 0
> Fatal Python error: Segmentation fault
> 
> Current thread 0x00007fa8ad068740 (most recent call first):
>   File "/usr/share/manuskript/manuskript/main.py", line 221 in launch
>   File "/usr/share/manuskript/manuskript/main.py", line 234 in run
>   File "/usr/bin/manuskript", line 30 in <module>
> Segmentation fault (core dumped)

This is the error report I am given when it is launched from the terminal.

**Comment by manoelpqueiroz** [comment] 2020-10-04 20:56
Manuskript is also crashing upon the same action in my installation, with a slightly different output:

```
/usr/share/manuskript/manuskript/main.py:104: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if platform.system() is not 'Windows':
Debug: Web rendering engine used: QWebView

** (process:7781): WARNING **: 17:51:47.126: Error loading plugin: libnuspell.so.3: cannot open shared object file: No such file or directory

Running manuskript version 0.11.0.
Preferred translation: ['en-GB'] (based on available ui languages)
Loaded translation: manuskript_en_GB.qm
/usr/share/manuskript/manuskript/importer/opmlImporter.py:124: SyntaxWarning: "is" with a literal. Did you mean "=="?
  return len(s) is 0
/usr/share/manuskript/manuskript/exporter/pandoc/abstractPlainText.py:78: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if self.formats is "":
Icon theme "NumixMsk" not found.
Loading: /home/myuser/Documents/scripts/test1.msk
Detected file format version: 1. Zip: True.
Project /home/myuser/Documents/scripts/test1.msk loaded.
Fatal Python error: Segmentation fault

Current thread 0x00007f044a19f740 (most recent call first):
  File "/usr/share/manuskript/manuskript/main.py", line 221 in launch
  File "/usr/share/manuskript/manuskript/main.py", line 234 in run
  File "/usr/bin/manuskript", line 30 in <module>
Segmentation fault (core dumped)
```

Will this be addressed? The last commit for this project was back in April.

**Comment by Spounka** [comment] 2020-11-21 12:48
I get same issue trying a custom fullscreen image
Manuscript just crashes after closing the menu

Running manuskript version 0.11.0.
Preferred translation: ['en-GB'] (based on available ui languages)
Loaded translation: manuskript_en_GB.qm
/usr/share/manuskript/manuskript/exporter/pandoc/abstractPlainText.py:78: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if self.formats is "":
Python error: Segmentation fault

Current thread 0x00007f1e42133740 (most recent call first):
  File "/usr/share/manuskript/manuskript/main.py", line 221 in launch
  File "/usr/share/manuskript/manuskript/main.py", line 234 in run
  File "/usr/bin/manuskript", line 30 in <module>
[1]    87862 segmentation fault (core dumped)  manuskript

**Comment by TheJackiMonster** [comment] 2021-02-21 23:41
I have fixed an issue (#817) related to Qt styles today and fixed those python syntax warnings. Maybe you can pull the current develop branch and test if the issue still occurs.

I can use manuskript just fine on Arch with GNOME using Adwaita or Adwaita-dark theme.

**Comment by TheJackiMonster** [comment] 2021-02-22 16:13
I will test it longer but I think this issue can potentially be solved by installing "qgnomeplatform". On Archlinux this is an optional dependency of adwaita-qt but I assume it is required for some widgets.

**Comment by TheJackiMonster** [comment] 2021-02-22 16:15
This is a duplicate of https://github.com/olivierkes/manuskript/issues/676.

**Closed by TheJackiMonster** 2021-02-22 16:15 UTC
Labels: bug, duplicate
