### ISSUE TITLE
Accented characters not working

### ISSUE THREAD

**Issue by zorrillodepeluche** [olivierkes/manuskript#141] opened 2017-08-28 22:47 UTC
I’m working with the 0.4 version in and Linux Mint 18.2 Sonya (cinnamon) and entering accented characters á, è, etc. is not working (pasting them or entering with an external editor is no problem). The problem is only when using key combinations (e. g. `'` then `a` outputs “a” instead of “á”).

**Edit**: The keyboard input is working fine in 0.3.0 running from source (in the pre-compiled 0.3.0 is not working either). I can't, however, get 0.4.0 to run from source; I get an `ImportError: No module named 'PyQt5.QtWebKitWidgets'` error (and can't figure out how to install it).

**Comment by gedakc** [comment] 2017-08-29 16:04
The package name for the required QtWebKit is `python3-pyqt5.qtwebkit`.
See [Run Manuskript from Source Code on Linux](https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Linux).

For some reason the accent characters do not seem to work from international keyboards when using the Linux PyInstaller package.  The work around is to run from source code.

This issue is a duplicate of issue #58 for the 0.3.0 PyInstaller package, and issue #105 for the 0.4.0 PyInstaller package, in addition to this report.

**Comment by zorrillodepeluche** [comment] 2017-08-29 16:44
> The package name for the required QtWebKit is python3-pyqt5.qtwebkit.
> See Run Manuskript from Source Code on Linux.

Thanks, @gedakc, and sorry for the duplicate. I have already followed the steps in the [link you provided](https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Linux), but get same error about `PyQt5.QtWebKitWidgets`; if I try to reinstall `python3-pyqt5.qtwebkit` I get
`python3-pyqt5.qtwebkit is already the newest version (5.5.1+dfsg-3ubuntu4)` so, I don’t know what should I do. As I mentioned before, 0.3.0 runs fine from source for me.

**Comment by gedakc** [comment] 2017-08-29 17:48
If you have the dependencies installed, then let's try something different.

Can you try cloning the git repository and running from both the **master** branch, which represents v0.4.0, and also the **develop** branch?

**Comment by zorrillodepeluche** [comment] 2017-08-30 19:03
I try what you suggested, but the result is the same. Here is what I get exactly

```
Your branch is up-to-date with 'origin/develop'.
username@computer ~/bin/manuskript-git/manuskript $ cd bin
username@computer ~/bin/manuskript-git/manuskript/bin $ python3 manuskript
QApplication: invalid style override passed, ignoring it.
Running manuskript version 0.4.0.
Found translation in settings: /home/username/bin/manuskript-git/manuskript/i18n/
Note: No translator found or loaded for locale en_US.
Traceback (most recent call last):
  File "manuskript", line 13, in <module>
    main.run()
  File "/home/username/bin/manuskript-git/manuskript/bin/../manuskript/main.py", line 64, in run
    launch()
  File "/home/username/bin/manuskript-git/manuskript/bin/../manuskript/main.py", line 68, in launch
    from .mainWindow import MainWindow
  File "/home/username/bin/manuskript-git/manuskript/bin/../manuskript/mainWindow.py", line 22, in <module>
    from manuskript.ui.exporters.exporter import exporterDialog
  File "/home/username/bin/manuskript-git/manuskript/bin/../manuskript/ui/exporters/exporter.py", line 10, in <module>
    from manuskript import exporter
  File "/home/username/bin/manuskript-git/manuskript/bin/../manuskript/exporter/__init__.py", line 4, in <module>
    from manuskript.exporter.manuskript import manuskriptExporter
  File "/home/username/bin/manuskript-git/manuskript/bin/../manuskript/exporter/manuskript/__init__.py", line 6, in <module>
    from manuskript.exporter.manuskript.HTML import HTML
  File "/home/username/bin/manuskript-git/manuskript/bin/../manuskript/exporter/manuskript/HTML.py", line 4, in <module>
    from PyQt5.QtWebKitWidgets import QWebView
ImportError: No module named 'PyQt5.QtWebKitWidgets'
```

**Comment by gedakc** [comment] 2017-08-30 20:40
Hmm... I wonder if there is a newer version of Python3 that is in the PATH before the Mint packaged version.

On my Kubuntu 16.04 distro I see the following results:

```
$ which python3
/usr/bin/python3
$ python3 --version
Python 3.5.2
```

What results do you see on your system?

**Comment by zorrillodepeluche** [comment] 2017-08-31 04:31
Exactly the same…

**Comment by gedakc** [comment] 2017-08-31 17:00
I wonder if some other Python module install method is getting in the way.

Do you have any Python3 modules that are installed through PIP?

I think the command for PIP in Python3 is `pip3`.

**Comment by zorrillodepeluche** [comment] 2017-09-01 04:29
Unfortunately, this also didn't help. I was considering moving to kubuntu for a while now, and Manuskript is an important program for me, so I did it (dual-boot, for now) and Manuskript run fine on it. Thanks for all your help! I’m sorry for (if) anyone who's having this same trouble though.

**Comment by gedakc** [comment] 2017-09-01 15:45
Thank you @zorrillodepeluche for reporting back with how you worked around the problem.

Manuskript _should_ work with Linux Mint 18.2 Sonya (cinnamon).  I am reasonably sure that the issue is something to do with the python environment.  Unfortunately I am new to Python myself and don't know what else to suggest.

**Comment by gedakc** [comment] 2017-11-19 18:03
For users of Debian based GNU/Linux distributions, such as Ubuntu and Linux Mint, please try the `manuskript-0.5.0-1.deb` package to see if accents now work for you.

The package along with the instructions for installation can be found at:   
[SF - manuskript-0.5.0](https://sourceforge.net/projects/manuskript/files/manuskript/manuskript-0.5.0/)

**Comment by gedakc** [comment] 2017-11-20 22:54
For users of Fedora based GNU/Linux distributions please try the `manuskript-0.5.0-1.noarch.rpm` package to see if accents now work for you.

The package along with the instructions for installation can be found at:   
[SF - manuskript-0.5.0](https://sourceforge.net/projects/manuskript/files/manuskript/manuskript-0.5.0/)

**Comment by zorrillodepeluche** [comment] 2017-11-21 18:09
Can confirm accentuated characters working all right in kubuntu 16.04 from the .deb installer.

**Comment by gedakc** [comment] 2017-11-21 18:23
Thank you @zorrillodepeluche for reporting your test results.  :-)

**Closed** 2017-11-21 18:24 UTC
Labels: bug, packaging

**Comment by thoronaug** [comment] 2017-11-24 08:46
I confirm accents working from the .deb installer 0.5.0-1 too. I'm using Linux Mint 18.2 Sonya.
I've also tried running from precompiled (accents not working) and from source code (accents working).

Have you ever thought about releasing an appImage package or something similar? Maybe this solve the problems between platforms.

Greetings

**Comment by olivierkes** [comment] 2017-11-24 12:31
Thanks @thoronaug for confirming! 

About appImage, do you have any knowledge / experience with it? :)

**Comment by thoronaug** [comment] 2017-11-30 22:32
Sorry, but my only experience is using it :(. But if I learn something about it, I will let you know and try to help!. Thanks!
