### ISSUE TITLE
Impossible to start a project on Lubuntu 16.04

### ISSUE THREAD

**Issue by ArnaudBlondel** [olivierkes/manuskript#85] opened 2017-02-22 13:50 UTC
Hi, 

I have difficulties launching the software. When trying to create a new Research paper, I get this error message : 

> Traceback (most recent call last):
  File "manuskript/ui/welcome.py", line 159, in createFile
  File "manuskript/ui/welcome.py", line 344, in loadDefaultDatas
  File "manuskript/ui/welcome.py", line 344, in <listcomp>
IndexError: list index out of range

I don't know whether it is an issue or whether I missed something during the unpacking/installation.

**Comment by olivierkes** [comment] 2017-03-10 12:59
This is a duplicate of #44.
Try double-clicking on a template before saving (the UI must change).

**Closed by olivierkes** 2017-03-10 12:59 UTC
