### ISSUE TITLE
Crash (program closes) when changing revision number per 10 minutes in manuskript-0.7.0-win32

### ISSUE THREAD

**Issue by AnthonyBronislavaGonzales** [olivierkes/manuskript#393] opened 2018-09-30 06:08 UTC
Screenshot attached to show the current setting. I was clicking the down button to change the revisions per 10 minutes to zero.

![screenshot_28](https://user-images.githubusercontent.com/43716911/46253958-a851d680-c455-11e8-8c8d-ae563f8b88d1.png)

By the way, where are these revisions stored?

**Comment by gedakc** [comment] 2018-10-02 00:04
The revisions are stored in the Manuskript project file(s).

Closing this report as a duplicate of issue #381 - Lowering number of saved revisions below 1 crashes program.

**Closed by gedakc** 2018-10-02 00:04 UTC
