### ISSUE TITLE
Crashes in outliner

### ISSUE THREAD

**Issue by Lledor** [olivierkes/manuskript#582] opened 2019-05-15 16:15 UTC
Running on windows 7. I am getting multiple crashes when working in the outline and editing windows, it usually happens when expanding folders. I have also lost work in outline window when using labelling function.

**Comment by worstje** [comment] 2019-05-16 13:51
Pull request #571 ought to fix most of the crashes you experience in the outline.

The bit about 'losing work when using the labeling function' is new to me though. Do you have any specific steps that can reproduce the issue? Alternatively, a traceback that is produced when it crashes would be useful as well. (You may have to run from the command line and/or from source in order to see that, though.)

**Comment by gedakc** [comment] 2019-05-19 15:58
@Lledor can you test with the latest **develop** branch?

See [Run Manuskript from Source Code on Windows](https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Windows) and choose the **develop** branch.

**Comment by Lledor** [comment] 2019-05-20 14:14
I have solved the problem, but I am unsure how this happens? Occasionally if I set up a new project, it saves to a single file, with all the information in the .msk file (this version is the one that crashed on me). I now use a version that is similar to the sample projects folder, msk file with a single digit '1' in it and the folder that holds all the saved information (this one is stable). Is there a difference in the type of file that the program creates (for example empty fiction file compared to novel file?). Also I having problems opening the good project file on other computers (Same version of Windows 7)?

Whilst I'm here is there a function to expand and collapse the tree in outline mode?

**Comment by gedakc** [comment] 2019-05-20 16:30
> Is there a difference in the type of file that the program creates (for example empty fiction file compared to novel file?)

The type of file should be the same.  The difference would be the pre-created chapters and scenes.

The default when creating a Manuskript project is that the project is saved as a single .msk file which is a zip file of all the contents.  If you edit the settings to disable _save to one single file_ then the file contents are unzipped into a directory with a corresponding .msk file which contains the number "1".

> Also I having problems opening the good project file on other computers (Same version of Windows 7)?

Be sure to copy all files and folders (both project directory and project.msk) if you wish to open on another computer.

> Whilst I'm here is there a function to expand and collapse the tree in outline mode?

Not that I'm aware of, but that doesn't mean it doesn't exist.

Now onto the original reason for this report.

Can you test with the latest **develop** branch?

Otherwise without a specific set of steps to reproduce the problem you experienced then we do not know if the issue is already fixed.

**Comment by gedakc** [comment] 2019-07-31 16:50
Closing this request as PR #571 and #609 have been merged with the **develop** branch.

**Closed by gedakc** 2019-07-31 16:50 UTC
