### ISSUE TITLE
well, now it don't even open...

### ISSUE THREAD

**Issue by DorenMad** [olivierkes/manuskript#870] opened 2021-04-30 17:38 UTC
2021-04-30 19:29:58,162 - manuskript.logging - INFO - Logging to file: C:/Users/sylvesson/AppData/Local/manuskript/manuskript\logs\2021-04-30_19-29-58_manuskript#16932.log
2021-04-30 19:29:58,167 - manuskript - INFO - Operating System: Windows-10-10.0.19041-SP0
2021-04-30 19:29:58,167 - manuskript - INFO - Hardware: AMD64 / AMD64 Family 21 Model 48 Stepping 1, AuthenticAMD
2021-04-30 19:29:58,167 - manuskript - INFO - Running in a frozen (packaged) state.
2021-04-30 19:29:58,167 - manuskript - DEBUG - * sys.frozen = True
2021-04-30 19:29:58,167 - manuskript - DEBUG - * sys._MEIPASS = D:\manuskript-0.12.0-win32\manuskript
2021-04-30 19:29:58,257 - manuskript - DEBUG - * sys.executable = 'D:\\manuskript-0.12.0-win32\\manuskript\\manuskript.exe'
2021-04-30 19:29:58,258 - manuskript - DEBUG - * sys.argv = ['D:\\manuskript-0.12.0-win32\\manuskript\\manuskript.exe']
2021-04-30 19:29:58,258 - manuskript - DEBUG - * sys.path = ['D:\\manuskript-0.12.0-win32\\manuskript\\base_library.zip',
 'D:\\manuskript-0.12.0-win32\\manuskript\\..',
 'D:\\manuskript-0.12.0-win32\\manuskript\\lib-dynload',
 'D:\\manuskript-0.12.0-win32\\manuskript']
2021-04-30 19:29:58,259 - manuskript - DEBUG - * sys.prefix = 'D:\\manuskript-0.12.0-win32\\manuskript'
2021-04-30 19:29:58,260 - manuskript - INFO - Manuskript 0.12.0 (Python 3.8.9)
2021-04-30 19:29:58,261 - manuskript - INFO - * PyQt 5.15.4 (compiled against Qt 5.15.2)
2021-04-30 19:29:58,261 - manuskript - INFO -   * Qt 5.15.2 (runtime)
2021-04-30 19:29:58,277 - manuskript - INFO - * lxml.etree 4.6.3.0
2021-04-30 19:29:58,278 - manuskript - INFO -   * libxml   2.9.5 (compiled: 2.9.5)
2021-04-30 19:29:58,278 - manuskript - INFO -   * libxslt  1.1.30 (compiled: 1.1.30)
2021-04-30 19:29:58,278 - manuskript - INFO - * pyEnchant 3.2.0 (libenchant: 2.2.7)
2021-04-30 19:29:58,278 - manuskript - INFO - * pySpellChecker 0.6.2
2021-04-30 19:29:58,279 - manuskript - INFO - * Symspellpy 6.7.0
2021-04-30 19:29:58,334 - manuskript - INFO - * Markdown 3.3.4
2021-04-30 19:29:58,336 - manuskript - INFO - Web rendering engine: QTextEdit
2021-04-30 19:29:58,377 - manuskript.main - INFO - Preferred translation: manuskript_en_GB.qm (based on user setting)
2021-04-30 19:29:58,377 - manuskript.main - INFO - Loaded translation: manuskript_en_GB.qm
2021-04-30 19:30:04,118 - manuskript.logging - CRITICAL - An unhandled exception has occurred!
Traceback (most recent call last):
  File "language_tool_python\language_tag.py", line 30, in _normalize
KeyError: 'polish_poland'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "language_tool_python\language_tag.py", line 33, in _normalize
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manuskript", line 13, in <module>
  File "manuskript\main.py", line 291, in run
  File "manuskript\main.py", line 172, in prepare
  File "manuskript\mainWindow.py", line 76, in __init__
  File "manuskript\mainWindow.py", line 1403, in setupMoreUi
  File "manuskript\mainWindow.py", line 1434, in updateMenuDict
  File "manuskript\functions\spellchecker.py", line 81, in availableDictionaries
  File "manuskript\functions\spellchecker.py", line 584, in availableDictionaries
  File "manuskript\functions\spellchecker.py", line 555, in getTool
  File "language_tool_python\server.py", line 54, in __init__
  File "language_tool_python\language_tag.py", line 13, in __init__
  File "language_tool_python\language_tag.py", line 35, in _normalize
ValueError: unsupported language: 'Polish_Poland'

That's error log

**Comment by TheJackiMonster** [comment] 2021-04-30 17:43
I see. That seems to be an exception directly from language_tool_python which didn't appear before during testing because it seems to related to the used language. I will look into this.

**Comment by DorenMad** [comment] 2021-04-30 17:58
Then how can i change language???

**Comment by TheJackiMonster** [comment] 2021-04-30 18:09
You can probably still use the older version 0.11.0, then disable spell checking and try 0.12.0 again. I certainly can't reproduce the bug despite setting the language used for spell checking to Polish and actively using LanguageTool.

**Comment by Erkhyan** [comment] 2021-04-30 18:25
I have the same issue, but the language in my case is “English_Europe”.

**Comment by TheJackiMonster** [comment] 2021-04-30 18:40
Okay, I think I know what's wrong. LanguageTool tries to use the system language as default and doesn't find the exact string in its database which throws an exception. It's just weird that the strings which get tested are in a completely different format than expected. I will add a whole exception handling around this which will prevent LanguageTool from getting used if this error occures.

**Comment by TheJackiMonster** [comment] 2021-04-30 18:49
This should be fixed now. I'll rebuild and replace the windows package now because it's more difficult to just separate language_tool_python from it than on the Linux builds.

**Closed by TheJackiMonster** 2021-04-30 18:49 UTC
Labels: bug
