### ISSUE TITLE
Version 0.15.0-1 IndexError: list index out of range - crash in Debian Bookworm

### ISSUE THREAD

**Issue by charliemartinez** [olivierkes/manuskript#1238] opened 2023-10-15 16:59 UTC
When switching between the options in the left menu (trilogy, story, etc.), the program closes.
This only happens with the **.deb package**, not with Flatpak; Flatpak works fine.

**Package:** manuskript
**Version:** 0.15.0-1
**SO:** Debian 12 (Bookworm). 

In the terminal, you can observe the following:

`$ manuskript
CRITICAL> An unhandled exception has occurred!
Traceback (most recent call last):
  File "/usr/share/manuskript/manuskript/ui/welcome.py", line 260, in changeTemplate
    self.updateTemplate()
  File "/usr/share/manuskript/manuskript/ui/welcome.py", line 329, in updateTemplate
    self.updateWordCount()
  File "/usr/share/manuskript/manuskript/ui/welcome.py", line 370, in updateWordCount
    self.template[1][templateIndex][1])
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
IndexError: list index out of range`

**Comment by knorton181** [comment] 2023-12-06 21:33
still new here but BUMP! same issue. good to know flatpak works well

**Comment by TheJackiMonster** [comment] 2023-12-07 14:47
I close this since it's a duplicate of #1163 which has been addressed.

**Closed by TheJackiMonster** 2023-12-07 14:47 UTC
Labels: bug
