### ISSUE TITLE
Crash at project creation on mac

### ISSUE THREAD

**Issue by jlanca** [olivierkes/manuskript#48] opened 2016-09-25 11:45 UTC
Using mac OS X 10.10.3 and manuskript 0.3.0.

When creating a new project, the application closes after clicking on the "Create" button, and I get the following backtrace:

> Traceback (most recent call last):
>   File "manuskript/ui/welcome.py", line 159, in createFile
>   File "manuskript/ui/welcome.py", line 344, in loadDefaultDatas
>   File "manuskript/ui/welcome.py", line 344, in <listcomp>
> IndexError: list index out of range
> Fatal Python error: Aborted
> 
> Current thread 0x00007fff748dc300 (most recent call first):
>   File "manuskript/main.py", line 72 in launch
>   File "manuskript/main.py", line 63 in run
>   File "<string>", line 13 in <module>
> Abort trap: 6

Do you have any idea what's going on?
Is there a way to workaround the issue?

**Comment by vivganes** [comment] 2016-09-26 04:14
I too got the same error

> Traceback (most recent call last):
  File "manuskript/ui/welcome.py", line 159, in createFile
  File "manuskript/ui/welcome.py", line 344, in loadDefaultDatas
  File "manuskript/ui/welcome.py", line 344, in <listcomp>
IndexError: list index out of range
Fatal Python error: Aborted
Current thread 0x00007fff75533000 (most recent call first):
  File "manuskript/main.py", line 72 in launch
  File "manuskript/main.py", line 63 in run
  File "<string>", line 13 in <module>
Abort trap: 6
logout

**Comment by olivierkes** [comment] 2016-10-01 09:19
Duplicate of #44.

**Closed by olivierkes** 2016-10-01 09:19 UTC
