### ISSUE TITLE
CTD Crash To Desktop after "inserting link"

### ISSUE THREAD

**Issue by Moris1991** [olivierkes/manuskript#1071] opened 2022-09-01 23:50 UTC
1. Create new empty book.
2. Go to world
3. Use heart option to import fantsy world
4. Click on first option (Climate in my case)
5. In description right click and use first option "inserting link"
6. Insert anything and if result is green, clicking or hover over it will make CTD
Any1 else or it's just me?

Video cap of the problem
https://files.fm/u/83kvmwzkv#/view/ry9y5afzt
*  Video Will be deleted from website at 2022-11-05 *

**Comment by AKANexus** [comment] 2022-09-04 03:55
I can confirm this happens, but only when running Manuskript in polish. Doing the same using english interface doesn't result in a CTD. Haven't tested for other languages, though.

Here's a file ready to "crash" for easier testing - https://github.com/AKANexus/AKANexus/blob/master/1071.msk

**Comment by TheJackiMonster** [comment] 2022-09-04 11:28
I'll try to look into it. Thank you for the detailed information so far. ^^

**Comment by TheJackiMonster** [comment] 2023-02-09 22:01
The issue seems to be fixed. It has been solved by catching any errors caused by an incomplete translation which has caused the CTD here (as mentioned by @AKANexus when using some languages besides the default English).

So I will close this one.

**Closed by TheJackiMonster** 2023-02-09 22:01 UTC
Labels: bug
