### ISSUE TITLE
[Dev] Full Screen - Indent 1st line has no effect.

### ISSUE THREAD

**Issue by andersstroem** [olivierkes/manuskript#162] opened 2017-10-17 19:25 UTC
I'm not sure if this affects the Master branch as well, but in Dev the "Indent 1st line" option for full screen has no effect, and the box is unticked again after clicking Apply and editing the theme once more.

It does seem to have an effect on the non full screen editor however, unless it's already the default there.

**Comment by gedakc** [comment] 2017-10-17 19:27
@andersstroem, is the same problem as I recently provided a screen shot for in [Issue 133 - Indent not saved in custom full screen theme](https://github.com/olivierkes/manuskript/issues/133).

**Comment by andersstroem** [comment] 2017-10-17 19:31
@gedakc Yes, please feel free to close this one out as a duplicate.

**Comment by gedakc** [comment] 2017-10-17 19:33
Thanks @andersstroem for the prompt response.  'Closing this issue as a duplicate of issue #133.

**Closed by gedakc** 2017-10-17 19:33 UTC
