### ISSUE TITLE
Launch flag to hide command prompt in Windows?

### ISSUE THREAD

**Issue by sprite-1** [olivierkes/manuskript#457] opened 2019-01-11 12:37 UTC
When I open this in Windows 10, it shows a command prompt. Is there a way to hide that? I don't necessarily need to debug the app all the time. 😅

**Comment by gedakc** [comment] 2019-01-11 16:40
The command prompt in Windows is related to our current packaging decision to make it easier for users to report issues and include the console debug output.

Marking this request as a duplicate of issue #327.

**Closed by gedakc** 2019-01-11 16:40 UTC

**Comment by sprite-1** [comment] 2019-01-11 16:42
Damn that sucks. I guess I have to figure out some hack to hide it at runtime in the meantime

**Comment by sprite-1** [comment] 2019-01-11 16:44
If anything I would've suggested just outputting a log file instead of the command prompt window for a much cleaner way of doing it.

**Comment by gedakc** [comment] 2019-01-11 16:45
There is a workaround listed in issue #327 if you happen to be using Windows 10.

Alternatively you can choose to [Run Manuskript from Source Code on Windows](https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Windows) and create your own invocation script / shortcut.

**Comment by sprite-1** [comment] 2019-01-11 16:54
Yeah I saw that workaround but I feel like it's too cumbersome to do it whenever I open the app so I think a quick and dirty AHK script could deal with it in the meantime.

**Comment by gedakc** [comment] 2019-01-11 16:57
If you discover a workaround then please feel free to add it to issue #327.  Further if you are familiar with Windows and packaging then perhaps you might try creating a better install package for Manuskript that does not use PyInstaller.

**Comment by sprite-1** [comment] 2019-01-12 05:36
I'm not very familiar with Python but I finally got around to making a simple launcher this morning and I [posted it there](https://github.com/olivierkes/manuskript/issues/327#issuecomment-453721533). So far so good.

**Comment by gedakc** [comment] 2019-01-12 16:45
Thanks @sprite-1 for posting your work-around.
