### ISSUE TITLE
[Feature request] Text to speech

### ISSUE THREAD

**Issue by Eusorph** [olivierkes/manuskript#633] opened 2019-09-09 20:17 UTC
As a previous user of Scrivener, one feature I always found very helpful during editing was Text to speech, and specifically the "Play from cursor point". I'd love to see Manuskript implement this. The settings inside the program must of course allow for the choice of the different voices one has already installed.

**Comment by gedakc** [comment] 2019-09-09 20:24
Closing this issue as a duplicate of issue #575.

**Closed by gedakc** 2019-09-09 20:24 UTC
