### ISSUE TITLE
not working on Mac

### ISSUE THREAD

**Issue by rem90** [olivierkes/manuskript#35] opened 2016-05-04 10:17 UTC
Hello, the app is not starting on OS X Yosemite 10.10.5. Here is the log:

Last login: Wed May  4 11:03:14 on console
Remus:~ Remus$ /Users/Remus/Downloads/manuskript/manuskript ; exit;
Warning: failed to load translator for locale en_US...
Traceback (most recent call last):
  File "<string>", line 13, in <module>
  File "manuskript/main.py", line 63, in run
  File "manuskript/main.py", line 69, in launch
  File "manuskript/mainWindow.py", line 51, in **init**
  File "manuskript/ui/mainWindow.py", line 167, in setupUi
  File "manuskript/ui/views/textEditView.py", line 79, in **init**
  File "enchant/**init**.py", line 548, in **init**
enchant.errors.Error: No tag specified and default language could not be determined.
manuskript returned -1
logout

[Process completed]

**Comment by vitalibondar** [comment] 2016-05-15 19:49
Same issue:
`Warning: failed to load translator for locale en_US...
Traceback (most recent call last):
  File "<string>", line 13, in <module>
  File "manuskript/main.py", line 63, in run
  File "manuskript/main.py", line 69, in launch
  File "manuskript/mainWindow.py", line 51, in __init__
  File "manuskript/ui/mainWindow.py", line 167, in setupUi
  File "manuskript/ui/views/textEditView.py", line 79, in __init__
  File "enchant/__init__.py", line 548, in __init__
enchant.errors.Error: No tag specified and default language could not be determined.
manuskript returned -1
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]`

**Comment by dmbhatti** [comment] 2016-07-02 01:05
My mac doesn't even run manuscript and actually tells me to put it in the trash lol. 
![screen shot 2016-07-01 at 9 01 58 pm](https://cloud.githubusercontent.com/assets/5568781/16537399/6eacf37c-3fcf-11e6-9988-a412c462a92a.png)

**Comment by marnen** [comment] 2016-07-11 19:41
I wonder if it would be worth using [py2app](https://pythonhosted.org/py2app/) to package this better.

**Comment by marnen** [comment] 2016-07-11 19:43
@dmbhatti In the meantime, what happens if you right-click on the file and choose Open from the context menu? Some warnings of that sort can be overridden that way; I don't remember if the one you're seeing can be.

**Comment by marnen** [comment] 2016-07-11 20:17
@dmbhatti Rats. I'll see what it does for me when I'm not at work.

**Comment by olivierkes** [comment] 2016-10-01 09:30
I'm sorry I don't own a mac so it's difficult for me to test, and packaging is not my priority now. If @marnen wants to play with that, that would be awesome :)

You might wanna try to run manuskript from source: [Run manuskript on OS X](https://github.com/olivierkes/manuskript/wiki/Run-manuskript-on-OS-X)

**Comment by marnen** [comment] 2016-10-01 21:01
I doubt that I have time to do much with this. @olivierkes I will say, though, that if packaging is not a priority for you, you probably won't get many non-technically-minded users...

If I do have time, I'll play around with it, but don't assume that I'll get to it. :)

**Comment by katafrakt** [comment] 2016-10-17 19:42
Hi!

I have the same problem and it seems that rescuing from `enchant.errors.Error` could help here. However, I was not able to recreate this exception while running from source and I don't know anything about OSX packaging (I just got new Mac at work recently and wanted to run Manuskript on it) so I can't confirm it would help.

BTW how is the package different from just downloading a tarball of latest version from Github?

**Comment by olivierkes** [comment] 2016-10-17 21:17
@katafrakt I guess this is because the packaged version is 0.3.0, whereas the sources have corrected a few bugs, including this one.

The package is different in that it is self-contained: it includes python, Qt, PyQt, etc.

**Comment by michae1ho11ey** [comment] 2016-12-06 14:02
I can't get Manuskript to run on my Mac either, but I get different error than stated above. I wasn't sure if I should open an new issue or not. I'm running macOS Sierra (10.12). I followed these instructions for running the app: https://github.com/olivierkes/manuskript/wiki/Run-manuskript-on-OS-X

From the master branch starting the app from the terminal worked, but when I tried to create a new empty file it crashed with this output. Running the packaged version it crashed in the same manner.

```
$ ./manuskript
Warning: failed to load translator for locale en_US...
Traceback (most recent call last):
  File "/Users/michael/Repos/manuskript/bin/../manuskript/ui/welcome.py", line 159, in createFile
    self.loadDefaultDatas()
  File "/Users/michael/Repos/manuskript/bin/../manuskript/ui/welcome.py", line 344, in loadDefaultDatas
    t = [i for i in self.templates() if i[0] == self.template[0]]
  File "/Users/michael/Repos/manuskript/bin/../manuskript/ui/welcome.py", line 344, in <listcomp>
    t = [i for i in self.templates() if i[0] == self.template[0]]
IndexError: list index out of range
Fatal Python error: Aborted

Current thread 0x00007ffff33983c0 (most recent call first):
  File "/Users/michael/Repos/manuskript/bin/../manuskript/main.py", line 72 in launch
  File "/Users/michael/Repos/manuskript/bin/../manuskript/main.py", line 63 in run
  File "./manuskript", line 13 in <module>
Abort trap: 6
```

I'd love to help with getting to work on a Mac, but my Python knowledge is very rusty, but I'll do what I can.

**Comment by gedakc** [comment] 2017-06-06 17:17
@michae1ho11ey several problems have been fixed since you reported the startup issue.  Could you try the latest **master** branch which currently contains the 0.4.0 release of Manuskript?

If you have already cloned the git repository then you can update your copy with the `git clone` command.

Also if anyone is able, a Mac OS X package of the Manuskript 0.4.0 release would be appreciated.
See the request on [Manuskript - Download](http://www.theologeek.ch/manuskript/download/) page.

**Comment by michae1ho11ey** [comment] 2017-06-06 17:58
Unfortunately I've broken Python on my daily driver Mac so I can't test right now. I'll try on my Mac mini at home which should have a working Python set up. I'll let you know how that goes.

**Comment by katafrakt** [comment] 2017-06-07 08:42
So, it seems that Qt (or PyQt) in Homebrew does not have QtWebKit (followup to #54).

```
Running manuskript version 0.4.0.
Warning: failed to load translator for locale en_US...
Traceback (most recent call last):
  File "./manuskript/bin/manuskript", line 13, in <module>
    main.run()
  File "/Users/pawel/dev/github/manuskript/bin/../manuskript/main.py", line 64, in run
    launch()
  File "/Users/pawel/dev/github/manuskript/bin/../manuskript/main.py", line 68, in launch
    from .mainWindow import MainWindow
  File "/Users/pawel/dev/github/manuskript/bin/../manuskript/mainWindow.py", line 22, in <module>
    from manuskript.ui.exporters.exporter import exporterDialog
  File "/Users/pawel/dev/github/manuskript/bin/../manuskript/ui/exporters/exporter.py", line 10, in <module>
    from manuskript import exporter
  File "/Users/pawel/dev/github/manuskript/bin/../manuskript/exporter/__init__.py", line 4, in <module>
    from manuskript.exporter.manuskript import manuskriptExporter
  File "/Users/pawel/dev/github/manuskript/bin/../manuskript/exporter/manuskript/__init__.py", line 6, in <module>
    from manuskript.exporter.manuskript.HTML import HTML
  File "/Users/pawel/dev/github/manuskript/bin/../manuskript/exporter/manuskript/HTML.py", line 4, in <module>
    from PyQt5.QtWebKitWidgets import QWebView
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'
```

**Comment by gedakc** [comment] 2017-06-07 15:22
Thank you @katafrakt for trying out the recent version of Manuskript, and also for linking to the issue regarding QtWebKit.

The QtWebKit issue mentions that QtWebKit is still developed but no longer bundled with QT.  It did say that pre-compiled binaries are available for Windows and Mac for QtWebKit.

Do you think you will have a chance to try the pre-compiled QtWebKit binaries to try to get Manuskript working?

**Comment by katafrakt** [comment] 2017-06-07 16:02
I'm quite sure that I managed to run Manuscript on Mac some 2 or 3 months ago somehow, so I'll give it a shot in near future again.

**Comment by gedakc** [comment] 2017-06-07 17:29
That would be great.  :-)

The WIKI contains instructions on how to [Run manuskript on OS X](https://github.com/olivierkes/manuskript/wiki/Run-manuskript-on-OS-X).  If changes are needed then please let us know, or update the article directly.

**Comment by katafrakt** [comment] 2017-06-12 16:17
I have it working, the process was painful though:

1. `brew install qt5 --with-qtwebkit` - it take ridiculous amount of time (4.5 hour for me)
2. `brew link qt5`
3. Install PyQt5 manually:
```
wget https://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-5.8.2/PyQt5_gpl-5.8.2.tar.gz
tar -xvf PyQt5_gpl-5.8.2.tar.gz
cd PyQt5_gpl-5.8.2
wget https://sourceforge.net/projects/pyqt/files/sip/sip-4.19.2/sip-4.19.2.tar.gz
tar -xf sip-4.19.2.tar.gz
cd sip-4.19.2
make
cd ..
python3 configure.py --sip-incdir=sip-4.19.2/siplib/
make
make install
```

After that, running `bin/maunskript` open the app. I know that's a long way but maybe a starting point for someone to make it shorter. Also, right now I'm not really sure if the first step is really necessary but I don't want to lose 4.5 hours again to check right now ;)

**Comment by marnen** [comment] 2017-06-12 16:44
@katafrakt That looks like very useful information. Now that we have a procedure, maybe it can become a Homebrew formula...

**Comment by gedakc** [comment] 2017-06-12 19:30
@katafrakt thanks for reporting with how you got manuskript running on a Mac.

From looking at the steps you posted, I suspect that `brew install qt5 --with-qtwebkit` installed the entire qt5 cross-platform application framework, which would be much larger than just PyQt5 and might explain the 4.5 hours (and ??? disk space used?).  This is just a guess though as I do not work on or have access to Mac OS X.

**Comment by katafrakt** [comment] 2017-06-13 07:52
@marnen Might be, but homebrew formula that runs for 5 hours is not good, I think 😉  Also, I think "regular people" don't use homebrew (correct me if I'm wrong), so dmg image is a must anyway.

@gedakc I don't see any option for qtwebkit in [pyqt formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/pyqt.rb), while it's there in [qt formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/qt.rb#L21). Also, PyQt from homebrew started to compile Qt for me, even though I had it installed already, so I think it's best to avoid it.

**Comment by katafrakt** [comment] 2017-06-13 09:18
Ba news is: you need to `brew install qt5 --with-qtwebkit`, otherwise it's built withohut `QtWebKit` and `PyQt` builds without support for it.

**Comment by katafrakt** [comment] 2017-06-13 10:12
Good news: Replacing QtWebKit with QtWebEngine is almost trivial and it works with default Qt installation and default PyQt installation. I'll share the changes later.

**Comment by gedakc** [comment] 2017-06-13 20:48
@katafrakt thank you for investigating further regarding qt5, pyqt5, and --with-webkit.

Also thank you for posting code changes to use QtWebEngine instead of QtWebView.  I plan to test these soon on GNU/Linux and Windows.

I like to maintain backward compatibility as much as is reasonably possible, so one thing I will be checking is to see if QtWebEngine works on Windows XP with Python v3.4.4 and PyQt v5.5.1.

**Comment by gedakc** [comment] 2017-06-14 18:47
Unfortunately it appears that Windows XP is not supported with QT WebEngine.

Quote from [Deploying Qt WebEngine Applications](https://doc.qt.io/qt-5/qtwebengine-deploying.html):

> On Windows, QtWebEngine only supports Windows Vista or newer as target platform. Due to use of newer API in Chromium, **Windows XP is not supported**. WinRT is not supported, either.

Based on this lack of support for older platforms I think if we are to implement QtWebEngine then we will need a solution that can also continue to use QtWebView.

**Comment by katafrakt** [comment] 2017-10-12 21:15
So, I played a bit with PyInstaller and managed to create a self-contained package from `develop` branch. It runs on my mac, however I have no way to test it on other machines. If you're willing to try, here it is: https://www.dropbox.com/s/vf92ghnlpj7x4mk/manuscipt-0.4.0-develop-osx.zip?dl=0

**Comment by gedakc** [comment] 2017-10-15 19:07
Thank you @katafrakt for creating a package for Mac.  Hopefully other Mac OS X users will be able to test and provide feedback.

Soon I think we should create a new release.  Before that happens there is a critical bug in the current _develop_ branch that prevents creating and saving a new project.  I believe the bug was recently introduced with commit [Fixes: Crash when permissions don't allow saving #138](https://github.com/olivierkes/manuskript/commit/f2aa9abc85a417d177280a425e5ebef31ef22bf1).  If @olivierkes doesn't get a chance to investigate that I will look at it in a day or two.

**Comment by gedakc** [comment] 2017-10-18 18:37
Based on the thumbs up by @Emstanif on the OS X package, I take it that the package worked.  :+1: 

Currently we are awaiting language translations updates for the 0.5.0 release.

@katafrakt would you consider creating a Mac OS X binary package for the old official 0.4.0 release?

I guess it would require building the old QtWebKit as you discovered how to do earlier.

If you create a `manuskript-0.4.0-osx.zip` file then we can upload the package to the official release locations.

If not, then no worries.  More important is that we create packages for Linux, Windows, and Mac OS X when 0.5.0 is officially released.

I offer to build the Linux and Windows packages and I will be including the pyEnchant spell checker in the packages.

**Comment by katafrakt** [comment] 2017-10-18 19:37
@gedakc is "old official 0.4.0" basically current `master`? I can try, but no promises.

**Comment by gedakc** [comment] 2017-10-18 20:16
Yes, "old official 0.4.0" is basically current master.  A git tag is applied to every release.

You can list git tags with the `git tag` command.

You can check out old releases with a command like:
`git checkout -b mylabel 0.4.0`

**Comment by krazyjakee** [comment] 2017-10-29 23:15
@katafrakt when trying to run your self-contained package (manuskript binary), I get this error:

```
[73008] Error loading Python lib '/Users/User/Downloads/manuskript/Python': dlopen: dlopen(/Users/User/Downloads/manuskript/Python, 10): Symbol not found: _clock_getres
  Referenced from: /Users/User/Downloads/manuskript/Python (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/User/Downloads/manuskript/Python
```

Am I missing something?

**Comment by katafrakt** [comment] 2017-10-30 08:11
@krazyjakee it seems it's related to XCode version. I didn't realize it's so different between them. What your `xcodebuild -version` says?

**Comment by olivierkes** [comment] 2017-10-30 08:23
Something similar here? https://github.com/pyinstaller/pyinstaller/issues/1191

**Comment by krazyjakee** [comment] 2017-10-30 11:14
@katafrakt 

```
Xcode 8.2.1
Build version 8C1002
```

**Comment by katafrakt** [comment] 2017-10-30 15:51
> The only way to be certain your app supports an older version of Mac OS X is to run PyInstaller in the oldest version of the OS you need to support.
(from: http://pythonhosted.org/PyInstaller/usage.html#making-mac-os-x-apps-forward-compatible)

That's quite unfortunate, since I cannot downgrade neither OS, nor XCode...

**Comment by gedakc** [comment] 2017-10-30 15:53
@katafrakt if your computer has sufficient free hard drive space and RAM, then you might consider settting up a Virtual Machine to contain and run an older OS.

On GNU/Linux I use both VirtualBox and VMWare Player to enable me to run Windows and multiple GNU/Linux distros.

**Comment by krazyjakee** [comment] 2017-10-30 16:01
Please excuse the extreme derailing of this issue, but I think the project would hugely benefit by porting to [Electron](https://electron.atom.io/) or something a little less convoluted. The entire concept is fantastic and would be simple enough to swiftly port. It would greatly empower any front-end work too by not being restricted by qt dependency hell.

**Comment by olivierkes** [comment] 2017-10-31 06:15
@krazyjakee: if you know anyone capable of porting manuskript to Electron, then go with my blessings. Thing is, I know python and I know Qt, and they're great. Many great apps are written in PyQt and are widely used (Calibre is a great example, Anki another one), so we just have to figure that part out. And we will :)
We won't continue that thread derailing, if you want a longer discussion please open another thread.

And big thanks to everyone working on packaging!

**Comment by marnen** [comment] 2017-10-31 06:17
@katafrakt Since Travis can do Mac builds, is that a possibility for supporting older versions?

**Comment by gedakc** [comment] 2017-11-01 21:14
[Manuskript 0.5.0](https://github.com/olivierkes/manuskript/releases/tag/0.5.0) has been released in case any Mac users are able to contribute a [PyInstaller build](https://github.com/olivierkes/manuskript/wiki/Package-manuskript-for-OS-X).

Ideally for forward compatibilty the package would be built upon the oldest still supported version of Mac OS X.  With that being said, any package would be better than none at all.

**Comment by katafrakt** [comment] 2017-11-04 01:18
I've been playing with Travis builds as @marnen suggested, but since it was a new topic for me, it took some time. Anyway, the result is supposed to be a mac package compiled using older XCode (7.3.1 [according to the docs](https://docs.travis-ci.com/user/reference/osx/#OS-X-Version)).

Can you please try it out (especially @krazyjakee)? It can be downloaded here for now: https://github.com/katafrakt/manuskript/releases/tag/0.5.0

This is a version without PyEnchant support. Enabling it causes an error, I think this is a bug. I'll report it in separate issue.

**Comment by gedakc** [comment] 2017-11-04 16:26
First, a huge thank you @katafrakt.  Yours is the first official release package since 0.3.0 was released over a year ago.  I'm confident that our Mac OS X users will appreciate your work.

I have uploaded your build so it is available on all our official download locations.  For example see [Manuskript Download](http://www.theologeek.ch/manuskript/download/).  If you would prefer to have your full name shown instead of your github userid then please let me know.

After we have confirmation from at least one user that the OSX package works, then I think we can close this report.

**Comment by katafrakt** [comment] 2017-11-04 19:05
@gedakc Since it's a Travis build, maybe we could integrate it in the repository, so you don't need me or someone else around to build it? For now it's configured to perform a build every time a tag is pushed to the repository and the resulting image is uploaded to Github releases page. I can clean it up and make a pull request where we can discuss it in detail. I think it can be also reused to create Linux builds (although there is no support for Windows, as far as I know).

Meanwhile you can take a look at [`.travis.yml`](https://github.com/katafrakt/manuskript/blob/travis/.travis.yml) that was used to create it.

**Comment by olivierkes** [comment] 2017-11-04 19:42
This is awesome ! If we could do this things would be much simpler.

**Comment by gedakc** [comment] 2017-11-04 19:52
Agreed.  Automatic building of Mac OS X and/or Linux builds would be fantastic.

I'll have to do some reading up on Travis.  When it was first suggested I thought Travis was a person.  :-)

**Comment by krazyjakee** [comment] 2017-11-05 18:46
@katafrakt I can confirm it works like a charm :D

But seriously, thanks so much for putting time into this. <3

**Comment by katafrakt** [comment] 2017-11-12 20:03
Here's a version with PyEnchant (spellcheck) enabled: https://github.com/katafrakt/manuskript/releases/tag/0.5.1-test It works on my machine, so things are looking good.

**Closed** 2017-11-22 19:48 UTC
Labels: packaging
