### ISSUE TITLE
Seg faults found

### ISSUE THREAD

**Issue by KenMcConnell** [olivierkes/manuskript#9] opened 2016-03-25 15:58 UTC
Running on Ubuntu 15.10

Current thread 0x00007fb5df7ca700 (most recent call first):
  File "manuskript/models/outlineModel.py", line 100 in parent
  File "manuskript/ui/views/textEditView.py", line 228 in update
  File "manuskript/models/outlineModel.py", line 147 in setData
  File "manuskript/ui/views/cmbOutlineStatusChoser.py", line 125 in submit
  File "manuskript/main.py", line 65 in launch
  File "manuskript/main.py", line 56 in run
  File "<string>", line 13 in <module>

(Had created a new folder in Outline Mode and was setting the status dropdown when it crashed.)

Current thread 0x00007f275cdd8700 (most recent call first):
  File "manuskript/models/outlineModel.py", line 100 in parent
  File "manuskript/ui/views/textEditView.py", line 259 in rowsAboutToBeRemoved
  File "manuskript/models/outlineModel.py", line 364 in removeRows
  File "manuskript/models/outlineModel.py", line 356 in removeRow
  File "manuskript/models/outlineModel.py", line 336 in removeIndex
  File "manuskript/models/outlineModel.py", line 353 in removeIndexes
  File "manuskript/ui/views/outlineBasics.py", line 179 in delete
  File "manuskript/main.py", line 65 in launch
  File "manuskript/main.py", line 56 in run
  File "<string>", line 13 in <module>
Segmentation fault

(I was deleting a scene when it crashed.)

**Comment by olivierkes** [comment] 2016-03-26 10:59
Thanks for reporting.

I guess you're running manuskript 0.2.0 ?

Can you reproduce?

**Comment by KenMcConnell** [comment] 2016-03-26 15:42
I was able to get it to crash again creating a new folder in Outline mode
and setting the Status, then trying to set the Label. But then I relaunched
it and did the same thing again and had no problems. Seems interment.

Yes, running 0.2.0 Manuskript.

   Ken McConnell

   Twitter - @KenMcConnell
   Google - +KenMcConnell
   Blog - http://ken-mcconnell.com

**Comment by olivierkes** [comment] 2016-03-26 20:15
I tried a few times and wasn't able to reproduce.
I had similar segfault in the past, but thought I fixed them...
Just for the sake of completedness, can you post your python version, and
Qt version?

Olivier Keshavjee
Ch. du Daillard 37
1070 Puidoux
+41 (0)76 345 47 49
http://www.theologeek.ch

2016-03-26 16:42 GMT+01:00 Ken McConnell <notifications@github.com>:

> I was able to get it to crash again creating a new folder in Outline mode
> and setting the Status, then trying to set the Label. But then I relaunched
> it and did the same thing again and had no problems. Seems interment.
>
> Yes, running 0.2.0 Manuskript.
>
> Ken McConnell
>
> Twitter - @KenMcConnell
> Google - +KenMcConnell
> Blog - http://ken-mcconnell.com
>

**Comment by KenMcConnell** [comment] 2016-03-26 21:12
Python 3.4.3+
QT = x86_64-linux-gnu/qt4



   Ken McConnell

   Twitter - @KenMcConnell
   Google - +KenMcConnell
   Blog - http://ken-mcconnell.com

**Comment by gedakc** [comment] 2017-06-06 15:38
Thank you @KenMcConnell for discovering and reporting segfaults.

I am relatively new to Manuskript, but working to improve the robustness and reliability of Manuskript.

On May 25th, 2017 @olivierkes released Manuskript version 0.4.0, which includes a number of improvements since 0.2.0.

Would you be able to try 0.4.0 to see if the issues with segfaults have been fixed?

**Comment by gedakc** [comment] 2017-10-18 17:26
> I was able to get it to crash again creating a new folder in Outline mode and setting the Status, then trying to set the Label. But then I relaunched it and did the same thing again and had no problems. Seems interment.

I have tried to recreate this segfault, but have been unsuccessful.

@olivierkes should we close this report?
We can always re-open or create a new issue if the segfault occurs in the upcoming 0.5.0 release.

**Comment by olivierkes** [comment] 2017-10-19 11:49
Agreed.

**Closed by olivierkes** 2017-10-19 11:49 UTC
Labels: bug
