### ISSUE TITLE
Redaction's tab problem in 0.3.0 win version

### ISSUE THREAD

**Issue by Yirojan** [olivierkes/manuskript#92] opened 2017-04-17 20:45 UTC
I'm not developer but recent user of the program. Manuskript 0.3.0 win 32 version can't save or load the information in redaction's tab. Every time I open my project, after saving it, this blank tab appears, without information. I tried it by saving the sample project as its own and also loaded this tab completely blank.

----------------------

No soy desarrollador, sino usuario reciente de este programa. La versión 0.3.0 de windows de Manuskript no guarda o no carga el contenido de la pestaña Redacción. Cada vez que abro mi proyecto tras haberlo guardado aparece esta pestaña completamente en blanco. Para probar, guardé el proyecto de ejemplo como si fuera propio, y al cargar toda la información de la pestaña Redacción había desaparecido.

**Comment by olivierkes** [comment] 2017-04-18 06:02
Thanks for reporting. 
So you mean you can't save any of your writing?! That would be very bad indeed. 
Do you see any error message in the console?

**Comment by Yirojan** [comment] 2017-04-18 15:01
All content is saved except the information in the Redaction's tab. Resume, Characters, Plots, World... all rigth, but the information in Redaction's tab dissapear. Console does not display error message. 

I have opened my project, added a new sheet and a few lines of text in the Redaction's tab, saved and closed the project and I have reopened it. Here is what appears on the console:

Found translation in settings: C:\Program Files (x86)\manuskript_0.3.0_win32\i18n\manuskript_es.qm
Loaded translation: C:\Program Files (x86)\manuskript_0.3.0_win32\i18n\manuskript_es.qm.
Loading: C:/Users/xxx/xxx/xxx/La poción de la felicidad/La poción de la felicidad.msk
Detected file format version: 1. Zip: True.
Proyecto C:/Users/xxx/xxx/xxx/La poción de la felicidad/La poción de la felicidad.msk cargado.
Proyecto C:/Users/xxx/xxx/xxx/La poción de la felicidad/La poción de la felicidad.msk guardado.
Proyecto C:/Users/xxx/xxx/xxx/La poción de la felicidad/La poción de la felicidad.msk guardado.
Proyecto C:/Users/xxx/xxx/xxx/La poción de la felicidad/La poción de la felicidad.msk guardado.
Proyecto C:/Users/xxx/xxx/xxx/La poción de la felicidad/La poción de la felicidad.msk guardado.
Loading: C:/Users/xxx/xxx/xxx/La poción de la felicidad/La poción de la felicidad.msk
Detected file format version: 1. Zip: True.
Proyecto C:/Users/xxx/xxx/xxx/La poción de la felicidad/La poción de la felicidad.msk cargado.

**Comment by Yirojan** [comment] 2017-04-18 15:16
By the way, i have win10 64 bits system, in case that could have any relation.

**Comment by olivierkes** [comment] 2017-04-18 22:49
This is strange.... Users have reported troubles with accented characters.
Can you try to create a project without any in its name and path?
Also, can you open the sample project and does it work?

Le 18 avr. 2017 17:16, "Yirojan" <notifications@github.com> a écrit :

By the way, i have win10 64 bits system, in case that could have any
relation.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/olivierkes/manuskript/issues/92#issuecomment-294878061>,
or mute the thread

**Comment by Yirojan** [comment] 2017-04-19 09:24
I've made a video to show what happens. I hope it helps to understand what happens. I also attached a screenshot of the console after the whole process.

https://youtu.be/bLLo7Shg0m8

![manuskript_2017-04-19_11-17-12](https://cloud.githubusercontent.com/assets/27704566/25172914/b8965ee8-24f2-11e7-8710-ee0ffc240c34.png)

**Comment by gedakc** [comment] 2017-05-24 17:18
Thank you @Yirojan for the video demonstrating the issue you discovered.

The latest version of the manuskript source code contains some improvements for opening and closing projects.

I tried using your steps, and the latest **develop** branch of the source code on GNU/Linux and all of the data was saved.

Would you be able to try running manuskript from the latest **develop** branch?

**Comment by gedakc** [comment] 2017-06-05 17:03
Recently I tried manuskript 0.3.0 and using the steps in the video I was able to reproduce the missing Redaction tab data missing issue reported by @Yirojan.

Now that manuskript 0.4.0 has been released, which contains the **develop** branch I tested earlier, I highly recommend trying 0.4.0.  With the code contained in 0.4.0, I did not encounter the Redaction tab data missing issue.

**Comment by olivierkes** [comment] 2017-06-15 11:46
Should we close this then?

**Comment by gedakc** [comment] 2017-06-15 15:11
Personally I think this issue should be closed because I was able to confirm the issue with 0.3.0, and also that the issue was gone with 0.4.0.

Ideally @Yirojan would be able to test and respond.  However, because this issue meant that projects could not be reliably loaded or saved, it is possible that @Yirojan has moved on to using different software.

**Comment by olivierkes** [comment] 2017-06-16 07:04
Ok let's close it for now, and if @Yirojan comes by we can still reopen it.

**Closed by olivierkes** 2017-06-16 07:04 UTC
Labels: bug
