### ISSUE TITLE
Objectif by characters and not by word

### ISSUE THREAD

**Issue by bepolymathe** [olivierkes/manuskript#586] opened 2019-05-24 13:44 UTC
Would it be possible to add the possibility of setting the objective of writing a document by number of characters instead of the number of words ? This is in high demand in the humanities and social sciences.

**Comment by gedakc** [comment] 2019-06-04 17:05
Tracking the character count has been requested previously.

Closing this issue as a duplicate of [Issue 334 - Show character count progress indicator](https://github.com/olivierkes/manuskript/issues/334).

**Closed by gedakc** 2019-06-04 17:05 UTC
