### ISSUE TITLE
Manuskript 0.3.0 crash on Windows 10

### ISSUE THREAD

**Issue by scribas** [olivierkes/manuskript#83] opened 2017-02-02 11:16 UTC
When Manuskript opens, the command prompt window gives warning:
"Warning: failed to load translator for locale en_US..."
When I try to create a new project, Manuskript crashes, as I try to save the file:
Traceback (most recent call last):
  File "manuskript\ui\welcome.py", line 159, in createFile
  File "manuskript\ui\welcome.py", line 344, in loadDefaultDatas
  File "manuskript\ui\welcome.py", line 344, in <listcomp>
IndexError: list index out of range

**Comment by olivierkes** [comment] 2017-03-10 12:59
This is a duplicate of #44.
Try double-clicking on a template before saving (the UI must change).

**Closed** 2017-03-10 12:59 UTC
