### ISSUE TITLE
Editor's buttons not working

### ISSUE THREAD

**Issue by hmslima** [olivierkes/manuskript#300] opened 2018-01-13 17:05 UTC
The buttons of the Editor for making the text bold, italic or underlined aren't working, is it because the program still is in Alpha fase? Ah, and everytime I click on the button "Format Clear" the program crashes, it's closed instantly

I am testing this program on the updated Linux Mint 18.2 MATE 64bits. I've installed all the required packages.

**Comment by gedakc** [comment] 2018-01-13 17:17
You are correct.  The format buttons do not work.

This is a duplicate of issue #59.

The format buttons do not work since manuskript was changed from using rich text format to using markdown syntax.  The format buttons have been removed from the GUI in the git **develop** branch and will be gone with the next release (0.7.0).  Ideally we should have removed these buttons earlier (our bad).

See issue #59 for additional information and samples of markdown syntax.

@olivierkes what do you think of making a 0.7.0 release soon?

The reason for the suggested release is to avoid future reports of the problems with the format buttons.  This issue has previously been reported in issue #59, issue #250, issue #285, issue #286.

**Closed by gedakc** 2018-01-13 17:17 UTC
Labels: duplicate

**Comment by hmslima** [comment] 2018-01-13 17:21
Ah, OK. Sorry for making an already made question. I didn't see the tab of Closed issues.
