### ISSUE TITLE
Fullscreen editor suggestions

### ISSUE THREAD

**Issue by worstje** [olivierkes/manuskript#527] opened 2019-03-04 13:01 UTC
I finally got around to writing a couple of chapters in Manuskript in the past few days while also figuring out what works best for me. And based on that I have a few requests / suggestions which will cause me to spam some issues. Feel free to shut any of them down; they are just what I think is handy or convenient.

This particular issue concerns my experience with the fullscreen editor mode.

## Markup colors

I already mentioned a related topic in one of the other issues I opened today, but I cannot adjust the color of bracketed spans to match my editor colors, making some of them hard to read unless I change my editor to look different from what I would find most convenient.

## Lock Screen panel on left is unreadable

No doubt this is because of my custom color theme as I can read it when I switch to another one, but I am not sure which colors it uses. It uses a combination of colors that don't end up on top of eachother in the editor, at least.

(I don't quite know how this featureworks, either... the 'lock' name scares me a bit, haha! 🤣 I'll experiment with that another day!)

## Top hover bar only has the spell check... what a waste of space.

I feel like more could be done with the top hover bar. For example, have the remainder of the empty space show the text name. Or have it show the one-line summary for reminding purposes. Or maybe both. (Or just make it configurable in the Settings -> Views screen somewhere like is done for so many other views!)

## No easy way to check text summary while writing.

I would not mind a button in the top bar that would toggle the usage of the free space on the right side to list the multiline summary of that text (which I use to briefly describe the plot points I need to touch on while actually writing a text). It would be a very useful thing indeed.

Right now, I find myself leaving the full screen mode far too much to make this happen. (And in the process I get slammed in the face by all the brightness of the whitish interface colors. 🤣 )

**Comment by gedakc** [comment] 2019-03-04 16:53
@worstje, were you aware that @katafrakt was actively working in this area?

See Issue #234 and Pull Request #509.

Your testing and comments could go a long way to helping @kakaroto implement fullscreen improvements.

**Comment by worstje** [comment] 2019-03-04 17:13
No @gedakc , I wasn't aware at all. I have spent almost all my time the last few weeks at importing all my old chapters into Manuskript, setting up a way to publish them in a format I can use and only just now got to finally use the program for the actually productive parts of it. 😁 

My primary aim for posting all these issues was something you said several weeks ago regarding the importing functionality in particular, which was to essentially share my experiences. I figured that no matter what part of the program it is, whatever thoughts I have along the way could give the developers some insights as to my usage patterns and perhaps help identify bits that need love, even if it is not in the way I suggest.

I'll give those issues and that pull request a look over; thank you for bringing them to my attention.

Maybe I'll finally take the plunge of switching over git-sourced Manuskript, or maybe even offer a PR or two. (But that would be the complete anathema to me adopting Manuskript in the first place, which is to stop finding reasons to procrastinate on writing...) Only time will tell! 😄

**Comment by gedakc** [comment] 2019-03-04 17:21
We do appreciate the detailed reports, even if we don't comment on these in a timely manner.

I now need to switch my attention to open Pull Requests.

**Comment by kakaroto** [comment] 2019-03-04 21:47
Hey @worstje! I think you'll like the full screen improvement I've done in PR #509 as it at least fixes the wasted space on the top panel, you can see a screenshot of it in https://github.com/olivierkes/manuskript/issues/234#issuecomment-467695073

As for the unreadable panels, can you give information on what your custom color scheme is? It might help with a screenshot or a way to reproduce and see how unreadable it is.
The suggestion for the summary is interesting but I don't see any "free space" myself because I've set my custom theme to have the text stretched (which actually causes the 'lock screen' panel to overlap the chapter text, making it hard to read as well, see screenshot below). But I think it would be a good idea to have just the summary widget as part of the left panel. I was wondering what I could add to that panel and I think that is it. Would do work for you ? In your case, you could disable the auto-hide, remove the lock parts and enable the metadata part and your right panel would serve as your always-visible summary (or keep it on auto-hide if you prefer).

![image](https://user-images.githubusercontent.com/27990/53765092-0cf9dd00-3e9d-11e9-9fb2-c68e62673852.png)

**Comment by tildagail** [comment] 2019-03-05 07:58
Re: unreadable panels, all my custom themes are light text on a dark background. To make them readable I switched the fg/bg values in fullscreen.py on lines 145-146, so from:

self._bgcolor = QColor(self._themeDatas["Text/Color"])
self._fgcolor = QColor(self._themeDatas["Background/Color"])

to 

 self._fgcolor = QColor(self._themeDatas["Text/Color"])
 self._bgcolor = QColor(self._themeDatas["Background/Color"])

That made the text and background of the panels match the colours used in the main text area.

**Comment by kakaroto** [comment] 2019-03-05 09:03
Yes, good catch! I didn't notice this because my background is different from my foreground, and the opacity is 50%. Your change only affects you if you set opacity to less than 5% or if the colors in "Windows background" and in "Text background" are the same color.
Anyways, what I think @worstje was referring to is the other case and the fact that only the left panel was unreadable. I checked, if I set my text color to green, every text is green but the left panel's text remains black. The fix for that is in updateThemes of fullscreen.py, replace : 
```
        for panel in (self.bottomPanel, self.topPanel):
```
by :
```
        for panel in (self.bottomPanel, self.topPanel, self.leftPanel):
```

**Comment by gedakc** [comment] 2019-04-03 16:10
Closing this issue because many of the items requested have been implemented in the **develop** branch.  New requests for fullscreen enhancements should be based on the **develop** branch or the upcoming [0.9.0](https://github.com/olivierkes/manuskript/milestone/8) release.

**Closed by gedakc** 2019-04-03 16:10 UTC
Labels: enhancement
