### ISSUE TITLE
Impossible to change UI language to english if your system locale isn't set to an anglophonic country

### ISSUE THREAD

**Issue by Protected** [olivierkes/manuskript#619] opened 2019-08-17 12:29 UTC
Version 0.9, Windows 10.

Apparently the "english" option in the settings actually means "system locale if a translation is available for that". I can change to any other language and restart and it will work, but if I change to english and restart it will go back to my system locale language (not english).

The only way I found for working around this issue was to delete the Manuskript translation files entirely.

Please do not do this. The system locale is set for the sake of measurement units, currency, time, etc. and is not my system language or the language I want to read things in. Either have a "System locale" option in the dropdown, distinct from "English" (and keep "English" for "use built-in labels without applying any translation") or do not make any assumptions and let people choose (in addition, this option should be immediately accessible on first run - without requiring the creation of a project - and should prompt for an application restart!)

Thanks.

**Comment by worstje** [comment] 2019-08-18 16:03
Thank you for your report. It is very much appreciated.

I am in complete agreement with you: these things should not be mixed up. Although it can be considered jarring when you end up with days or formats that don't match the language of the rest of the interface, there are good reasons these things are kept separate, some of which you have eloquently described in your post.

Based on your description, I am not sure if the issue is as simple as the system-defined locale setting being labeled as 'English', or if it is indeed an 'English' setting that is being poisoned with system-specific settings.

Would you be able to provide a representative screenshot of the English language in Manuskript with

1. a problematic system locale selected and

2. the correct output with all translation files removed.

Please have your region and locale settings in Windows present on the screenshot for reproduction purposes.

Additionally, feel free to list of any locations you are able to identify that fail to properly behave for the selected language. In order to solve these translation & locale-related issues, it might be best to thoroughly identify the scope of the issues first.

The few volunteers we have that work on Manuskript may not necessarily be in a position to properly identify the scope of this particular issue on their own. The more thoroughly and clearly we document the wrong behaviour, the easier it is for someone to actually dig into this issue. 😄

**Comment by mxamber** [comment] 2019-08-18 22:58
Same issues here. Upon startup (Windows 7), the console window that opens says `Loaded translation from system locale: manuskript_de_DE.qm.` and subsequently presents the UI in German. While there is an option in the settings to switch to another language, it's ineffective, as described above, requiring a restart only to be set to German again. It might be noteworthy that the option in the settings remains set to English, even as the actual language keeps being reset to my system language, German.

**Comment by worstje** [comment] 2019-08-22 12:37
@mxamber Can you share with us the console log you get for your initial start of manuskript, and also what the log looks like when you restart a second time again?

Based on my cursory glance through the code, you should be seeing different messages.

Assuming the message you shared in your post is the only one, then that implies it never saved your language preference to begin with, as it is falling back on the default for your system without any user preference being configured.

I might try to do some more indepth testing at a later point, but it would be nice to exactly understand the nature of the issue before I dig in and try to reproduce the symptoms that are described in this issue. (I am not seeing it in my brief test just now, but I suspect that is in part because my own locale has no Manuskript translation available for it.)

**Comment by mxamber** [comment] 2019-08-22 13:02
**Log upon startup:**

Debug: Web rendering engine used: QWebView
Running manuskript version 0.9.0.
Found translation in settings: 
Loaded translation from system locale: manuskript_de_DE.qm.
Loading: `path/to/my/project`
Detected file format version: 1. Zip: True.
Projekt `path/to/my/project` geladen.
Projekt `my/project` gespeichert.

and then
**Log upon subsequent restart after changing language:**

Debug: Web rendering engine used: QWebView
Running manuskript version 0.9.0.
Found translation in settings: 
Loaded translation from system locale: manuskript_de_DE.qm.

**Comment by worstje** [comment] 2019-08-22 13:22
That is weird. Why does it completely skip trying to load from settings? 🤔 

Actually no, worse. I just noticed the colon. Why is it not storing the translation in the settings to begin with? Clearly the setting it loads is empty, and if it is unable to load a setting it obviously loads from default. That explains the behaviour seen during load-up...

Thank you for the logs; just seeing those saved me barking up the wrong tree when looking for the cause. I'll look further into this later today. 😃

**Comment by mxamber** [comment] 2019-08-22 14:58
In case it's any help, other settings, such as labels or UI style (I changed it to Windows XP style to test if it worked) are saved and loaded properly.

**Comment by mxamber** [comment] 2019-08-24 17:22
I took a look at the registry and the source code and the key it looks for (`applicationTranslation`) is empty. It's not an issue with loading the translation, it's an issue with not storing it in the first place.

**Comment by mxamber** [comment] 2019-08-24 17:28
Take a look at [this commit](https://github.com/olivierkes/manuskript/commit/dc51f6d84e601b21b341c5efa4f853a3c55b4da9) here. English is just "" and many of the languages specified don't exist, for instance, it says UK English is `manuskript_en_GB.qm`, yet no such translation file exists within the current release, however, `manuskript_uk.qm`, here labelled Ukranian, appears to contain the British translations (took a quick peek with the hex editor). I think the issue lies within settings.py or settingsWindow.py.

**Comment by worstje** [comment] 2019-08-24 17:30
It's not quite that simple, @mxamber . I dug into the code the other day - I was on my phone, not really the right time to code but browsing github worked 😄 - and it basically comes down to the code treating an empty string as the 'default' translation (the one in the code, so to speak), which happens to be the English language you expect.

However, when starting the application and detecting what language to load, and then trying to load it, also short-circuits a missing translation to 'autodetect'. Ergo, it kicks in with the autodetection based on your configured region when the interface has the correct option selected.

I intended to write a patch for it today, but I've been getting distracted so it will hopefully be tomorrow. The code is just slightly hairy enough (it smelled like a copypaste from some other project or demo with far more translations available) that I want to properly triplecheck all the code paths to make sure everything makes sense after I fix it. (Which would most likely involve adding an auto-detection entry to the settings screen as well.)

**Comment by mxamber** [comment] 2019-08-24 17:35
i just noticed that ""fixing"" it via regedit crashes if i try to load a project so yeehaw

**Comment by worstje** [comment] 2019-08-24 17:44
If you want to still use an English language and can stomach working around the bug for now, you can set the registry key you mentioned to `manuskript_en_GB.qm` to select the UK English variant. It is not ideal, but at least it is a form of English that is hopefully readable enough. 😉

**Comment by mxamber** [comment] 2019-08-24 19:12
> If you want to still use an English language and can stomach working around the bug for now, you can set the registry key you mentioned to `manuskript_en_GB.qm` to select the UK English variant. It is not ideal, but at least it is a form of English that is hopefully readable enough.

I did, didn't work, said there was no such translation and gave me my system language. I checked, and no file of that name exists. I changed it to `manuskript_uk.qm` which, despite being labelled as Ukranian, contained the English translation, seemed to work but crashed upon opening a project, so back to square one I am.

**Comment by worstje** [comment] 2019-08-24 19:47
Hrm, it sounds like there may be more than one issue. I'll have to check separately later whether or not the British language actually works for me.

**Comment by gedakc** [comment] 2019-08-25 15:06
Adding a British translation is a work in progress.  See issue #592 and also [Weblate](https://hosted.weblate.org/projects/manuskript/translations/).

**Comment by gedakc** [comment] 2019-09-11 16:15
Can someone with a non-English system locale test the proposed fix in PR #619?

**Comment by gedakc** [comment] 2019-09-13 15:16
@mxamber the problem reported is that a system with a non-English locale was unable to display English when choosing English in **Edit -> Settings**, and then restarting Manuskript.  Instead Manuskript would continue to load and display the system locale.

To test you would need to [Run Manuskript from Source Code](https://github.com/olivierkes/manuskript/wiki#install-source-code-more-work-runs-on-more-os-platforms), use the git **develop** branch, and pull down the commits from PR #619.

If you require exact commands then let me know.

**Comment by gedakc** [comment] 2019-09-15 15:24
PR #627 has been tested and confirmed to fix the issue reported here.  This enhancement will be included in the next release of Manuskript.

For a non-English default locale to use English one must first change the Manuskript setting to something other than English, then back to English, then restart Manuskript for the builtin English to be displayed in Manuskript.

**Closed by gedakc** 2019-09-15 15:24 UTC
Labels: bug

**Comment by mxamber** [comment] 2019-09-15 15:27
> For a non-English default locale to use English one must first change the Manuskript setting to something other than English, then back to English, then restart Manuskript for the builtin English to be displayed in Manuskript.

Is this about the current version or the next version? Because in my current install, it won't work, I changed the language to Spanish, restarted, found Manuskript to be in Spanish, changed it to English, restarted, and found Manuskript in my system locale (not English) again.

**Comment by gedakc** [comment] 2019-09-15 15:33
> Is this about the current version or the next version?

This will be fixed in the next version (0.10.0).  This is displayed in on the right hand side of this issue under **Milestone**.  The fix is already available in the git **develop** branch.

> Oh, and setting the language to Dutch gave me the English UI language.

The language translations are in various stages of completion.  See [Weblate - Manusrkipt](https://hosted.weblate.org/projects/manuskript/translations/).  Even the current Dutch translation is only about one third complete.

**Comment by uwe22** [comment] 2020-07-24 03:49
I am running version 0.11.0 having the same problem on OSX 10.14.6
I would like to have the english interface. I set it up in the settings, but
Korean keeps showing up. I downloaded the latest version from git.
Is there a workaround for starting with english?

Running manuskript version 0.11.0.
Preferred translation: ['en-KR', 'ko-KR', 'de-KR'] (based on available ui languages)
No translation found or loaded. (manuskript_en_KR.qm)
Loaded translation: manuskript_ko_KR.qm
Loading: /Users/user/Desktop/test.msk
Detected file format version: 1. Zip: True.
프로젝트 /Users/user/Desktop/test.msk을(를) 불러왔습니다.
프로젝트 test.msk을(를) 갈무리하였습니다.**

![Screen Shot 2020-07-24 at 12 47 53](https://user-images.githubusercontent.com/11908297/88358964-f1ea7e80-cdab-11ea-85d1-e8271cb44542.jpg)

**Comment by pkej** [comment] 2022-01-23 12:01
Quick solution: Go into the Preferences of Manuskript, set to "English (Great Britain)". Restart. Change to "Eglish", voilá, problem fixed.

I'm using Manuskript 0.10.0 (the one Homebrew defaults to) on macOS Monterey, v 12.1.

I hope this helps.
