### ISSUE TITLE
Change application settings style crashed the UI, for awhile ;)

### ISSUE THREAD

**Issue by taw00** [olivierkes/manuskript#676] opened 2019-10-27 18:21 UTC
This is one of those bugs. :/

I upgraded to 0.10 (Fedora 29 fully updated).

I started up Manuskript. It opened fine and of course loaded my current project. I noodled around the settings and tried to move from the Fusion style to the Adwaita Dark style and ... CRASH.

Tried a couple more times and CRASH.

Then I worked on something else for awhile. I came back to it and ran it from the commandline (so I could see any errors) and... I didn't crash anymore. _sigh_ Boggle!

So, I have no clue, but I figured I would finish filing the bug. If there is even a bug. Well, there is _something_ going on.
![Screenshot from 2019-10-27 14-13-26](https://user-images.githubusercontent.com/6908872/67639350-0c4b0680-f8c5-11e9-9d88-9c35c6e1e3ca.png)

**Comment by worstje** [comment] 2019-10-28 00:18
This is probably something Qt related. Manuskript doesn't do anything particularly fancy, and I know I've seen some mystery errors that only happen sometimes when switching skins on Windows.

The best I can do for now is to recommend you try a more recent version of Qt, or worst case scenario downgrade. (Qt is a temperamental library and you never know what you'll get from my experience.)

If you manage to get a proper error at some point, come back so we can offer a final diagnosis on whether the ~~buck~~ bug here is indeed something that needs to be passed to the Qt developers, or whether it is something we need to own up to ourselves.

(But all that probably hangs on whether or not you can manage to figure out a consistent way to reproduce the bug step by step...)

**Comment by TheJackiMonster** [comment] 2021-02-22 19:06
This is a duplicate of #467.

**Closed by TheJackiMonster** 2021-02-22 19:06 UTC
Labels: bug, duplicate
