### ISSUE TITLE
Loading Error with fileno

### ISSUE THREAD

**Issue by SpeedyDoggo** [olivierkes/manuskript#1121] opened 2023-01-29 14:03 UTC
Hello,

I'm seeing a smallish error when I try to boot manuskript and was wondering if there was anything I could do to fix this specific instance. I'm comfortable with JS and some python so I wouldn't mind going in and editing code as needed; I just need a bit of direction. The project is in separate files; this happened after I added and moved a chapter last night and now manuskript.exe won't open and aborts when loading. Manuskriptw.exe gives me the following error.

Traceback (most recent call last):
  File "manuskript", line 11, in `<module>`
  File "`<frozen importlib._bootstrap>`", line 991, in _find_and_load
  File "`<frozen importlib._bootstrap>`", line 975, in _find_and_load_unlocked
  File "`<frozen importlib._bootstrap>`", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "manuskript\main.py", line 17, in `<module>`
AttributeError: 'NullWriter' object has no attribute 'fileno'

Any help is appreciated!

**Comment by TheShadowOfHassen** [comment] 2023-01-31 12:47
So did you change the chapter in the program or out of the program? And to where? It looks like its some sort of loading error. Also it sounds like you set the program to automatically open a project. Delete the Manuskript file here: HKEY_CURRENT_USER/Software/manuskript
(HKEY_CURRENT_USER I am assuming is your user. I got it from the wiki so...)

Just throw the file in the trash and run Manuskript. It should open. Try to create a new manuksript file and run it and if that runs good. You can try opening your old project but it might crash. I can't help you there until you tell me where you put the chapter. But I have a good idea. Don't worry your project won't be lost. We can fix it. I just need more information.

**Comment by SpeedyDoggo** [comment] 2023-02-02 05:04
Moved it within the program. I believe I made the 5th chapter the 2nd within the same folder. The file for the offending chapter itself seems to be named correctly (as in, it starts with 02 and is located in the correct folder). I'm not too worried about data loss since it's all saved in .md files and I've already checked that my latest writing is there, which is a huge relief and gives me the option of just recreating it if it comes to that. I assumed what's wrong is that it didn't properly update the new chapter location but I cannot for the life of me figure out where that's stored.  If it makes a difference, manuskript the program is stored on disc and accesses files from a Google Drive folder that is mirrored locally. I last accessed the project properly on my desktop computer (which I cannot currently access to test.)

I've tried redownloading the program but it still won't open.

In the process of trying to find the file you're talking about, I ended up checking the appdata/local folder, which actually had a log file! The final line is `in lxml.etree._raiseParseError
  File "<string>", line 673
lxml.etree.XMLSyntaxError: expected '>', line 673, column 8
`
I found the file it seems to reference and tried to open it with Python, but it doesn't seem to want to open on my system at least. Not sure what the recommended program for opening / modifying .pyd files would be if not just... Python.

As for the file you pointed out, I had to access it using regedit and deleted the 'lastproject' file to make it no longer automatically open that specific project and... no dice. Manuskript still aborts with the same error in Manuskriptw. Set autoLoad to false, no change. Deleted whole registry, same result. I've attached the log file; maybe it makes sense to someone more experienced with the program and Python.
[2023-01-29_05-46-08_manuskript#9528.log](https://github.com/olivierkes/manuskript/files/10564902/2023-01-29_05-46-08_manuskript.9528.log)

At this point I'm just curious to see what happened because I'm not sure it's the project file anymore....

**Comment by TheShadowOfHassen** [comment] 2023-02-04 12:43
So you know the switch the data to another project. That's one that took me a while. You might have corruption somewhere so it might be better to just do that.

I have no clue what the error could be currently. Have you tried running manuskript from source? I think on Windows its as easy as installing python and pip installing qt. At the very lease it would pin down any freezing errors.

I haven't used windows so I won't be able to help very much unless you're running source, sorry.

**Comment by SpeedyDoggo** [comment] 2023-02-04 17:06
I actually did try to compile it myself after my last post! I installed PyQt 6 though, and then when I tried to run the build, it told me it needed PyQt 5. I installed that, recompiled, but it still gave me the 'needs PyQt 5' error. 

Trying to run from source gets me this:
Traceback (most recent call last):
  File "C:\Users\USER\Documents\manuskript\bin\manuskript", line 11, in <module>
    from manuskript import main
  File "C:\Users\USER\Documents\manuskript\bin\..\manuskript\main.py", line 9, in <module>
    import manuskript.logging
  File "C:\Users\USER\Documents\manuskript\bin\..\manuskript\logging.py", line 216, in <module>
    from PyQt5.Qt import QtMsgType
ImportError: cannot import name 'QtMsgType' from 'PyQt5.Qt' (C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyQt5\Qt.pyd)

So it looks to me I've got something installed in the wrong place? I'll try to poke at it more but there's only so much troubleshooting I can handle without frustration. I do appreciate the help, though!

**Comment by TheJackiMonster** [comment] 2023-02-09 22:15
@SpeedyDoggo Regarding the log you shared: It seems like the `revisions.xml` file of your project is broken. I'd recommend disabling the revision feature completely as it's recommended because it can cause other issues as well. You can also try removing the file (`revisions.xml`) from your project because that will prevent the XML parsing to throw an exception.

Hope this helps.

**Comment by SpeedyDoggo** [comment] 2023-02-12 01:59
That seems to have done the trick, thank you! ManuskriptW.exe still throws the 'fileno' error even without trying to load a project but manuskript.exe (the 0.14 version from the website) opens now. The font / font sizes are a bit messed up, but at this point I'm just glad to use the program again and get back to the workflow I liked best. :)

**Comment by TheJackiMonster** [comment] 2023-02-12 04:08
> That seems to have done the trick, thank you! ManuskriptW.exe still throws the 'fileno' error even without trying to load a project but manuskript.exe (the 0.14 version from the website) opens now. The font / font sizes are a bit messed up, but at this point I'm just glad to use the program again and get back to the workflow I liked best. :)

Maybe that's an issue with the `manuskriptw.exe` itself... I assume this could be related to this closed issue here: #1044

**Comment by TheJackiMonster** [comment] 2023-03-04 15:42
If this issue might still be reproduced with the current state of development, feel free to reopen it. Otherwise I'm closing this for now.

**Closed by TheJackiMonster** 2023-03-04 15:42 UTC
Labels: bug
