### ISSUE TITLE
Error "Fail to load translator..."

### ISSUE THREAD

**Issue by MrDiBs** [olivierkes/manuskript#49] opened 2016-10-01 03:56 UTC
I am running Windows 10 Home 64bit version 10.0.14393 Build 14393
Upon starting Manuskript 0.3.0 I receive this error.  I also tried the older versions of Manuskript and received the same error.

![manuscript error](https://cloud.githubusercontent.com/assets/22554632/19011509/beae2c96-8765-11e6-8a2c-92602f495af2.png)

This is as far as I get.  I cannot create new files as I attempted to do so the software crashes.  
I can only **view** the sample file provided.
Needless to say I cannot use the software at this time.
 
I am no coder but, if there is a simple fix let me know.
If you need more information please ask.

Thanks, for your time and effort.

**Comment by olivierkes** [comment] 2016-10-01 09:18
Duplicate of #44. 

The "translator" thing is just a warning, you can ignore it. As for the crash, please see issue #44 or try the develop branch.

**Closed by olivierkes** 2016-10-01 09:18 UTC
Labels: bug
