### ISSUE TITLE
File won't open in windows, no problem in linux

### ISSUE THREAD

**Issue by bartart3d** [olivierkes/manuskript#359] opened 2018-06-23 06:57 UTC
I've got manuskript project here that won't open in Windows, it does however, without warnings or errors in linux. 
I'm used to linux, and running Manuskript from terminal can show what's going wrong. Is there some similar way to run Manuskript in Windows 10 ?

**Comment by gedakc** [comment] 2018-06-23 15:31
In order to see the console output on Windows when using the PyInstaller binary perform the following steps:

1. Open a Command Prompt
2. Change directory into the folder that contains the manuskript.exe executable
3. Run the executable by entering `manuskript.exe`

For more information see also [Run Manuskript from Source Code on Windows](https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Windows).

**Comment by bartart3d** [comment] 2018-06-24 11:51
Ok, thanks, I managed to track it down to the spellchecker. It was enabled, saved in linux. When disabled, saved and copied over to my windows machine, the file opens just fine...
I tested with another file on windows, created on windows. As soon as I enabled the spellchecker, Manuskript crashed.

**Comment by gedakc** [comment] 2018-06-26 15:57
Thanks @bartart3d for researching further to identify spell check as an issue.   This leads me to believe that you might have encountered the same problem as reported in issue #273.

To troubleshoot further please try the following:

A.  With the project saved with spell check disabled, open the project on Windows, select a dictionary that is installed on Windows, then enable spell check.

Does the program crash?

B.  Alternatively you might try using the **develop** branch of Manuskript and [Run Manuskript from Source Code on Windows](https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Windows).

**Comment by bartart3d** [comment] 2018-07-10 08:36
Hi, sorry for the late reply, I have been on holidays. 
No, I selected English (Dutch isn't installed), then enabled spell check, and no crash. I hope that is the expected behavior for the related issue.

**Comment by bartart3d** [comment] 2018-07-10 10:09
As an extra comment, Dutch was the original spell check language on the linux computer, On windows Dutch is not installed, maybe the crash was caused by not being able to handle a missing language in the spell checker?

**Comment by gedakc** [comment] 2018-07-10 16:48
Thanks @bartart3d for the additional information.  The issue sounds very similar to issue #273.

To confirm if this is fixed, would you be able to test using the **develop** branch of Manuskript and [Run Manuskript from Source Code on Windows](https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Windows)?

**Comment by bartart3d** [comment] 2018-07-11 11:40
Hello,
I just tested it on the development branch, and it seems like the fix has worked indeed 👍 
grtz,
Bart

**Comment by gedakc** [comment] 2018-07-11 17:42
Thanks @bartart3d for confirming that the **develop** branch fixes the issue.

Closing this report as duplicate of issue #273.

**Closed by gedakc** 2018-07-11 17:42 UTC
Labels: bug, duplicate
