### ISSUE TITLE
Index Card Background Freeze

### ISSUE THREAD

**Issue by Exitr** [olivierkes/manuskript#127] opened 2017-07-03 06:08 UTC
Index cards background option defaults to last pic inserted in either directory, even with color background option selected. The only way to acquire a non-photo background is to purge all images from background directories.

**Comment by gedakc** [comment] 2017-07-03 15:40
This report is a duplicate of issue #52.

A fix for the issue is currently included in the **develop** branch of the git repository and is planned for inclusion in the next release of Manuskript (0.5.0).

If you wish to help test the **develop** branch  and _run Manuskript from source code_ then see the instructions in the Manuskript [Wiki](https://github.com/olivierkes/manuskript/wiki).

**Closed** 2017-07-04 21:12 UTC

**Comment by Exitr** [comment] 2017-11-05 19:05
> If you wish to help test the develop branch and run Manuskript from source code then see the instructions in the Manuskript Wiki.

Just wanted to say I'm liking the changes in the develop version.

**Comment by olivierkes** [comment] 2017-11-05 19:12
Thanks :)
