### ISSUE TITLE
The program close when click in the Format Clear tool

### ISSUE THREAD

**Issue by RicardoOpus** [olivierkes/manuskript#250] opened 2017-12-02 20:43 UTC
All the edit tools don't work (Bold, Italic, Underline), and the program close when I click in the Format Clear tool.
I try the .deb and direct to sources (on zip files), both has the same issue.

I use the version 0.6.0 on Linux Mint 18.3

**Comment by darrelwright** [comment] 2017-12-02 20:50
I am on linux mint 18.3 MATE running 0.60. and everything is working. I can use all the markuips, I can clear them. It works beautifully. Sorry to have to disagree with what you are finding.

Darrel

**Comment by gedakc** [comment] 2017-12-02 20:52
This is a duplicate of issue #59.

The format buttons do not work since manuskript was changed over to use markdown syntax.  The format buttons have been removed from the GUI in the git **develop** branch and will be gone with the the next release (0.7.0).

See issue #59 for additional information and samples of markdown syntax.

**Closed by gedakc** 2017-12-02 20:52 UTC
