### ISSUE TITLE
Crash when permissions don't allow saving

### ISSUE THREAD

**Issue by TheFeshy** [olivierkes/manuskript#138] opened 2017-08-15 01:42 UTC
When opening a document without write permissions, and making modifications, autosave causes manuskript to crash.

Version: 0.4 on Archlinux

To reproduce:  Install manuskript, open the sample document "book-of-acts", which is not user-writable.  Make a change, such as dragging a card, and wait for the auto-save.  manuskript crashes with the message:

`Running manuskript version 0.4.0.
Warning: failed to load translator for locale en_US...
Loading: /opt/Manuskript/sample-projects/book-of-acts.msk
Detected file format version: 1. Zip: False.
Project /opt/Manuskript/sample-projects/book-of-acts.msk loaded.
Traceback (most recent call last):
  File "/opt/Manuskript/bin/../manuskript/mainWindow.py", line 488, in saveDatas
    loadSave.saveProject()  # version=0
  File "/opt/Manuskript/bin/../manuskript/loadSave.py", line 21, in saveProject
    v1.saveProject()
  File "/opt/Manuskript/bin/../manuskript/load_save/version_1.py", line 345, in saveProject
    os.replace(oldPath, newPath)
PermissionError: [Errno 13] Permission denied: '/opt/Manuskript/sample-projects/book-of-acts/outline/1-Judea_and_Samaria' -> '/opt/Manuskript/sample-projects/book-of-acts/outline/0-Judea_and_Samaria'
Fatal Python error: Aborted

Current thread 0x00007f7f354ca4c0 (most recent call first):
  File "/opt/Manuskript/bin/../manuskript/main.py", line 73 in launch
  File "/opt/Manuskript/bin/../manuskript/main.py", line 64 in run
  File "/usr/local/bin/manuskript", line 13 in <module>
`

Obviously the program cannot overwrite a file for which it has no permission to write to - however, it shouldn't crash, and should probably suggest doing a "save as."

**Comment by gedakc** [comment] 2017-08-15 15:33
Thank you Dave for this report.  I have confirmed issues with manuskript trying to save when the project file or project files/directories are not writable.

I will investigate further.

**Comment by olivierkes** [comment] 2017-10-14 10:23
Now manuskript shows a warning (in status bar and console) when saving in a directory without write permission.

I'll leave it at that, but if you think that's not enough (that it should display an alert, or open the save-as dialog), please reopen this.

**Comment by gedakc** [comment] 2017-10-14 18:04
Re-opening this issue because it appears that when I create a new project, I cannot save it.

Also I didn't notice the warning in the status bar.  I think we need a pop-up dialog to indicate that saving is not possible and perhaps  suggest save-as.

**Comment by olivierkes** [comment] 2017-10-15 19:41
I misread your message, I thought you said you cannot save a new project *in a non-write-access directory*. Thanks to your comment on #35 I realized my mistake !

This should be working as expecting, at least it does according to my tests.

**Comment by olivierkes** [comment] 2017-10-17 15:10
@gedakc can you confirm this works for you, so we can close this?

**Comment by gedakc** [comment] 2017-10-17 16:06
@olivierkes no worries on the misunderstanding.  I'm glad you were able to develop fix.

Using the _develop_ branch with last commit 447fbb4a2a I confirmed:

* If the file is read-only then an _Error_ is written to the console, and a _WARNING_ is written to the console and the status line at the bottom of the Manuskript window.
* If the directory is read-write then a new project can be created.  :-)

Personally I missed the status line message in my initial testing of a project with read-only permissions.  I think it might be better to have a warning dialog pop up indicating the read-only issue.  With that being said, I think the likelihood of a user trying to purposefully write to read-only project is low.  As such please feel free to close this issue as FIXED.

**Comment by olivierkes** [comment] 2017-10-17 16:27
Yes that was my thought. There's little chance it will cause troubles, but it can be made better.
So i'll close this issue and open a new one as a reminder for the future.

**Closed by olivierkes** 2017-10-17 16:27 UTC
Labels: bug
