### ISSUE TITLE
Timeline column in the outliner

### ISSUE THREAD

**Issue by ghost** [olivierkes/manuskript#684] opened 2019-11-07 02:34 UTC
Perhaps a "Timeline" column in the Outliner could be useful.  For example, you could say "Day 1," "Day 2 (evening)," "Day 7 (morning)," etc. next to your chapters in this column. This way, you could get a good idea of the timeline of your sections at a glance (and maybe spot continuity issues!).

**Comment by TheJackiMonster** [comment] 2021-02-22 21:56
I would close this as duplicate of #118.

**Closed by TheJackiMonster** 2021-02-22 21:56 UTC
Labels: enhancement
