### ISSUE TITLE
I want to translate it to portuguese

### ISSUE THREAD

**Issue by FTMolina** [olivierkes/manuskript#230] opened 2017-11-23 00:00 UTC
Hi,
I really liked Manuskript and want people from Brazil to be able to enjoy it.

**Comment by gedakc** [comment] 2017-11-23 16:25
That's great to hear.  To learn more about translating manuskript to another language see the [Wiki - Translate Manuskript](https://github.com/olivierkes/manuskript/wiki/Translate-Manuskript) article.

**Comment by FTMolina** [comment] 2017-11-23 16:47
Yes, i've read it ^^

"1. Request it

Simply request it by creating a new issue. We will then generate the empty language file and send it to you. You can translate it following instructions below."

**Comment by FTMolina** [comment] 2017-11-23 16:48
Oh wait, just saw there is another way. sry. Will start the work

**Comment by olivierkes** [comment] 2017-11-23 16:56
Hi FTMolina,
Thank you very much for your desire to help!
Great that you found the way to add it yourself. If you have any question I'll answer here. Sorry I took so long today. ;)

**Comment by FTMolina** [comment] 2017-11-23 17:23
Hi guys,
I'm having a problem.
the wiki says to "3.Run pylupdate5 -noobsolete i18n/manuskript.pro"

But i'm getting the error "molina@tardis-POSITIVO-MOBILE:~/traducao/manuskript$ pylupdate5 -noobsolete i18n/manuskript.pro
pylupdate5 error: Cannot open Python source file '/home/molina/traducao/manuskript/i18n/../manuskript/exporter/mmd.py': No such file or directory"

I believe i am using the develop branch (altough it's my first time using github, so i may be wrong). and I edited the file i18n/manuskript.pro and added TRANSLATIONS += manuskript_ptbr.ts (pt stands for portuguese and BR for brazil. Most software translations distinguish brazillian and european portuguese).

What should I do? Do you need more information?

thx in advance :)

**Comment by gedakc** [comment] 2017-11-23 17:37
Thanks @FTMolina for reporting this problem.

The MultiMarkDown exporter provided via the "mmd.py" file was removed in commit 4ddb95ff67 because pandoc provides the same (and more) functionality.

It looks like we neglected to remove it from the **SOURCES** field in the `manuskript.pro` file (and several of the translation `.ts` files, such as `manuskript_fr.ts`.

@olivierkes would you be able to make this change, or would you prefer me to perform the update on **master**?

**Comment by gedakc** [comment] 2017-11-23 17:48
@FTMolina if you wish to continue with translations while we fix this issue, you might remove the `mmd.py` line from `manuskript.pro` and then try to continue with your translation efforts.

```
$ git diff
diff --git a/i18n/manuskript.pro b/i18n/manuskript.pro
index e04e722..568eba0 100644
--- a/i18n/manuskript.pro
+++ b/i18n/manuskript.pro
@@ -69,7 +69,6 @@ SOURCES          += ../manuskript/ui/exporters/manuskript/plainTextSettings.py
 
 
 SOURCES          += ../manuskript/exporter/basic.py
-SOURCES          += ../manuskript/exporter/mmd.py
 SOURCES          += ../manuskript/exporter/manuskript/__init__.py
 SOURCES          += ../manuskript/exporter/manuskript/HTML.py
 SOURCES          += ../manuskript/exporter/manuskript/markdown.py
$
```

**Comment by olivierkes** [comment] 2017-11-23 17:51
I need to update those whole `manuskript.pro`. Some files have been deleted, others added and are not here. I'll try to do that later, but you can still do as @gedakc said: remove that line from manuskript.pro (and if other similare errors occurs, remove those lines to). 

Your work won't be wasted: once I update the .pro file, you can still simply update your translation and it should be faster.

**Comment by gedakc** [comment] 2017-11-23 17:59
> @FTMolina: I edited the file i18n/manuskript.pro and added TRANSLATIONS += manuskript_ptbr.ts

I think the naming standard is to place a hyphen between **pt** and **br**.  For example `manuskript_pt-br.ts`.

On the [gparted](https://gparted.org) project I also work on, the Brazillian Portugese translation used [`pt_BR`](https://git.gnome.org/browse/gparted/tree/po), which I believe is the GNOME translation standard.  I do not know if there is a standard for Python3 and PyQt5 which is used by manuskript.

**Comment by olivierkes** [comment] 2017-11-23 18:06
I don't know about that, but `pt_BR` looks better to me. I need to find out, but [the manual](http://doc.qt.io/qt-5/linguist-programmers.html) doesn't say anything about that.

**Comment by olivierkes** [comment] 2017-11-23 18:11
[Here](https://github.com/cedrus/qt4/tree/cedrus-qt/translations) for example, they would use `manuskript_pt_BR.ts`. Let's go with that!

**Comment by olivierkes** [comment] 2017-11-23 18:46
@FTMolina, I updated `manuskript.pro` in `develop`. 

So if you've started working:

- Save your work
- Update your repo (`git pull`)
- Run `pylupdate5 -noobsolete i18n/manuskript.pro`
- Open QT Linguist, and your previous work will be here, as well as all new strings

Thanks :)

**Comment by olivierkes** [comment] 2017-12-04 12:45
Hey @FTMolina,
Are you still working on that translation?
No pressure, just to know how things are :)
++

**Comment by FTMolina** [comment] 2017-12-13 13:27
Hi, sorry for being so quiet. I spent some time in the beach and now have to dedicate some time to college. But I plan to resume work this week.

So far everything is fine. I didn't have any problems with qt linguist or the translation itself. It's not a difficult job ad I plan finishing it soon

**Comment by FTMolina** [comment] 2017-12-27 20:13
Great news guys. After some weeks of intense college work, I got some time for the translation. It is done, i just want to revise it a little to guarantee its quality.

**Comment by marvson** [comment] 2017-12-28 16:13
I just downloaded Manuskript and wanted to translate to "pt-br" as well. Since you finished it I can help to revise it. @FTMolina

**Comment by FTMolina** [comment] 2018-01-02 12:43
Great. Im new to this. what do I do to send you my translation?

**Comment by pindarogb** [comment] 2018-07-25 22:18
Hey all, I have open translate to ptBR, here:
https://hosted.weblate.org/projects/manuskript/translations/pt_BR/

Soon will ready to be added to source code.

att

**Comment by gedakc** [comment] 2018-07-30 16:20
@FTMolina and @pindarogb it appears that we might have two people working on a translation so there might be duplication of effort.

In answer to @FTMolina the next step in the translation process according to @olivierkes link [Wiki - Translate Manuskript](https://github.com/olivierkes/manuskript/wiki/Translate-Manuskript) was to provide the `.ts` file either via an attachment or a pull request.

When someone has a translation ready, please post it and I will try to figure out how to have the translation included.

**Comment by pindarogb** [comment] 2018-08-01 11:12
@FTMolina  and @gedakc 

Good Morning
I started translating into portuguese from brazil because there was no translation in weblate, as the post from @Ftmolina is from November 2017, having spent more than six months, I figured it would not start, because it did not open any translation there.

But without intending to harm the FTmolina work, I am doing the translation.

By my calculations, I'm already 80% ready.
I'm even able to test the Manuskript.
see screenshot below.

![image](https://user-images.githubusercontent.com/41213070/43518427-718fd218-9562-11e8-9713-26780d7a24d6.png)

**Comment by gedakc** [comment] 2018-08-01 15:59
I think we are all working towards improving Manuskript so hopefully no offense is taken.  Since we work on our own spare time progress is often sporadic.

I'm new to Manuskript translations, but will do my best to incorporate the **pt_BR** translation when it is available.

**Comment by FTMolina** [comment] 2018-08-01 18:11
Hi guys. I'm having troubles with my computer. SInce pindarogb's translation is almost ready I think it would be better for the project to use his version.

**Comment by pindarogb** [comment] 2018-08-02 02:08
@FTMolina here you can write your contribution:
https://hosted.weblate.org/projects/manuskript/translations/pt_BR/

Onde eu estou fazendo a tradução. Um pouco cada dia.

**Comment by pindarogb** [comment] 2018-08-04 01:54
Translation on is all done 100%: 
https://hosted.weblate.org/projects/manuskript/translations/pt_BR/

Now tests and corrections.

**Comment by pindarogb** [comment] 2018-08-04 02:07
@olivierkes and @gedakc 

I found somes word, into Manuscript, but not on: https://hosted.weblate.org/projects/manuskript/translations/pt_BR/, for translate.

All word of submenu "Format" on menu Edit, all word of submenu of "Format" too, are not available to translate. See below:

![image](https://user-images.githubusercontent.com/41213070/43671517-fc954486-9771-11e8-84c7-c51d098bd057.png)

**Comment by pindarogb** [comment] 2018-08-04 02:12
The same problem of lack of words happened with the Spanish.
![image](https://user-images.githubusercontent.com/41213070/43671558-b7fa9820-9772-11e8-93ec-e8820c53dc86.png)

**Comment by gedakc** [comment] 2018-08-04 14:57
@pindarogb, can you create make the changes that will enable the text strings you mentioned to be translatable?

The changes to make the strings translatable should be in a new Pull Request that is separate from this on.

**Comment by gedakc** [comment] 2018-08-06 17:38
@pindarogb, could you check the **develop** branch to see if I have correctly included your current translation work?

I also updated the `*.ts` files with the current translatable strings from the source code.  These updates have been pushed to the **develop** branch.  I think that weblate should automatically pick up these changes, but I can't be sure because I'm not sure how @olivierkes configured weblate for Manuskript.

**Comment by gedakc** [comment] 2018-08-07 16:28
I have confirmed that the **Edit -> Format** menu entries are not translated when using languages other than English, such as Russian.

To help address this issue I updated the `*.ts` translation source files.

I can confirm that the **Edit -> Format** menu strings are now in the **develop** branch `*.ts` files.  For example _Superscript_ can be found in the [i18n/manuskript_pt_BR.ts](https://github.com/olivierkes/manuskript/blob/0d84202da61db3ea4727dcb4a4603841051183d9/i18n/manuskript_pt_BR.ts#L1396) file and it is marked as *unfinished*.

Unfortunately these updated `*.ts` files have not automatically been picked up by weblate.  Further I do not appear to have permission to push these updates to weblate.  :-(

I have emailed @olivierkes requesting an update.

**Comment by gedakc** [comment] 2018-08-14 15:14
Closing this issue so that the work to-date is included in the CHANGELOG.md file for when I create the next official release (soon).

**Closed by gedakc** 2018-08-14 15:14 UTC
