### ISSUE TITLE
buttons without icon

### ISSUE THREAD

**Issue by koliseo** [olivierkes/manuskript#542] opened 2019-03-29 14:04 UTC
Buttons that change view of writing panel between text, tree or tags (don't know the exact words in English, I use spanish language) appear withou icon, just a blank sqhare button.
![Captura de pantalla -2019-03-29 15-02-24](https://user-images.githubusercontent.com/4547822/55238039-d745db00-5233-11e9-9dac-49fe4b06ac95.png)

**Comment by koliseo** [comment] 2019-03-29 14:06
I forget to say I'm using Linux Mint 19.1 Mate with dark theme

**Comment by koliseo** [comment] 2019-03-29 14:10
Ah... in left panel are missing two icons on "Personajes" and "Esquema"

**Comment by gedakc** [comment] 2019-03-29 15:30
Thank you for providing the screen shot with the issue report.

I can see that the navigation menu icons are also incorrect.  This issue was reported previously with Linux Mint and the Cinnamon desktop.  It would appear that the issue also occurs on Linux Mint with the Mate desktop.

Closing this as a duplicate of [Issue 498- Inconsistent / missing navigation menu icons on Linux Mint](https://github.com/olivierkes/manuskript/issues/498).

**Closed by gedakc** 2019-03-29 15:30 UTC
