### ISSUE TITLE
Crash on Linux Mint 21.1 (Cinamon)

### ISSUE THREAD

**Issue by Robert-Jesteburg** [olivierkes/manuskript#1116] opened 2023-01-15 11:51 UTC
Manuskript version is 0.12.0-1. It's a fresh install from yesterday and it's the first time I start the tool. When it didn't come up, I tried to start from the shell and got the following error:

RITICAL> An unhandled exception has occurred!
Traceback (most recent call last):
  File "/usr/bin/manuskript", line 30, in <module>
    main.run()
  File "/usr/share/manuskript/manuskript/main.py", line 292, in run
    app, MW = prepare(arguments)
  File "/usr/share/manuskript/manuskript/main.py", line 171, in prepare
    from manuskript.mainWindow import MainWindow
  File "/usr/share/manuskript/manuskript/mainWindow.py", line 23, in <module>
    from manuskript.models.worldModel import worldModel
  File "/usr/share/manuskript/manuskript/models/worldModel.py", line 11, in <module>
    from manuskript.ui import style as S
  File "/usr/share/manuskript/manuskript/ui/style.py", line 36, in <module>
    highlightLight = F.mixColors(highlight, window, .3)
  File "/usr/share/manuskript/manuskript/functions/__init__.py", line 197, in mixColors
    return QColor(r, g, b) if not fromString else QColor(r, g, b).name()
TypeError: arguments did not match any overloaded call:
  QColor(Qt.GlobalColor): argument 1 has unexpected type 'float'
  QColor(int): argument 1 has unexpected type 'float'
  QColor(QRgba64): argument 1 has unexpected type 'float'
  QColor(Any): too many arguments
  QColor(): too many arguments
  QColor(int, int, int, alpha: int = 255): argument 1 has unexpected type 'float'
  QColor(str): argument 1 has unexpected type 'float'
  QColor(Union[QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'

I have been using this great tool for a while and would love to continue my project...

Sincerely,
Robert

**Comment by Robert-Jesteburg** [comment] 2023-01-15 11:57
Please feel free to contact me if additional information is required.

**Comment by marosoft** [comment] 2023-01-15 12:27
To me it looks like a mismatch between version of Qt and Manuskript.
Any reason as to why you are using version 12 over 14?

Might be a good idea to show a proper error when a not supported At version
is installed with information what to do.

**Comment by TheJackiMonster** [comment] 2023-01-15 14:22
It's actually an issue with newer Python versions changing their behavior when it comes to implicit type casting in function attributes. This is fixed however in newer versions of Manuskript. So on Linux Mint I would recommend using the flatpak version of Manuskript which will automatically update and use the versions of dependencies matching with the ones required by latest application changes.

You can still choose to use the .deb package from newer releases. But for once you would need to update them manually each time there is a new release and second such an incompatibility could happen at any later time as well when your distro updates some packages. So essentially it's an issue that your distro does not update its repository properly when it comes to Manuskript.

Hope this helps.

**Comment by TheJackiMonster** [comment] 2023-01-15 14:24
Closed as duplicate of #1043.

**Closed by TheJackiMonster** 2023-01-15 14:24 UTC
Labels: duplicate

**Comment by Robert-Jesteburg** [comment] 2023-01-15 17:51
Thank you very much, installing the flatpak version solved the problem.
You're quite fast in answering, thanx a lot!
