### ISSUE TITLE
Instant crash when starting 0.11.0 on Windows: ValueError: invalid literal for int() with base 10: '\x00'

### ISSUE THREAD

**Issue by NoCodeForOldMen** [olivierkes/manuskript#794] opened 2020-08-18 13:43 UTC
Hi,
don't know why it crashes, since I cannot remember having done anything different. I have looked at the other threads but couldn't find a solution either.
System: Windows 10.
Language: German (I saw that someone had a problem in an earlier version)
I have used the programm for a few days. My projects is opened on startup.
information from cmd:

> Debug: Web rendering engine used: QWebView
> Running manuskript version 0.11.0.
> Preferred translation: ['de-DE', 'en-US'] (based on available ui languages)
> Loaded translation: manuskript_de_DE.qm
> Traceback (most recent call last):
>   File "manuskript\ui\welcome.py", line 86, in showEvent
>   File "manuskript\mainWindow.py", line 572, in loadProject
>   File "manuskript\mainWindow.py", line 861, in loadDatas
>   File "manuskript\loadSave.py", line 58, in loadProject
> ValueError: invalid literal for int() with base 10: '\x00'

I haven't found a solution by going for other people with the 'ValueError' problem.
I tried opening the project through cmd directly like in another thread but it didn't work - my error message is a bit different.

manuskript.exe C:\Manuscript Buchsoftware\manuskript-0.11.0-win32\manuskript\Gesammelte Notizen.msk

(Gesammelte Notizen is my projects name, 'collected notes', I don't see a difficult letter here and I had no problem in the last few days.
Either way this way the output in cmd is still the same as above, so no luck.

**Comment by DarkinKimiroAV59** [comment] 2020-08-26 10:01
hello.

I also have the same problem and the only solution I had unfortunately found was to delete my project file so that the software would unlock it again, even though I had done the famous "Uninstall/Reinstall the software" while keeping my file aside thinking that it was the software that had bugged.

Anyway, the only thing I know is that I don't have access to my project anymore and that it bothers me a lot because of the work I went through on it, otherwise I had time to make a screenshot on the problem in question.

Thanks in advance to the one who will find the solution to this rather annoying problem ^^"

![Screenshot_14](https://user-images.githubusercontent.com/47459451/91290259-b15b9780-e793-11ea-80ee-cbc5ada97f0e.png)

**Comment by NoCodeForOldMen** [comment] 2020-08-26 12:05
I could easily access my project, what I lost was time but not data: 
in the installation file system of Manuskript was a folder with the name of my project (in my case C:\Manuskript\Gesammelte Notizen) and inside was a sole folder: 'outline'.
Inside were more folderas: all my project's chapters, from 00 to 42, with their respectable names. When I open one chapter-folder I have at least two files: one or more of .md and one .txt file.
The latter is useless, but the .md files are the ones where the written stuff is and they can be opened with the winows built-in editor (and probably any similiar program).


So at least you can recover your project in case you still have the folder (there are ways to get deleted data back in case it's not even in your waste bin).

**Comment by RiderExMachina** [comment] 2020-10-06 03:55
Looking at the code, I have an idea as to what the issue is, but I need to know if you still have the file(s), as it works okay for me on Linux. If you do, open the file(s) up in an archive utility (like 7-zip) and see if you have a file titled MANUSKRIPT or VERSION. I need to know what the number is inside of that file is as well, so open the file in Notepad and paste that here.

**Comment by TheJackiMonster** [comment] 2021-02-22 00:42
@NoCodeForOldMen Your original problem is related to the file access of the .msk file which is probably empty in your case. So it will read an ending zero instead of a version number to parse. I can add a work-around to use a different version as default and not crash but for transparency this should include a warning or similar that loading your project could fail or delete data in worst case.

**Comment by TheJackiMonster** [comment] 2021-02-22 01:21
This seems to be a duplicate of #776.

**Closed** 2021-02-22 01:21 UTC
Labels: bug, duplicate
