### ISSUE TITLE
[Feature Request] Import character or scene photos

### ISSUE THREAD

**Issue by darrelwright** [olivierkes/manuskript#214] opened 2017-11-14 04:14 UTC
Can I import photos and/or images and attach them to either characters or scenes?

**Comment by olivierkes** [comment] 2017-11-14 07:45
Will be done in the future :)

**Comment by darrelwright** [comment] 2017-11-14 07:48
Hey, thanks for answering all my questions (even if they're not what I'd like hear :)). I appreciate what you do!

**Comment by olivierkes** [comment] 2017-11-22 09:00
BTW, this is a duplicate of #22. Honor to elder issues, I close this one to centralize discussion in one place.

**Closed by olivierkes** 2017-11-22 09:00 UTC
Labels: duplicate
