### ISSUE TITLE
Two Windows instead of one

### ISSUE THREAD

**Issue by Eusorph** [olivierkes/manuskript#635] opened 2019-09-10 13:06 UTC
On my laptop, when I open Manuskript, two windows open: one is the main window, and the other what I think is the debug window. Manuskript would look much more professional if it opened only its main window.
![Two windows](https://user-images.githubusercontent.com/30339709/64616275-8a6a5100-d3dc-11e9-9e74-e3b3a6be8714.jpg)

**Comment by gedakc** [comment] 2019-09-10 15:43
Please search for an existing issue before opening a new issue.

Closing issue as a duplicate of issue #327.

**Closed by gedakc** 2019-09-10 15:43 UTC

**Comment by Eusorph** [comment] 2019-09-10 17:13
Sorry. I did, but probably with the wrong search words.
