### ISSUE TITLE
Crash on create - Linux Mint 18

### ISSUE THREAD

**Issue by scumop** [olivierkes/manuskript#91] opened 2017-04-15 04:07 UTC
Followed source install instructions, installed dependencies, etc.
Manuskript starts, gives nice startup screen.
I want to create a new story, so click [Create] button.
File dialog opens.
I nav to another folder, type in a name (with or without the .msk extension), click [Save]
and kaboom - closed and gone.

Program output in shell:
```
grantr@wolf ~/Software/manuskript $ bin/manuskript &
[1] 11620
grantr@wolf ~/Software/manuskript $ Warning: failed to load translator for locale en_CA...
Traceback (most recent call last):
  File "/home/grantr/Software/manuskript/bin/../manuskript/ui/welcome.py", line 159, in createFile
    self.loadDefaultDatas()
  File "/home/grantr/Software/manuskript/bin/../manuskript/ui/welcome.py", line 344, in loadDefaultDatas
    t = [i for i in self.templates() if i[0] == self.template[0]]
  File "/home/grantr/Software/manuskript/bin/../manuskript/ui/welcome.py", line 344, in <listcomp>
    t = [i for i in self.templates() if i[0] == self.template[0]]
IndexError: list index out of range
Fatal Python error: Aborted

Current thread 0x00007f41f2c01700 (most recent call first):
  File "/home/grantr/Software/manuskript/bin/../manuskript/main.py", line 72 in launch
  File "/home/grantr/Software/manuskript/bin/../manuskript/main.py", line 63 in run
  File "bin/manuskript", line 13 in <module>

[1]+  Aborted                 bin/manuskript
```

If I try to open a sample project, it works. Just does want to create a new one.

Version info:
```
grantr@wolf ~/Software/manuskript $ git log | head -n 4
commit efedde93eee6115879e5f15a16047d9c009fc7e6
Merge: d579659 574c144
Author: Olivier <olivier.keshavjee@gmail.com>
Date:   Tue Dec 13 08:20:26 2016 +0100
```

**Comment by olivierkes** [comment] 2017-04-17 16:43
Duplicate of #44 . (please do search in past issues before posting, I got this one like 10 times already :p )

Either double-click in one of the template on the left and then customize it to your need, before clicking Create.
Or much better: download the develop branch here on git, and run it the same way (since you already installed all the dependencies, that's easy).

**Closed by olivierkes** 2017-04-17 16:43 UTC
Labels: bug
