### ISSUE TITLE
Translation regression in plot meta step

### ISSUE THREAD

**Issue by magicvince** [olivierkes/manuskript#466] opened 2019-02-02 12:42 UTC
In the version 0.8 the translation of the different items of stage resolution is now only in english even I set up manuskript in french. In my old stories the french expression still appear, but if I want to change, I can only change to english expression.

Dans ma version 0.8 (à partir du .deb), les étapes de réseolution de l'intrigue ne sont proposées qu'en anglais bien que j'ai paramétré Manuskript en français (au besoin j'ai activé mon accès à weblate pour contribuer à la traduction).
ps: je maintiens d'ailleurs ma "request" pour cette fonctionnalité: pouvoir ajouter des modèles personnalisés de résolution d'enquête.

**Comment by gedakc** [comment] 2019-02-02 16:34
Can you describe the steps to reproduce the problem, and perhaps provide a screen shot or two?

Currently I do not understand the what the problem is in this report.

**Comment by magicvince** [comment] 2019-02-02 18:11
In the plot manager, for each plot I define steps via meta. In the previous version the item were translate in my locale language (french).  If I create a new story, the meta menu are not translate. If I load an old story, the meta of each step are in french, but if I want to change them, the menu of meta are also in english.

**Comment by gedakc** [comment] 2019-02-03 17:37
What Operating System are you using?

So far I have been unable to reproduce the issue.  Following are the steps I used.

1. Set language to French.

       export LANGUAGE=fr_FR:fr

2. Run Manuskript
3. Create a new **Novel**
4. Create a new **Plot**
5. Create 4 new **Plot steps** and set **Meta** on each.
6. Screen shot of Plot pane with **Meta** values in French.

![manuskript-plot-resolution-french](https://user-images.githubusercontent.com/10405019/52180132-95eaff00-279f-11e9-9958-4534ca4c38e2.png)

**Comment by magicvince** [comment] 2019-02-03 18:22
As I could see with my screen shot the translation is incomplete. My Manuskript is setting up with Fr; (in config file : applicationTranslation=manuskript_fr.qm
![manuskript-plot01](https://user-images.githubusercontent.com/627273/52180621-f2bed780-27e8-11e9-8a7b-c3fc0c9cb1ea.png)
![manuskript-plot02](https://user-images.githubusercontent.com/627273/52180622-f2bed780-27e8-11e9-9aa6-f424f37d15a8.png)

**Comment by gedakc** [comment] 2019-02-03 18:30
My bad.  I was running the **develop** git branch, and not the **master** branch which currently represents the 0.8.0 release.

This bug is already resolved in the **develop** branch which will be include in the next release of Manuskript.

Marking this bug as a duplicate of issue #411.

**Closed by gedakc** 2019-02-03 18:30 UTC
