### ISSUE TITLE
[Feature Request] Changing default settings

### ISSUE THREAD

**Issue by Nasgarath** [olivierkes/manuskript#724] opened 2020-01-27 02:49 UTC
I have poor eye sight, so the default value of size 10 is hard for me to read. No problem, I can easily change that. Except, when I start a new project, it goes back to the default and I have to change it again. Full screen mode doesn't have that problem, though, since you can save your settings into a personal theme, which is awesome.

I can think of two ways to do this:

1) Make it possible to change the default values (they could be saved in a theme too, like with full screen mode).
2) Make it possible to save your settings into template files that could be reused in future projects.

There are probably other ways this could be done, in fact I'm pretty sure I'd thought of another but it's slipped my mind now. But anyway, you get the idea ;)

**Comment by obw** [comment] 2020-01-27 09:27
Go to the Edit Menu -> Settings, first Tab you have your font size selector!

Also, under Views -> Editor you can also select Font and fontsize for the Editor...

**Comment by Nasgarath** [comment] 2020-01-27 15:22
> Go to the Edit Menu -> Settings, first Tab you have your font size selector!

This affects the menus and other system messages, but none of the texts I write.

> Also, under Views -> Editor you can also select Font and fontsize for the Editor...

Yes, but my point is that changes made here are not persistant. If I use that to set font size to 20, for instance, when I start a new project the size goes back to 10.

My suggestions above are ways to make it possible for the user to change the *default* values rather than just the current ones, if that makes sense.

Another way to do it would be to just have Manuskript remember and reuse the latest values (like it does on startup of a new project).

**Comment by TheJackiMonster** [comment] 2021-02-22 22:45
I think this is a duplicate of #337. So I would close this issue.

**Closed by TheJackiMonster** 2021-02-22 22:45 UTC
Labels: duplicate, enhancement
