### ISSUE TITLE
[bug] List index out of range (detailed character info)

### ISSUE THREAD

**Issue by tron1221** [olivierkes/manuskript#914] opened 2021-08-10 06:46 UTC
Hi, I created a new project, added one character. Then I add detailed information about it. 
The first string is added successfully, but when you try to add a second string an error occurs:
"
An unhandled exception has occurred!
Traceback (most recent call last):
  File "manuskript\models\characterPOVModel.py", line 17, in filterAcceptsRow
  File "manuskript\models\characterModel.py", line 139, in pov
  File "manuskript\models\characterModel.py", line 124, in character
IndexError: list index out of range
CRITICAL> An unhandled exception has occurred!
Traceback (most recent call last):
  File "manuskript\models\characterPOVModel.py", line 17, in filterAcceptsRow
  File "manuskript\models\characterModel.py", line 139, in pov
  File "manuskript\models\characterModel.py", line 124, in character
IndexError: list index out of range
"
Versions:
manuskript 0.12.0
python 3.8.9
PyQt 5.15.4
Qt 5.15.2
Windows 10

**Comment by tron1221** [comment] 2021-08-10 07:09
The number of characteristics added without errors is equal to the number of characters. Most likely, the search is performed in the wrong list (the list of characters instead of the list of character details).

**Comment by TheJackiMonster** [comment] 2021-08-10 09:07
This seems to be a duplicate of #908 and #843 which were already fixed for the next release. So I will close this issue here.

**Closed** 2021-08-10 09:07 UTC
Labels: duplicate
