### ISSUE TITLE
Crashes when creating new project

### ISSUE THREAD

**Issue by rshamrock** [olivierkes/manuskript#60] opened 2016-11-21 23:16 UTC
I clicked on "Novel," then the Create button. It  brings me to the save dialog. I enter a name, and when I press Save, the program crashes immediately. I am on Windows 10 (all current updates), and I've tried changing compatibility mode to Windows 7 and other versions (none worked). This also happens if I try to create a new Empty Fiction.

I also tried running the program as administrator, and that didn't work.

(Not sure if this is related, but when I run it, I get this in the terminal window: "Warning: failed to load translator for locale en_US...")

I used Camtasia to record the terminal window. Here's what I could see it reporting as it crashed:
```
Traceback (most recent call last):
  File "manuskript\ui\welcome.py", line 159, in createFile
  File "manuskript\ui\welcome.py", line 344, in loadDefaultDatas
  File "manuskript\ui\welcome.py", line 344, in <listcomp>
IndexError: list index out of range
```

**Comment by olivierkes** [comment] 2016-11-22 06:19
This might be a duplicate of #44.
Try double-clicking on "Novel" before saving (the UI must change).

**Closed** 2016-11-29 10:17 UTC
