### ISSUE TITLE
Recent Files List

### ISSUE THREAD

**Issue by siliconserf** [olivierkes/manuskript#604] opened 2019-07-09 20:47 UTC
Where does Manuskript store the information on recently opened files? This isn't a bug report, mostly I'm just curious. The subject came us as I want Manuskript to "forget" about some archive copies of files which I opened recently. Now having them continue show up is clutter.

**Comment by gedakc** [comment] 2019-07-09 20:56
The answer can be found under [answered questions](https://github.com/olivierkes/manuskript/issues?utf8=%E2%9C%93&q=+label%3Aquestion+) in the wiki.

Marking this as a duplicate of [Where are the configuration settings stored](https://github.com/olivierkes/manuskript/issues/446#issuecomment-453764119).

**Closed by gedakc** 2019-07-09 20:56 UTC
