### ISSUE TITLE
Plot-step summary disappearing and not being saved!

### ISSUE THREAD

**Issue by AndrewDemidov** [olivierkes/manuskript#1008] opened 2022-01-31 15:23 UTC
Choosing simply another plot step or creating a new one erases completely whatever has been entered into the "Summary" field! **Not** just clears the area, because it's a new step.

I've attempted writing a summary from one plot step, created another one... returned to the first plot step... Where is my summary? Attempting anew... Selecting the other plot step... then back to the first one... It's gone!

That's clearly incorrect! Although the summary field should be cleared/changed when moving to another step, each step must remember its summary!

Seriously, though, I can't plot like that! How is it no one's noticed???

**Comment by TheJackiMonster** [comment] 2022-01-31 19:58
> Seriously, though, I can't plot like that! How is it no one's noticed???

I assume many people don't use the plot steps because of the lacking ability to reference them specifically (#983).

It's now files as bug and should get fixed in the future.

**Comment by AndrewDemidov** [comment] 2022-05-24 15:12
Update:

Just forked from "develop" branch to see, what I could do. The code needs documenting, by the way.
For a new empty project the latest v0.13.1 of "Manuskript" doesn't appear to behave the way described in this bug report.
However the behaviour is **still** there for an existing project!
But that _same_ existing project, when opened in "Manuskript" from "develop" branch, behaves correctly!
I've no idea, what caused the issue... If it's elusive, further research must be conducted. But, if some commit since the release has actually fixed the bug, then, well... We must avoid this in the future!

**Comment by TheJackiMonster** [comment] 2023-02-10 21:52
So I can't reproduce it in the current version as well. I'll close this as fixed, I assume.

**Closed by TheJackiMonster** 2023-02-10 21:52 UTC
Labels: bug
