### ISSUE TITLE
Crashes when trying to create or open the project

### ISSUE THREAD

**Issue by snowydad** [olivierkes/manuskript#99] opened 2017-05-16 08:57 UTC
Create project:
1. Run EXE
2. Select Create
3. Create folder for project
4. Click Save
5. Crash (and that folder (3) is not created)

Win 7 64

**Comment by gedakc** [comment] 2017-05-16 15:54
Thanks for your interest in Manuskript.

This is a known issue with version 0.3.0 and also the current git master -- see issue #37.

I believe the problem is resolved in the git source code repository on the **develop** branch.  At least it is for me on GNU/LInux.

If you can, clone the git repository and checkout the **develop** branch and then try running manuskript.

**Comment by olivierkes** [comment] 2017-05-23 14:56
Yep, duplicates of #44. See workaroud there, or do as @gedakc wisely says :)

**Closed by olivierkes** 2017-05-23 14:56 UTC
Labels: bug
