### ISSUE TITLE
Export crashes, because of encoding to 1250

### ISSUE THREAD

**Issue by lechbaczynski** [olivierkes/manuskript#331] opened 2018-03-26 18:29 UTC
Windows, version 0.6.0

While exporting to plain text (not pandoc):

  File "manuskript\ui\exporters\exporter.py", line 107, in export
  File "manuskript\exporter\manuskript\plainText.py", line 102, in export
  File "c:\python34\lib\encodings\cp1250.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 3968-396
9: character maps to <undefined>

Why doesn't it export to utf 8?

**Comment by lechbaczynski** [comment] 2018-04-06 08:48
This happened in downloaded compiled windows version of 0.60
This did not happen in current devel , run on windows from sources.

**Comment by gedakc** [comment] 2018-04-06 15:38
Thanks for testing reporting back that the problem does not exist with the current **develop** branch.

When the next official release is created, the **develop** branch will become the 0.7.0 release.  As such I will close this report as a bug and tag it with the 0.7.0 milestone.

**Comment by lechbaczynski** [comment] 2018-04-07 06:57
Okay, but anyway, why not use utf8?

Editor of Manuskript - good:
![obraz](https://user-images.githubusercontent.com/1127623/38452267-e9a346ae-3a40-11e8-9b16-a68e0e204927.png)

Exported file - bad (Sublime text, default):
![obraz](https://user-images.githubusercontent.com/1127623/38452270-f2cf6f28-3a40-11e8-902d-4170987834d5.png)

But if  I open it with windows 1250 encoding it looks okay:
Sublime text, opening the file explicitly in 1250:
![obraz](https://user-images.githubusercontent.com/1127623/38452297-81990a2a-3a41-11e8-9514-6e6014481793.png)


Windows Notepad seems to use 1250 by default:
![obraz](https://user-images.githubusercontent.com/1127623/38452291-6e0a97d0-3a41-11e8-9f22-07ae77ebcb5e.png)

**Comment by lechbaczynski** [comment] 2018-04-07 07:04
I am sorry, it seems that I was mistaken. The error still exist, 
but only if I use some characters that cannot be encoded in windows 1250
I exported whole short story with just Polish letters, and it was okay.
But If I insert anything else:


The editor in Manuskript:

![obraz](https://user-images.githubusercontent.com/1127623/38452316-1a0c8f7a-3a42-11e8-8ace-3bf85b301f2b.png)


The export preview:

![obraz](https://user-images.githubusercontent.com/1127623/38452320-2d55e310-3a42-11e8-8e61-2b9856976388.png)

The result after clicking export - crashes with:

manuskript\ui\exporters\exporter.py", line 107, in export
    F.export(self.settingsWidget)

manuskript\exporter\manuskript\plainText.py", line 102, in export
    f.write(content)

 File "C:\Python34\lib\encodings\cp1250.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 22-25: c
haracter maps to <undefined>

**Comment by lechbaczynski** [comment] 2018-04-07 13:35
Is it possible to reopen, or should I open another issue?

**Comment by gedakc** [comment] 2018-04-07 15:45
I thought Manuskript was using UTF-8.  Perhaps there is an invalid character in the project content?

I will re-open the issue.

It would help if you can post the steps to reproduce the error.

**Comment by gedakc** [comment] 2018-04-07 15:53
One suggestion is to check what language/encoding your operating system environment is set too.

In GNU/Linux this can be checked with the `locale` command.  For example on my kubuntu 16.04 computer the following is reported:

```
$ locale
LANG=en_CA.UTF-8
LANGUAGE=en_CA:en
LC_CTYPE="en_CA.UTF-8"
LC_NUMERIC="en_CA.UTF-8"
LC_TIME="en_CA.UTF-8"
LC_COLLATE="en_CA.UTF-8"
LC_MONETARY="en_CA.UTF-8"
LC_MESSAGES="en_CA.UTF-8"
LC_PAPER="en_CA.UTF-8"
LC_NAME="en_CA.UTF-8"
LC_ADDRESS="en_CA.UTF-8"
LC_TELEPHONE="en_CA.UTF-8"
LC_MEASUREMENT="en_CA.UTF-8"
LC_IDENTIFICATION="en_CA.UTF-8"
LC_ALL=
```

There should be a similar command in Windows that you can execute from the command prompt.

**Comment by lechbaczynski** [comment] 2018-04-07 21:04
There is systeminfo.exe , showing "locale" equivalent (and more), and it shows:

Ustawienia regionalne systemu:       pl;Polski
Ustawienia regionalne:               pl;Polski

(Which means: "Regional settings: pl;Polish" )

I think windows uses Win-1250 codepage by default for Central Europe.

How to reproduce:

Use Windows 7 
(maybe some other windows will have this problem too)

Write a text in editor (mine was a short story with 4 scenes)

Use some characters that cannot be encoded in 1250
(for example Arabic, Georgian etc - see my screensots in prevoius comment)

Export (F6)
Preview the export - should be okay.
When saving the export, the program crashes.

This happens both for compiled Win version and while using devel branch and that old python version and libs mentioned in documentation (about how to run Manuskript from sources on Windows).

**Comment by gedakc** [comment] 2018-04-07 22:17
From my understanding, Python picks up the language locale setting from the operating system environment.  This can be set within a shell or likely a Windows command prompt.

Are you using pandoc for export?

If so, then it appears that pandoc also expects UTF-8 input and output for the [character encoding](https://pandoc.org/MANUAL.html#character-encoding).  If not the pandoc suggests piping the input and output through `iconv`, which I'm guessing is not a tool available on Windows by default.

In the interest of learning more about the issue, would you be able to try setting your environment to a UTF-8 locale, typing in the text that causes the issue, and then export it?

**Comment by lechbaczynski** [comment] 2018-04-08 06:07
I suppose it is not so easy to set utf-8 locale in Windows. 
One can change language/regional settings, but not the code page:
https://superuser.com/questions/239810/setting-utf8-as-default-character-encoding-in-windows-7
http://blogmines.com/blog/how-to-change-system-locale-in-windows-7/

Also this is not something that typical user would be able to do, or even understand.

I know the concept of locale in unix/linux and changed locales there, but never encountered something similar in Windows (regarding encoding).


Also I get the same error, whether I choose plaintext or html or pandoc: latex , res, opml


Anyway, I made a simple fix, and now it works - see exported text file

![obraz](https://user-images.githubusercontent.com/1127623/38463874-d3c13b66-3b03-11e8-9b12-5d49b0193dba.png)

**Comment by gedakc** [comment] 2018-08-16 19:18
@lechbaczynski can you post some sample text that causes the crash?  
It should be text and not a picture.

The more I look at this issue the more I see that it is a complex issue with no single absolutely "correct" solution.

While searching the Internet I discovered:

- [Pandoc requires input and output to be in utf-8 encoding](https://pandoc.org/MANUAL.html#character-encoding).
- Trade-offs in [Processing Text Files in Python 3](https://python-notes.curiousefficiency.org/en/latest/python3/text_file_processing.html).

PR #331 changes the encoding of the exported file to be 'UTF-8'.  This is exactly what is expected for pandoc, but might not be what is intended for Manuskript's built-in export.  The pandoc export is based on the built-in export and hence changes to the base built-in affect both.  This might not be desired when the user expects the export to be in the default locale for the operating system.

**Comment by gedakc** [comment] 2018-08-17 16:05
Thank you @lechbaczynski for the sample text.  With this sample text I was able to confirm the compile/export crash on Windows 10.  The crash occurred when using the manuskipt built-in *Plain text* compile/export.

I would have thought that Manuskript would also have crashed when saving the entire project.  However when I save the project manuskript continues to work.  Also if I restart Manuskript I can load the project and the sample text is there.  The project save functionality works both when saved as a single *zip* file, and when not saved as a single *zip* file (for example folders and files).

So I investigated further and discovered the following project "open for write" calls:

Single Zip files:
[`zf = zipfile.ZipFile(project, mode="w")`](https://github.com/olivierkes/manuskript/blob/97e4679d83313f367b8b65f4e865a4bdec6bb984/manuskript/load_save/version_1.py#L316)

Multiple folders and files:
[`open(filename, "w", encoding='utf8') as f`](https://github.com/olivierkes/manuskript/blob/master/manuskript/load_save/version_1.py#L378)

Hence Manuskript **is using UTF-8** when saving plain text files (not binary) which is what you suggested!

Strangely I did not observe a statement to `import codecs` or `import io` in the [` manuskript/manuskript/load_save/version_1.py`](https://github.com/olivierkes/manuskript/blob/master/manuskript/load_save/version_1.py) file.  Perhaps one of the other imports includes either/or codecs or io themselves?

I will be away this weekend so plan to look at including your PR in some form next week.

**Comment by lechbaczynski** [comment] 2018-08-19 05:48
Hi :)

I didn't suggest saving was wrong, but exporting - this is why I added this simple, but working fix, to be able to use the program (export form it) -

import codecs
and
with open(filename, "w", encoding='utf8') as f:

in

exporter/manuskript/plainText.py


as in the commit and pull request.

I use my fork version of Manuskript now (with fixed export and characters counter at the bottom - another pull request, but denied because of screen space preservation)

**Comment by gedakc** [comment] 2018-08-21 16:44
I apologize for my explanation not being clear.

What I meant to say is that because Manuskript does save project files in UTF-8, it makes perfect sense that the compile option should also save the exported files in UTF-8.

Your PR does do this.  Further because there is no read or readline calls, there should be no issue regarding whether `codecs` or `io` is used as the import library.

Next I will test your PR to ensure that it works on my Windows VM too.

**Comment by gedakc** [comment] 2018-08-21 17:02
Closing this issue as I've confirmed that the proposed fix does indeed resolve the issue.

**Closed by gedakc** 2018-08-21 17:02 UTC
Labels: bug
