### ISSUE TITLE
Manuskript Crashes on Project Open

### ISSUE THREAD

**Issue by StacyWV** [olivierkes/manuskript#741] opened 2020-02-24 17:17 UTC
I created a project, was using it without issue, now, starting about 2 days ago, whenever I try to open the project it immediately crashes the program.

I can only assume something happened on that last save (when it still worked) that corrupted the file, as it does the same thing when I try to open the project from 3 different computers / installs. A Win10 PC, a Mac, and a Chromebook (linux).  I also tried an older version of Manuskript  –  same issue.

Here's what I'm getting in the cmd window:

> Traceback (most recent call last):
>   File "manuskript\ui\welcome.py", line 163, in openFile
>   File "manuskript\mainWindow.py", line 572, in loadProject
>   File "manuskript\mainWindow.py", line 861, in loadDatas
>   File "manuskript\loadSave.py", line 58, in loadProject
>   File "c:\python34\lib\codecs.py", line 319, in decode
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 10: invalid start byte

Is there any way to access the data in the project file otherwise  –  my mess-up was not having multiple backup copies, and now the work I did in my manuscript appears to be lost.  Any help would be appreciated!

**Comment by gedakc** [comment] 2020-02-24 17:38
By default Manuskript saves the project in a single file with the _.msk_ extension.  This file is a zip file that contains many folders and files.

However if you disabled **Save to one single file** under **Edit -> Settings -> General** then the _project.msk_ file will have an accompanying _project_ directory which contains the folders and files in plain text format (see [Using Manuskript to write a Fiction Novel - Tips](http://gedakc.users.sourceforge.net/display-doc.php?name=manuskript-novel-writing#t))

Assuming that you did not change the default settings you might try copying your project.msk file to project.zip and then try to unzip the file to gain access to the contents.

Are you using the latest 0.11.0 version of Manuskript?

**Comment by StacyWV** [comment] 2020-02-24 17:42
I was using 0.11.0  –  I don't believe I changed any default settings, all I have is the .msk file though, I don't see any directories with it though.  

Dang  –  when I change the extension to a zip it tells me it's invalid and I can't open / extract it.

**Comment by gedakc** [comment] 2020-02-24 17:47
That is unfortunate - it is never good to lose data.  :-(

You might check the size of the _project.msk_ file to see if it is large enough to contain your work to date.  If so there might be other options worth pursing like zip file repair tools.

**Comment by StacyWV** [comment] 2020-02-24 17:48
It's only 25kb  :(  I had about 9 chapters written, plus a few character profiles and places profiles... so I'm thinking it's just toast. *cry*

**Comment by StacyWV** [comment] 2020-02-24 17:52
WHen I try to run a zip repair on it... the repair software sees contents:

![image](https://user-images.githubusercontent.com/61427172/75177585-7c975680-5704-11ea-930a-2e40c3059297.png)

but when I try to open the zip after it still tells me it's invalid.... any ideas?

**Comment by gedakc** [comment] 2020-02-24 17:54
25kb compressed might expand to 75,000 characters or so when unzipped.  If it were me then I'd try some zip repair tools.

On GNU/Linux I'd use [zip from the command line](https://superuser.com/questions/23290/terminal-tool-linux-for-repair-corrupted-zip-files).  I'm unfamiliar with tools used to repair zip  files on Windows.

**Comment by gedakc** [comment] 2020-02-24 17:55
The image you uploaded looks promising for being able to recover at least a portion of your work.

**Comment by StacyWV** [comment] 2020-02-24 17:59
AHHH!!  GEDAKC YOU ARE MY HERO!

**Comment by StacyWV** [comment] 2020-02-24 18:00
I was able to repair the zip.... then can get in an open each chapter individually (the md file) with notepad and get them back..... YEEEEESSSS!!  :D  Thank you!!!

**Comment by gedakc** [comment] 2020-02-24 18:05
That is excellent news!  'Glad to hear you were able to recover your work.

It is possible that the project may open again in Manuskript if you copy the _project.zip_ file to _project.msk_.  Alternatively you might need to copy and paste the text contents into a new project.

It would help if we knew what caused the error in the first place.  We have had previous bugs with invalid characters see [issues search for "codec can't decode byte"](https://github.com/olivierkes/manuskript/issues?utf8=%E2%9C%93&q=is%3Aissue+codec+can%27t+decode+byte).  However I believe we resolved those specific issues.

**Comment by StacyWV** [comment] 2020-02-24 18:07
I will try to reopen it and see if it works, and if not, no biggie, I'm happy just to have the content back to copy into a new project! 🤣  I'll keep watch on it to see if anything funky happens again  –  most likely it was my excellent luck (sarcasm) with technology. LOL 

Thank you again!!

**Comment by gedakc** [comment] 2020-02-25 17:07
@StacyWV I will close this issue as you were able to recover at least a portion of your work.

If you discover what caused the issue (ideally a set of reproducible steps) then please feel free to re-open this issue so we can try to address the root cause.

**Closed by gedakc** 2020-02-25 17:07 UTC
