### ISSUE TITLE
Accent not working

### ISSUE THREAD

**Issue by Yattatux** [olivierkes/manuskript#105] opened 2017-05-27 16:35 UTC
Fedora 25 64-bit - manuskript-0.4.0-linux - accent doesn't work on UK layout.
I try to use: à - è - ì - ò - ù
It is impossible to use them in UK layout. **`** key doesn't work (the key on the left of 1 key)

accent á - é - í - ó - ú works fine instead (alt Gr + vowal key)

**Comment by gedakc** [comment] 2017-05-27 17:55
Would you be able to try to [Run Manuskript from Source Code on Linux](https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Linux)?

This would help to identify if the issue is with the _manuskript-0.4.0-linux.zip_ PyInstaller package.

**Comment by vinsifroid** [comment] 2017-08-02 20:33
Same problem here. I'm on Linux Mint 18.2 - manuskript-0.4.0-linux with a belgian layout.
My keys are working like é - è - à - ù
But when i try to do a combination of an accent + a vowel, it doesn't work. Like `´ + e` or `^ + o`
I did the installation and ran from Source Code

**Comment by gedakc** [comment] 2017-08-02 21:27
@vinsifroid.  Your post mentions using "manuskript-0.4.0-linux" which is the package file that includes the `manuskript` binary executable.  The package file is built with PyInstaller and according to @Yattatux has the accent not working issue.

> I did the installation and ran from Source Code

Or did you also try the steps listed in [Run Manuskript from Source Code on Linux](https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Linux)?

These steps would install the source code and invoke manuskript using the shell script `bin/manuskript`.

You can check whether the `manuskript` file is a binary executable or shell script with `file manuskript`.

Which `manskript` did you run (shell script or binary executable)?

**Comment by vinsifroid** [comment] 2017-08-03 08:42
I followed the instructions following way A in [Run Manuskript from Source Code on Linux](https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Linux) and thus by downloading `manuskript-0.4.0-linux.zip` on [this page](http://www.theologeek.ch/manuskript/download/).

It is a binary executable in folder `manuskript/manuskript`. If this help, i don't even have a `bin/` folder in my installation.

**Comment by gedakc** [comment] 2017-08-03 15:15
Thank you @vinsifroid for checking.  It appears you are running the binary executable.

It appears that you downloaded the binary package `manuskript-0.4.0-linux.zip`, and not the source code file `manuskript-0.4.0.zip` (note the missing _-linux_ in the file name).

Would you be able to to try running from the source code?

In the download section of [Run Manuskript from Source Code on Linux](https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Linux) the instructions try to make it clear to skip files with the Operating System name in them.

**BEGIN QUOTE**
Download an official **sources** release **zip** or **tar.gz** file.
Note that these are **NOT** the files with _-linux_, _-osx_, _-win32_, or _-windows_ in the filename.
**END QUOTE**

It would be a great help if you could try using the source code file and report your results here.

Thanks in advance,
Curtis

**Comment by gedakc** [comment] 2017-08-03 18:15
FYI:  It appears that we have two reports of this same accents not working problem.  This one for the 0.4.0 PyInstaller package, and issue #58 for the 0.3.0 PyInstaller package.

The 0.3.0 report indicated that the **develop** branch works which makes me think that the issue is with the release created with PyInstaller.  Perhaps it defaults to only one keyboard layout?

**Comment by gedakc** [comment] 2017-11-19 18:02
For users of Debian based GNU/Linux distributions, such as Ubuntu and Linux Mint, please try the `manuskript-0.5.0-1.deb` package to see if accents now work for you.

The package along with the instructions for installation can be found at:   
[SF - manuskript-0.5.0](https://sourceforge.net/projects/manuskript/files/manuskript/manuskript-0.5.0/)

**Comment by gedakc** [comment] 2017-11-20 22:53
For users of Fedora based GNU/Linux distributions please try the `manuskript-0.5.0-1.noarch.rpm` package to see if accents now work for you.

The package along with the instructions for installation can be found at:   
[SF - manuskript-0.5.0](https://sourceforge.net/projects/manuskript/files/manuskript/manuskript-0.5.0/)

**Comment by thoronaug** [comment] 2017-11-24 13:13
I confirm accents working from the .deb installer 0.5.0-1 too. I'm using Linux Mint 18.2 Sonya.
I've also tried running from precompiled (accents not working) and from source code (accents working).

Have you ever thought about releasing an appImage package or something similar? Maybe this solve the problems between platforms.

Greetings

**Comment by vinsifroid** [comment] 2017-11-25 09:22
I confirm as well that accent are working with .deb Installer 0.5.0-1, also using Linux Mint 18.2 Sonya 64 bits. It seems like only the precompiled code don't work with accents. I was using the source code until now and i never had the problem again.

**Comment by gedakc** [comment] 2017-11-25 17:24
Thank you @thoronaug and @vinsifroid for confirming that both the `.deb` package, and running from source code works.

For future releases we plan to create a `.deb` package for Debian based distros, and a `.rpm` package for Fedora based distros.

Due to the issues we've encountered with PyInstaller on various GNU/Linux distros, I think it makes sense to stop making Linux PyInstaller packages for future releases.

**Comment by thoronaug** [comment] 2017-11-28 22:08
It's me again. Now to confirm that accents are working perfectly with 0.5.0-1 .deb installer on BunsenLabs (64 bits), a Debian-based (not Ubuntu-based) distro.

Thank you so much for your help, your work, and, of course, for Manuskript.

**Comment by olivierkes** [comment] 2017-11-30 07:59
Thanks for reporting :)
Closing this.

**Closed by olivierkes** 2017-11-30 07:59 UTC
Labels: bug, packaging

**Comment by Yattatux** [comment] 2017-12-03 18:33
Hi, sorry for my delay.
I have tried Manuskript 0.6.0-1.rpm in Fedora 26 64 BIT, and accents work well.
Many thanks to gedakc and olivierkes for your work.

p.s. I talk about Manuskript in my free pdf book "Open Writing On Fedora 25", I love Manuskript, it is great. 👍 :)
