### ISSUE TITLE
Distraction Free Mode Opens in Different Display

### ISSUE THREAD

**Issue by BenjaminCecchetto** [olivierkes/manuskript#687] opened 2019-11-10 05:55 UTC
**Manuskript Version**: 0.10.0
**Python**: 3.7.3
**PyQt**: 5.12.1
**Qt**: 5.12.2
**OS**: Ubuntu 19.04
**Monitors**: Laptop as secondary display (monitor 1), external HDMI monitor as primary display (monitor 2).
**Problem**: The Manuskript window is on monitor 2. When I enter distraction free mode, either from pressing F11 or the fullscreen button on the bottom right, manuscript opens up distraction free mode on the laptop display (monitor 1)

**Comment by worstje** [comment] 2019-11-10 12:51
Where is your Manuskript window? I don't quite recall how the code works, but I _think_ it might be trying to put the distraction free environment on the same screen as the main window.

**Comment by BenjaminCecchetto** [comment] 2019-11-10 15:07
The Manuscript window is on the external display (monitor 2, primary
display) and it opens the fullscreen mode on the laptop window (monitor 1).

**Comment by TheJackiMonster** [comment] 2021-02-22 21:59
I would close this issue as duplicate of #456.

**Closed by TheJackiMonster** 2021-02-22 21:59 UTC
