### ISSUE TITLE
Run Manuskript from Source Code on Windows 10 

### ISSUE THREAD

**Issue by pindarogb** [olivierkes/manuskript#370] opened 2018-08-01 01:08 UTC
Hey, I clone project and change to develop, but before compile manuskript.exe not run. 
Prompt return the error:

**Debug: Web rendering engine used: QWebEngineView
This application failed to start because it could not find or load the Qt platform plugin "windows"
in "".

Reinstalling the application may fix this problem.
Fatal Python error: Aborted

Current thread 0x000020d4 (most recent call first):
  File "manuskript\main.py", line 18 in prepare
  File "manuskript\main.py", line 99 in run
  File "manuskript", line 13 in <module>**
I search on the web to solutions, but nothing.
I'm using theses softs on windows 10:
conda version : 4.5.4
conda-build version : 3.10.5
python version : 3.6.5.final.0
pyqt5

**Comment by pindarogb** [comment] 2018-08-01 01:11
Runing from source code is everything ok.
**bin> python .\manuskript**

**Comment by gedakc** [comment] 2018-08-01 16:00
Which `manuskript.exe` are you trying to run?

For the official Manuskript release for Windows, we create the `manuskript.exe` file using PyInstaller and the Manuskript source code on Windows XP (for maximum compatibility).  Any changes to the source code after creating `manuskript.exe` with PyInstaller will not be reflected in the running program.  If you are curious how we do this then see [Package Manuskript for Windows with PyInstaller](https://github.com/olivierkes/manuskript/wiki/Package-Manuskript-for-Windows-with-PyInstaller).

I'm assuming that you are **not** running the `manuskript.exe` created by PyInstaller.  If this is the case then running Manuskript from source code is the proper way to test changes to the code.

**Comment by gedakc** [comment] 2018-08-01 16:07
@pindarogb I noticed that you added translation instructions to the [Wiki - Run Manuskript from Source Code on Windows](https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Windows) guide.

These added translation instructions would fit better with the [Wiki - Translate Manuskript](https://github.com/olivierkes/manuskript/wiki/Translate-Manuskript).

Would you be able to move these added translation instructions to the latter location?

Thanks,
Curtis

**Comment by pindarogb** [comment] 2018-08-01 17:19
@gedakc you ask:
Which manuskript.exe are you trying to run?

I follow this tutorial - > https://github.com/olivierkes/manuskript/wiki/Package-Manuskript-for-Windows-with-PyInstaller

After compile source code... (pyinstaller --icon=manuskript.ico manuskript.spec)

I run manuskript.exe into manuskript\dist\manuskript\

**Comment by gedakc** [comment] 2018-08-01 20:29
> Sorry for my mistake

No worries.  It we did nothing then we'd never make a mistake.  :-)

Regarding the Windows PyInstaller package you are creating, I think the error might be caused by the newer version of PyQt5 or Python (3.4.4 versus 3.6.5).  I think that [issue #54 - Qt WebKit is deprecated](https://github.com/olivierkes/manuskript/issues/54) might be applicable, and you might try installing a version of QtWebEngine that matches the Python and PyQt5 versions.

**Comment by gedakc** [comment] 2018-08-11 14:47
@pindarogb any more questions on Windows 10 and PyInstaller?  If not we should close this issue.

**Comment by gedakc** [comment] 2018-09-11 15:59
Closing this issue as **invalid** as no further information has been provided.  Additionally the **invalid** tag will prevent the issue from showing up in the automatically generated CHANGELOG.md file.

**Closed by gedakc** 2018-09-11 15:59 UTC
Labels: packaging, windows
