### ISSUE TITLE
Cant create a new project using Ubuntu 16.10

### ISSUE THREAD

**Issue by turagittech** [olivierkes/manuskript#70] opened 2016-12-20 11:13 UTC
I tried out Manuskript in 16.10 and it appears to mostly function. The demo project opened fine. The application otherwise seems to run. 
I cannot, however, create a new project. I tried a number of times using different types of book and after I click on create nothing is in the folder to open.

Let me know what to do to find the culprit and I will gladly update this with additional info. Might be able to supply a patch if it's not too complex.

**Comment by olivierkes** [comment] 2016-12-20 14:45
I guess you're using 0.3.0? If so, this is a duplicate of #44. Please see that topic to find the workaround, or update to the develop branch.

**Closed by olivierkes** 2016-12-20 14:45 UTC
