### ISSUE TITLE
add suport Fountain fromat

### ISSUE THREAD

**Issue by Reaper10** [olivierkes/manuskript#111] opened 2017-06-07 23:42 UTC
add support Fountain format

https://fountain.io/
https://github.com/nyousefi/Fountain

**Comment by gedakc** [comment] 2017-06-08 17:37
Thank you @Reaper10 for you interest.

Currently Manuskript supports entering text such as fountain.

Were you looking for fountain syntax highlighting and a fountain export?

If so then this is already covered under the issue #32 request and hence this request could be closed.
If not, then please clarify what you are seeking regarding fountain.

**Comment by Reaper10** [comment] 2017-06-09 14:39
sorry I didn't on the fountain supported apps page. could you add support for Trelby , adobe story fade in celix,  movie magic screen writer, final draft? I would all so be nice to add the ability write comic scipts.

**Comment by gedakc** [comment] 2017-06-22 16:14
'Looks like this request is a duplicate.  The questions were asked in a separate issue.

**Comment by olivierkes** [comment] 2017-10-15 22:08
Duplicate of #32.

**Closed by olivierkes** 2017-10-15 22:08 UTC
Labels: enhancement
