### ISSUE TITLE
Some bugs in Windows XP and Ubuntu 15.1

### ISSUE THREAD

**Issue by ferranmarinramos** [olivierkes/manuskript#25] opened 2016-04-05 22:19 UTC
Hi to all!

I've detected some bugs in windows XP:
- Field "Epiphany" in Characters board doesn't saved.
- Don't load image for cards wallpaper.
- Field "Source of conflict" in World board doesn't active.
- In Redaction mode: It isn't stable, sometimes closes when changing from cards to text mode.
- Field "summary" in Plot board (Resolution steps) doesn't active. After complete this field, columns are very large. Impossible see fully.
- Not a bug, but a doubt: how use the heart icon in Characters board (field detailed infos).

In Ubuntu 15.1:

-Doesn't put accents on words.

Thanks for translation to spanish! :+1: 

Regards!

**Comment by olivierkes** [comment] 2016-04-05 22:42
Hi,

Thanks for reporting all of that.

Can you give me more details about the bug in redaction mode? When it closes, do you get an error message? And if so, what?

Also, about the accents missing in Ubuntu 15.1: do you get any error message in console? And are they missing in words you type, or in menus and such?

Thanks,

**Comment by ferranmarinramos** [comment] 2016-04-05 22:48
You're welcome.

No, it simply crash and closes. Doesn't appears an error message. I'm thinking: maybe when I work with an old document. In Ubuntu I've this problem when I type the words.

**Comment by olivierkes** [comment] 2016-04-07 15:24
When I'm talking about error message, I mean in the console. Not in a popup window.
Are you sure there is nothing?

**Comment by gedakc** [comment] 2017-06-05 17:48
Manuskript 0.4.0 was released on May 25, 2017, which fixes some of the problems mentioned in this issue report.  Ideally an issue report would contain only one problem so that it could be closed when the issue has been addressed.

Following is a list of the problems and the current status:

- _Field "Epiphany" in Characters board doesn't saved._
**FIXED in 0.4.0**

- _Don't load image for cards wallpaper._
Assume this has to do with **Edit -> Settings -> Views -> Index cards tab** Background selection.  It appears that only **Image** selection works.  Selecting a **Color** appears to have no affect.

- _Field "Source of conflict" in World board doesn't active._
**FIXED in 0.4.0**

- _In Redaction mode: It isn't stable, sometimes closes when changing from cards to text mode._
Please try 0.4.0.  If problem persists then please list steps to reproduce.

- _Field "summary" in Plot board (Resolution steps) doesn't active. After complete this field, columns are very large. Impossible see fully._
Please try 0.4.0.  If problem persists then please list steps to reproduce.

- _Not a bug, but a doubt: how use the heart icon in Characters board (field detailed infos)._
Good question.  In the code this is listed as **pushButton_3** with an icon from the theme **emblem-favorite**.  Other than that the button does not appear to do anything.  Perhaps it should be removed?

**Comment by olivierkes** [comment] 2017-10-14 07:37
> _Not a bug, but a doubt: how use the heart icon in Characters board (field detailed infos)._
Good question.  In the code this is listed as [pushButton_3](https://github.com/olivierkes/manuskript/blob/master/manuskript/ui/mainWindow.py#L489) with an icon from the theme **emblem-favorite**.  Other than that the button does not appear to do anything.  Perhaps it should be removed?

Removed.

Can we close this now, or should we keep it open for the two others undocumented issues?

**Comment by gedakc** [comment] 2017-10-14 16:22
Thanks @olivierkes for removing the button.  I will close this issue.  If any of the above listed problems re-occur then a new issue can be created.

**Closed by gedakc** 2017-10-14 16:22 UTC
Labels: bug
