### ISSUE TITLE
Fullscreen in multimonitor

### ISSUE THREAD

**Issue by vicentebarcelo** [olivierkes/manuskript#521] opened 2019-03-02 13:14 UTC
Hi.

When I try to use the full screen mode, the text is always activated only one of the screens. Is there any way to change the default screen for manuskript? Instead of activating the one I have as main in the OS, it activate the sencondary  :P

Regards,

**Comment by gedakc** [comment] 2019-03-02 16:38
'Hopefully someone with multiple monitors will investigate and troubleshoot this issue which has been raised previously.

Closing this report as a duplicate of issue #456.

**Closed by gedakc** 2019-03-02 16:38 UTC
