### ISSUE TITLE
Wrong codepage for import causes crash

### ISSUE THREAD

**Issue by worstje** [olivierkes/manuskript#470] opened 2019-02-05 15:12 UTC
I am finally at the point where I figured I'd try to import existing chapters into Manuskript.. and it is not quite going according to plan.

**Steps to reproduce:**

1. Open a project.

2. Click import.

3. Click 'Chose file'. (Btw, we probably want 'Choose', or perhaps the -on Windows more established- 'Browse'. But that's a minor thing I can't be bummed filing separately.)

4. Select the file.

5. Say goodbye to Manuskript and say hello to a wonderful traceback.

> Debug: Web rendering engine used: QWebView
> Running manuskript version 0.8.0.
> Note: No translator found or loaded for locale en_US.
> Loading: P:/Projects/Writing/AOitNoL/AOitNoL.msk
> Detected file format version: 1. Zip: True.
> Project P:/Projects/Writing/AOitNoL/AOitNoL.msk loaded.
> Traceback (most recent call last):
>   File "manuskript\ui\importers\importer.py", line 134, in selectFile
>   File "manuskript\ui\importers\importer.py", line 240, in preview
>   File "manuskript\ui\importers\importer.py", line 298, in startImport
>   File "manuskript\importer\markdownImporter.py", line 67, in startImport
>   File "c:\python34\lib\encodings\cp1252.py", line 23, in decode
> UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 488905: character maps to <undefined>

The problem seems to be that it is trying to import my existing musings in the default Windows codepage equivalent of latin1, but unfortunately I am a bit of an oddball because I chose to include bits of hiragana and kanji, which truly necessitates the file being stored as and processed in UTF-8.

Because my initial export was saved using Notepad++ default setting which does not include a BOM (which facilitates codepage auto detection), I have also tried to save the whole thing with the BOM included. But alas: the error remains, albeit with a slightly shifted position:

> UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 488908: character maps to <undefined>

**Suggestions for fix:**

1. Better fallback mechanism for auto-detection: if the default does not work, try UTF-8. Or maybe try UTF-8 by default because it has been the most dominant codepage on the internet for the last decade.

2. Allow the user to select a codepage for import to avoid problems with auto-detection.

3. Don't crash hard, but offer an error window explaining the nature of the problem. Bonus points if skipping the malformed characters could become possible, but only if it would offer a clear indication of where so I can manually fix up the relevant locations later.

**Comment by gedakc** [comment] 2019-02-05 16:56
Can you provide a sample input file that causes the issue?

That way I can try to reproduce the issue on GNU/Linux where I do all my development work.

**Comment by worstje** [comment] 2019-02-05 17:02
Ah whoops. I knew I had forgotten something. Sorry!

I distilled my huge thing down to a chapter heading and a few paragraphs including the one causing the problem. It still triggers the problem, just on a differnt position.

[testcase.txt](https://github.com/olivierkes/manuskript/files/2833039/testcase.txt)

**Comment by gedakc** [comment] 2019-02-05 18:21
From testing:

- Crash **does not** occur on Kubuntu 16.04 GNU/Linux which uses a UTF-8 environment by default
- Crash **does** occur on Windows 10  which does not use a UTF-8 environment by default.

To implement option **1** I tried the following change to the source code:

```
diff --git a/manuskript/importer/markdownImporter.py b/manuskript/importer/markdownImporter.py                                                                                                                    
index 107931e..d135485 100644                                                                                                                                                                                     
--- a/manuskript/importer/markdownImporter.py                                                                                                                                                                     
+++ b/manuskript/importer/markdownImporter.py                                                                                                                                                                     
@@ -63,7 +63,7 @@ class markdownImporter(abstractImporter):                                                                                                                                                       
                                                                                                                                                                                                                  
         if not fromString:                                                                                                                                                                                       
             # Read file                                                                                                                                                                                          
-            with open(filePath, "r") as f:                                                                                                                                                                       
+            with open(filePath, "r", encoding="utf-8") as f:                                                                                                                                                     
                 txt = f.read()                                                                                                                                                                                   
         else:                                                                                                                                                                                                    
             txt = fromString            
```

This change avoided the crash and enabled the `testcase.txt` file to be imported on both GNU/Linux and Windows.

Are you able to test this proposed solution?

**Comment by worstje** [comment] 2019-02-05 21:00
Yup, that test-build works fine. Thank you!

Now I can start messing around with the import function! :-)

On a related note... should I open issues for all the small issues I come across? I recall you mentioning the feature is relatively untested.. but at the same time I'm not sure if using the github issues is the way to go for things like bugs, typos, minor interface suggestions and even questions regarding how to approach the problems I run into while trying it out.

**Comment by gedakc** [comment] 2019-02-05 21:23
Thanks for testing to confirm that the proposed fix works.

Currently the only communication method available for reporting issues (bugs, feature requests, questions, etc) is the [Manuskript Issues](https://github.com/olivierkes/manuskript/issues) on GitHub.

If you wish, we can continue to communicate in this issue regarding import issues you discover.

> For example, the import dialog opens up right on the edge between my two screens rather than focusing on the screen I have the rest of the app on.

Could you describe in other words what is occuring?   Do you have two monitors, or are these virtual screens?

**Comment by worstje** [comment] 2019-02-05 22:08
I have dual monitors. My primary monitor is a 2560x1440 monitor, and to its left I have a secondary monitor with a 1920x1080 resolution.

See screenshot: 
![manuskript-import-window-position](https://user-images.githubusercontent.com/399950/52307253-5f2d0880-299a-11e9-9ad7-3bd567d65b82.png)

As you can tell the import window seems to position itself in the middle of the bounding box that makes up my combined screen areas. Because of my right screen being the larger one of the two, most of the import window ends up on that screen, but more than enough ends up on the left screen where it is a pain to use thanks to the physical limitations inherent to my desk.

Note that I haven't moved a single window; where you see the windows is where they ended up after a fresh start of Manuskript.

**Comment by gedakc** [comment] 2019-02-06 18:08
Thanks @worstje for the screen shot.  Interestingly the Manuskript window positions seem to be different on MS Windows versus GNU/Linux.  For example on my single monitor computer all of the child windows open up centered over the main Manuskript window.

Because I do not have dual monitors on my computer, would you be able to download and try **test2** in the [Manuskript testing-only folder on SourceForge](https://sourceforge.net/projects/manuskript/files/manuskript/testing-only/)?

Please try the **Import - F7** window and provide a screen shot.

If Import works, then please also try the **Compile - F6**, **Settings - F8**, and the **Help -> About** windows to see if the placement of these windows is okay.

**Comment by worstje** [comment] 2019-02-07 13:48
**F6 - Compile:** Cut off at the top.
![manuskript-test2-f6](https://user-images.githubusercontent.com/399950/52414811-98be5a80-2ae5-11e9-9b7f-efed36855e4a.png)

**F7 - Import:** Cut off at the top.
![manuskript-test2-f7](https://user-images.githubusercontent.com/399950/52414916-e1761380-2ae5-11e9-9620-fa608b24da82.png)

**F8 - Settings:** Appears to be centered on top of main window.
![manuskript-test2-f8](https://user-images.githubusercontent.com/399950/52414927-ed61d580-2ae5-11e9-8133-92a18695c841.png)

**Help -> About:** Cut off at the top.
![manuskript-test2-help-about](https://user-images.githubusercontent.com/399950/52414984-18e4c000-2ae6-11e9-829b-42bb0754cbd0.png)

**Tools -> Frequency Analyser:** Appears to be centered on the primary monitor (right screen).
![manuskript-test2-tools-frequency-analyser](https://user-images.githubusercontent.com/399950/52415000-2732dc00-2ae6-11e9-975c-08f070f2cc12.png)

**_Summary_**:

I think you adjusted a couple of windows to try and alleviate the location problem, but you adjusted vertically rather than horizontally. (Which is quite a feat btw, given that I know from my own coding experience that Windows tends to really fight attempts to position the top of windows off of the visible screen space!)

Settings and the Frequency Analyser are centered in different ways; one appears to center on top of the window and the other on top of the primary monitor.


Late addition:

I just spotted the 'Organize -> Split' window while writing this post, and it is the same as the Settings screen, centering on the main window.


**Organize -> Split**: Appears to be centered on top of main window.
![manuskript-test2-organize-split](https://user-images.githubusercontent.com/399950/52415460-4aaa5680-2ae7-11e9-95d8-25a0b84ddda6.png)

**Comment by gedakc** [comment] 2019-02-07 17:33
Thank you @worstje for all the screen shots.

The behaviour on Windows with dual monitors is quite different from my GNU/Linux computer with a single monitor.  For me the dialog placement code I modified continues to show child windows centered in the parent window on my Kubuntu 16.04 computer.

# Manuskript Child Windows with Placement Code

The original code in 0.8.0 tries to center the windows relative to the main Manuskript window.  For example the in-production 0.8.0 code for the **Help -> About** window is as follows:

https://github.com/olivierkes/manuskript/blob/f731e19e0030c3ac09b94f4bba1ef70526f55637/manuskript/mainWindow.py#L1076-L1084

The change I made for **test2** was as follows:

```
         # Center about dialog
         r = self.dialog.geometry()
         r2 = self.geometry()
-        self.dialog.move(r2.center() - r.center())
+        self.dialog.move(self.mapToGlobal(r2.center()) - self.mapToGlobal(r.center()))
```

# Manuskript Child Windows without Placement Code

Note that I did not alter the placement for the **Tools -> Frequency Analyser** window or the **Organize -> Split** window (thanks for noting this one).  These windows do not have code which tries to center them.

For example the code for the **Tools -> Frequency Analyser** is as follows:

https://github.com/olivierkes/manuskript/blob/f731e19e0030c3ac09b94f4bba1ef70526f55637/manuskript/mainWindow.py#L1340-L1343

From your screen shot the **Tools -> Frequency Analyser** child window is centered.  However on my Kubuntu 16.04 I see a different result as shown below:

![manuskript-tools-frequence-analyser-desktop](https://user-images.githubusercontent.com/10405019/52430411-3ce2da00-2ac3-11e9-8460-2f48c271da6b.png)

# Summary

It seems that my attempts to improve child window placement have only made the problem worse.  I will investigate to see if there are "best practices" for placing child windows using the Qt5 framework.  It is possible that this is best left to the Window manager on each operating system.

Regarding the original reason for this report (the _Wrong codepage for import causes crash_ issue), I will begin merging the **test** (not **test2**) code changes so that the Child Window placement problem does not hold up the crash fix.

_This report is now a classic example of why it is often better to track each problem in a separate issue._ :-)

**Comment by gedakc** [comment] 2019-02-07 17:46
@worstje when you have a chance would you please create a new issue for the child window placement problem on dual monitor Windows 10?

That way the window placement problem will not hold up the codepage crash fix.

**Comment by gedakc** [comment] 2019-02-08 18:43
Closing _Wrong codepage for import causes crash_ issue.  This enhancement will be included in the next release of Manuskript.

**Closed by gedakc** 2019-02-08 18:43 UTC
Labels: bug

**Comment by worstje** [comment] 2019-02-08 19:37
> _This report is now a classic example of why it is often better to track each problem in a separate issue._ :-)

Duly noted. The spelling mistake and then the awkward positioning of this window made me believe it was this dialog in particular that was still very alpha; the moment the other windows (that I had not used before!) came into it I immediately knew we escaped the scope of the sort of little issues I initially had in mind. :-)

> when you have a chance would you please create a new issue for the child window placement problem on dual monitor Windows 10?

I'll tidy up my screenshots post and write it up as its own issue. Consider it done.
