### ISSUE TITLE
Specific document suddenly won't open

### ISSUE THREAD

**Issue by timmytoe** [olivierkes/manuskript#502] opened 2019-02-20 23:49 UTC
Hey there,

really wanted to work on my writing just now, but found that manuskript won't even open. I tried to reinstall and even tried to open it on a different device where it had also worked just a day earlier. (Using Win10 64bit on both devices)

Now I'm a bit helpless as to what to do exactly and how to access/open my document files.
Here's a screenshot of the lines of text that pop up for only a few milliseconds before disappearing: https://i.gyazo.com/8e37618270fd1a1341549a428af9822b.png

A solution to this is much appreciated!

[Edit: This happens only with one particular document I'm trying to open]

**Comment by gedakc** [comment] 2019-02-21 16:12
There were some issues already addressed for Windows in the git source code **develop** branch that involved "_cp1252_" encoding problems.

Would you be able to [Run Manuskript from Source Code on Windows](https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Windows) and try the **develop** branch to see if it fixes the issue for you?

**Comment by gedakc** [comment] 2019-02-21 16:56
Would you be able to download and try the **issue502-test1** PyInstaller package?

The package is located at: [Manuskript testing-only folder on SourceForge](https://sourceforge.net/projects/manuskript/files/manuskript/testing-only/)

If there are problems, then open a command prompt, change to the directory that contains _manuskript.exe_  and then run _manuskript_.   Then copy the console log from the command prompt and paste it into this report.

**Comment by timmytoe** [comment] 2019-02-21 17:13
Thank you for getting back to me so quickly!

Unfortunately, neither of the two suggestions have worked.
The following happens by using the **issue502-test1** -> manuskript opens, but when choosing _that one specific document_ it closes instantly.

The following console log remains: https://i.gyazo.com/0bbd2ef2c6c1c0cc290b90748c763da6.png

**Comment by gedakc** [comment] 2019-02-21 17:31
Am I correct in assuming that you have the setting **Save to one single file** disabled?

If _and only if_ the above is true then can you try the following?

1. Make a backup of all the project files and folders.

2. Rename `your-project-name.msk` file to `your-project-name.msk.backup`

3. Open a text editor and create a new `your-project-name.msk` file and put the number one in the file as the only contents.

   ```
   1
   ```

3. Save the file and exit the text editor.

4. Try to open the project with manuskript.

**Comment by timmytoe** [comment] 2019-02-21 20:43
I have **Save to one single file** enabled.

**Comment by gedakc** [comment] 2019-02-21 21:58
Hmm...  There were two other reports of a similar problem (issues #106 and #222) but in both of those cases **Save to one single file** was **disabled**.

When **Save to one single file** is **enabled**, Manuskript stores all the project data in a zip file.  Otherwise it is unzipped.

You might try renaming `your-project-name.msk` to `your-project-name.zip` and then see if you can unzip the file to get at the contents.

At the moment I'm at a loss as to what might have caused the "VERSION" section of the file to have become corrupted.

**Comment by timmytoe** [comment] 2019-02-21 22:16
That is very weird indeed.

Tried to unzip the file but it says it's corrupted. But when I used a different file, it worked just fine.

Don't know how the file usually looks like when opening it with Notepad++, but maybe you can see something wrong with it: https://i.gyazo.com/23ef516f5266920629168d1a5660dcb5.png

I really appreciate all of your help so far. I can only hope that the contents aren't lost forever. :/

**Comment by gedakc** [comment] 2019-02-21 22:31
From your screen shot it would appear that the contents are still there, although in zip format.

Would you able to email a copy of the project file to me so that I can take a look at it?

I might not have a chance to look at it until early next week, but having the file would make it easier to directly compare with other working files.  Of course you might try doing this yourself.  I suspect that there is a problem at the start of the file such that manuskript does not recognize the `VERSION` number or the text `MANUSKRIPT` in the zip file.

The line of code that fails (from your screen shot of the console log) is line 58 of [`manuskript/loadSave.py`](https://github.com/olivierkes/manuskript/blob/develop/manuskript/loadSave.py)

**Comment by timmytoe** [comment] 2019-02-21 23:05
That would be very much appreciated! I just checked your profile, but couldn't find any email to send it to.

**Comment by gedakc** [comment] 2019-02-22 03:18
Thanks for the heads up on that.  I have added an email to my profile.  Otherwise I also have an email at the bottom of the web site link in my profile.

**Comment by gedakc** [comment] 2019-02-22 17:41
**Issue Update**:  After correspondence between @timmytoe and myself, we discovered that the project file was corrupted and had lost **significant** content.  :-(

In an attempt to recover as much file contents as possible from the single project.msk file the following commands were used:

    cp Manuskript-Project.msk Corrupted.zip
    zip -FF Corrupted.zip --out Recovered.zip

The loss of a significant amount of work is devastating.  Unfortunately we do not know the cause of corruption.  To minimize loss of work in the future it is highly recommended to make frequent backups. 

In an effort to address this issue, I will be making some additional code changes.  However without knowing the cause of the corruption, I cannot be sure that the code changes will fix the issue, or even if the issue is a bug within Manuskript itself.

Regards,
Curtis

**Comment by kakaroto** [comment] 2019-02-25 21:15
Losing that work would indeed be devastating, so sorry to hear that @timmytoe. I hope that you have a backup somewhere, maybe a compiled/exported document that you shared with someone at some point (having a writer's group is useful for that), from which you can recover some of your text.

When I downloaded manuskript for the first time, I saw that first line on the [download page](https://www.theologeek.ch/manuskript/download/) that says :
> Warning: Though many features are already working as expected, Manuskript is still in heavy development. **If you consider using it for serious work, do frequent backup !**

So I made a git repository in which I commit my project files every time I make a change (I disabled the **save to one single file** option) this way I always have a backup + history of my changes. 
If you ever had the file on your dropbox, dropbox might allow you to recover previous versions of the file, and hopefully you will find one that isn't corrupted.

Otherwise.. 😢 Try to keep frequent backups for the future.

@gedakc I didn't check how saving works, but would saving to a different file (like file.msk.tmp instead of file.msk) then making sure the new file loads without issues (i.e: not corrupted) before moving it to overwrite the real save file help prevent corruptions issues in the future ?

**Comment by gedakc** [comment] 2019-02-26 20:43
@kakaroto, in answer to your question we have identified [issue 254 - Make a backup copy of the project before saving]().

In the meantime I will create a PR for the code enhancements I have already developed for this issue, with the plan to merge the PR tomorrow.

**Closed** 2019-02-27 17:54 UTC
Labels: windows
