### ISSUE TITLE
Crash on start - arguments did not match any overloaded call: QColor(Qt.GlobalColor): argument 1 has unexpected type 'float'

### ISSUE THREAD

**Issue by Ubiquity5** [olivierkes/manuskript#1062] opened 2022-08-17 13:29 UTC
Can't open manuskript

```
2022-08-17 15:29:56,182 - manuskript.logging - INFO - Logging to file: /home/phawthorne/.local/share/manuskript/manuskript/logs/2022-08-17_15-29-56_manuskript#169983.log
2022-08-17 15:29:56,185 - manuskript - INFO - Operating System: Linux-5.18.0-1-amd64-x86_64-with-glibc2.33
2022-08-17 15:29:56,185 - manuskript - INFO - Hardware: x86_64 / 
2022-08-17 15:29:56,185 - manuskript - INFO - Running from unpackaged source code.
2022-08-17 15:29:56,185 - manuskript - DEBUG - * sys.executable = '/usr/bin/python3'
2022-08-17 15:29:56,185 - manuskript - DEBUG - * sys.argv = ['/usr/bin/manuskript', '--verbose']
2022-08-17 15:29:56,185 - manuskript - DEBUG - * sys.path = ['/usr/bin',
 '/usr/share/manuskript/',
 '/usr/lib/python310.zip',
 '/usr/lib/python3.10',
 '/usr/lib/python3.10/lib-dynload',
 '/usr/local/lib/python3.10/dist-packages',
 '/usr/lib/python3/dist-packages',
 '/usr/lib/python3.10/dist-packages']
2022-08-17 15:29:56,185 - manuskript - DEBUG - * sys.prefix = '/usr'
2022-08-17 15:29:56,186 - manuskript - INFO - Manuskript 0.12.0 (Python 3.10.5)
2022-08-17 15:29:56,186 - manuskript - INFO - * PyQt 5.15.7 (compiled against Qt 5.15.4)
2022-08-17 15:29:56,186 - manuskript - INFO -   * Qt 5.15.4 (runtime)
2022-08-17 15:29:56,193 - manuskript - INFO - * lxml.etree 4.8.0.0
2022-08-17 15:29:56,193 - manuskript - INFO -   * libxml   2.9.14 (compiled: 2.9.12)
2022-08-17 15:29:56,193 - manuskript - INFO -   * libxslt  1.1.34 (compiled: 1.1.34)
2022-08-17 15:29:56,194 - manuskript - INFO - * pyEnchant 3.2.2 (libenchant: 2.3.3)
2022-08-17 15:29:56,194 - manuskript - INFO - * pySpellChecker N/A
2022-08-17 15:29:56,194 - manuskript - INFO - * Symspellpy N/A
2022-08-17 15:29:56,246 - manuskript - INFO - * Markdown 3.3.7
2022-08-17 15:29:56,321 - manuskript - INFO - Web rendering engine: QtWebKit
2022-08-17 15:29:56,338 - manuskript.main - INFO - Preferred translation: manuskript_de.qm (based on user setting)
2022-08-17 15:29:56,339 - manuskript.main - INFO - Loaded translation: manuskript_de.qm
2022-08-17 15:29:56,348 - manuskript.logging - CRITICAL - An unhandled exception has occurred!
Traceback (most recent call last):
  File "/usr/bin/manuskript", line 30, in <module>
    main.run()
  File "/usr/share/manuskript/manuskript/main.py", line 292, in run
    app, MW = prepare(arguments)
  File "/usr/share/manuskript/manuskript/main.py", line 171, in prepare
    from manuskript.mainWindow import MainWindow
  File "/usr/share/manuskript/manuskript/mainWindow.py", line 23, in <module>
    from manuskript.models.worldModel import worldModel
  File "/usr/share/manuskript/manuskript/models/worldModel.py", line 11, in <module>
    from manuskript.ui import style as S
  File "/usr/share/manuskript/manuskript/ui/style.py", line 36, in <module>
    highlightLight = F.mixColors(highlight, window, .3)
  File "/usr/share/manuskript/manuskript/functions/__init__.py", line 197, in mixColors
    return QColor(r, g, b) if not fromString else QColor(r, g, b).name()
TypeError: arguments did not match any overloaded call:
  QColor(Qt.GlobalColor): argument 1 has unexpected type 'float'
  QColor(int): argument 1 has unexpected type 'float'
  QColor(QRgba64): argument 1 has unexpected type 'float'
  QColor(Any): too many arguments
  QColor(): too many arguments
  QColor(int, int, int, alpha: int = 255): argument 1 has unexpected type 'float'
  QColor(str): argument 1 has unexpected type 'float'
  QColor(Union[QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'
```

Running manuskript version `0.12.0-1` with `python3-pyqt5` version `5.15.7+dfsg-1` on [Debian Testing](https://wiki.debian.org/DebianTesting), `5.18.0-1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.2-1 (2022-06-06) x86_64 GNU/Linux`

What to do?

**Comment by TheJackiMonster** [comment] 2022-08-17 14:58
Please just try a newer version of Manuskript. I would recommend to use the flatpak on Debian, since it will provide the newest version out of the box without relying on potentially breaking dependencies.

The issue you encountered relies on the newer python version which breaks on type mismatches while older versions used implicit casting and ignored the cause.

**Comment by TheJackiMonster** [comment] 2022-08-17 15:00
This issue is a duplicate of #1043. So I will close it.

**Closed** 2022-08-17 15:00 UTC
Labels: duplicate

**Comment by TheJackiMonster** [comment] 2022-08-18 09:56
We do actually support Debian via a native package but not via the official repository unfortunately. So you could get the newest .deb package from the website [here](https://www.theologeek.ch/manuskript/download/) and install it manually if you don't like to use flatpaks. But this would lack automatic updates and there's currently an issue with the latest .deb package on Debian because I packaged it on Ubuntu which used a different compression algorithm as default (#1047: this has already been fixed for the upcoming packages).

Sure, I could try to contact the maintainers of the official repositories from Debian to update the package but I'm unsure whether it makes sense to put Manuskript into their repositories in current state anyway. We still have some quite important bugs to fix before I would say it's reliable enough for the expectations of most Debian users. ^^'

**Comment by TheJackiMonster** [comment] 2022-08-31 07:51
I have repackaged version 0.14.0 a few days ago with the fixed script. So it should work now.

**Comment by Biep** [comment] 2022-09-23 10:29
Could anyone having (had) this problem please indicate so [here](https://bugs.launchpad.net/ubuntu/+source/manuskript/+bug/1989203), so as to make the devs update the repo faster?  Thanks!
