### ISSUE TITLE
Spell Check Issue with Windows 10

### ISSUE THREAD

**Issue by karthikrao1999** [olivierkes/manuskript#373] opened 2018-08-08 19:41 UTC
Hi,
I just downloaded this today, so apologies if this issue has been brought up before. While I click on the menu to do a spell check, the app crashes, without loss of data as far as I can figure. I am running Windows 10 - 1803.

**Comment by gedakc** [comment] 2018-08-09 14:56
Thank  you @karthikrao1999 for your interest in Manuskript.

The crash on spell check is a known issue.  See issue #273.

You can work-around the issue by first selecting a valid dictionary (**Tools -> Dictionary**).

A fix for the issue exists in the **develop** branch, if you should choose to [Run Manuskript from Source Code on Windows](https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Windows).

Additionally I am planning to create a new release of Manuskript next week.

Marking this issue as a duplicate of issue #273.

**Closed by gedakc** 2018-08-09 14:56 UTC
Labels: bug, duplicate
