### ISSUE TITLE
manuskriptw.exe can not be executed due to unhandled exception "NullWriter"

### ISSUE THREAD

**Issue by Anne501R** [olivierkes/manuskript#1044] opened 2022-06-25 15:54 UTC
Hello Manuskript-Team
,
I just installed Manuskript v0.14.0 and tried to open manuskriptw.exe in order to avoid having a console window in the background. But when I do so I get the following error message on my Win 11 system:

### Unhandled exception in Script
Failed to excecute script 'manuskript' due to unhandled exception 'NullWriter' object has no attribute 'fileno'
>>Traceback (most recent call last):
  File "manuskript", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "manuskript\main.py", line 17, in <module>
AttributeError: 'NullWriter' object has no attribute 'fileno'
![Screenshot 2022-06-25 175242](https://user-images.githubusercontent.com/65713752/175781235-e010a0f5-65a8-477b-8290-43db1a5ceb32.png)

My current workaround is to excecute the manuskript.exe as before. 😀

**Comment by TheJackiMonster** [comment] 2022-06-26 02:01
Thanks for the feedback. That means I probably configured something wrong with `manuskriptw.exe`. I should look into this before the next release. Maybe some others can clarify whether this issue only occurs on Windows 11 or if it's a problem in general.

**Comment by geedeek** [comment] 2022-06-27 03:46
Yes, I see this too on WIndows 11 - the console version works, the windowed version gives me the same error.

**Comment by nikelui** [comment] 2022-07-13 02:39
I have encountered the same bug on Windows 10, so it's not an issue with the OS.

**Comment by TheJackiMonster** [comment] 2022-07-13 10:39
Okay, thank you for the confirmation. I will probably need a Windows VM for the next release then. ^^'

**Comment by ws132** [comment] 2022-07-13 13:48
> Okay, thank you for the confirmation. I will probably need a Windows VM for the next release then. ^^'

Thanks Reply.
I think it may be possible to mention this temporary processing method in the changelog, so that users can handle it themselves.
In fact, I've switched to arch because of the annoying EDGE update can't uninstall issue, and it's working fine so far.
manuskript is amazingly perfect🥳

**Comment by TheJackiMonster** [comment] 2022-08-09 22:23
I've found the cause of the issue. The problem is known by the developers of pyinstaller and can be seen [here](https://github.com/pyinstaller/pyinstaller/issues/4481). I will try to implement a workaround now for the next release.

**Comment by TheJackiMonster** [comment] 2022-08-09 22:48
Okay, from my testing in a VM the issue is solved by my latest commit 029dfe2056a2b3f83b0ec951110a3a8506bf27bf. So I will close this issue already. If you don't want to wait for the next release, you can theoretically [build the Windows binaries in any Linux VM](https://github.com/olivierkes/manuskript/wiki/Package-Manuskript-for-Windows-with-wine) using the current state in the `develop` branch (or you try [using PyInstaller on Windows](https://github.com/olivierkes/manuskript/wiki/Package-Manuskript-for-Windows-with-PyInstaller)). ^^'

**Closed by TheJackiMonster** 2022-08-09 22:48 UTC
Labels: bug, windows, packaging
