### ISSUE TITLE
Editor colours - BUG

### ISSUE THREAD

**Issue by hugo-id** [olivierkes/manuskript#264] opened 2017-12-08 12:35 UTC
I customised the editor (not fullscreen) to be white text on black background, but now when I go into any other text field, the text is white, but the background hasn't changed, and is still white too.

Fix:

All text fields 100% match editor, or
Text fields are unaffected by the View customisation settings

**Comment by olivierkes** [comment] 2017-12-08 14:13
What version are you using? (please, always include it in every issue)

And what other field are affected with the bug?

Because with current `develop` branch, I cannot reproduce:

![image](https://user-images.githubusercontent.com/1192933/33769385-5ba032f0-dc2a-11e7-835c-15d3f664eead.png)

**Comment by gedakc** [comment] 2018-08-16 21:44
Closing this issue as **invalid** because no further information has been provided.

If more details are provided then we can look at re-opening the issue.

**Closed by gedakc** 2018-08-16 21:44 UTC
