### ISSUE TITLE
Feature request: Character dossier template

### ISSUE THREAD

**Issue by MetalMick99** [olivierkes/manuskript#693] opened 2019-11-13 22:55 UTC
Many similar software products - for example, WriteItNow, Bibisco, Freewriter, etc - have a template for entering character information such a name, age, height, birthplace, eye color, weight, etc. Bibisco in particular is quite comprehensive.

Creating characters in Manuskript is slow because each trait needs to be created in the list for each character. Even if creating a character trait list saw it echoed for subsequent characters so that the author could then fill in those that s/he wished, this would ease things dramatically. Perhaps even a list of character traits that could be selected or dragged and dropped into the "Detailed Info" tab.

WriteItNow has complex and extensive trait tools such as "Aggressiveness" with sliders from 0 to 100, but I find it difficult to conceptualize a difference between say 75 for a trait and 70 or 82 or any other number. I find this tool in the software to be largely unnecessary.

I'd be happy to provide a list of traits on request.

**Comment by Blake-Eryx** [comment] 2019-11-16 14:17
Perhaps even something as simple as importing a list of traits (i.e., a single-column text file with traits like "gender") into the Details area would be useful.

**Comment by Blake-Eryx** [comment] 2019-11-16 15:02
Here are a few trait lists that I've come up

[EDUCATION & CAREER.txt](https://github.com/olivierkes/manuskript/files/3854318/EDUCATION.CAREER.txt)
[GENERAL INFO.txt](https://github.com/olivierkes/manuskript/files/3854319/GENERAL.INFO.txt)
[INTERPERSONAL.txt](https://github.com/olivierkes/manuskript/files/3854320/INTERPERSONAL.txt)
[PERSONALITY.txt](https://github.com/olivierkes/manuskript/files/3854321/PERSONALITY.txt)
[PHYSICALITY.txt](https://github.com/olivierkes/manuskript/files/3854322/PHYSICALITY.txt)
[RELIGION.txt](https://github.com/olivierkes/manuskript/files/3854323/RELIGION.txt)
[SPECIAL ABILITIES.txt](https://github.com/olivierkes/manuskript/files/3854324/SPECIAL.ABILITIES.txt)






 with, maybe useful.

**Comment by MetalMick99** [comment] 2019-11-16 23:35
I think your suggestions are a great start.

There are already online resources that can be accessed (ie. modified and copied for Manuskript):
https://www.novel-software.com/theultimatecharacterquestionnaire

- and;

https://www.epiguide.com/ep101/writing/charchart.pdf

Though I'm using Bibisco at the moment, its character dossier section is at times, a bit much, as is the link in epiguide. Currently oStorybook allows for the creation of character traits, and these are added to the novel database, allowing subsequent characters to be created from the first list of traits, and the author can add from the list as s/he sees fit for each of those characters.

**Comment by MetalMick99** [comment] 2019-11-17 02:03
I think your suggestions are a great start.

There are already online resources that can be accessed (ie. modified and copied for Manuskript):
https://www.novel-software.com/theultimatecharacterquestionnaire

- and;

https://www.epiguide.com/ep101/writing/charchart.pdf

Though I'm using Bibisco at the moment, its character dossier section is at times, a bit much, as is the link in epiguide. Currently oStorybook allows for the creation of character traits, and these are added to the novel database, allowing subsequent characters to be created from the first list of traits, and the author can add from the list as s/he sees fit for each of those characters.

**Comment by MetalMick99** [comment] 2019-11-17 02:04
Sorry - I accidentally closed this, but wished that it remain open.

**Comment by MetalMick99** [comment] 2019-11-18 00:29
Also relevant to the character dossier function would be the a means of adding a picture to the dossier - I regularly go through IMDB for photos that I feel are representative of the character I wish to build.

**Comment by PanDedoctor** [comment] 2019-11-18 21:21
So we are in agreement, we basically want Character Story Planner 2 inside of the Manuskript? I think it is outstanding idea.

**Comment by MetalMick99** [comment] 2019-11-20 21:13
After having a very brief look at CSP2  - which is an Android app - but not installing it, I think that yes, it would be useful, but integrating that functionality into Manuskript might require enormous work. That's something the creator of it can decide to do if he wishes. The facilities in Bibisco, Freewriter, and others (including oStorybook) are superior to Manuskript and in my opinion needed to bring Manuskript closer to completion. Right now, I'd be okay with a good list of traits - physical, familial, emotional, etc - that I could fill in so that I know more about my character and how they react to events in my stories.

**Comment by gedakc** [comment] 2020-01-02 18:15
This discussion looks like a duplicate of issue #252.

**Comment by Blake-Eryx** [comment] 2020-07-30 23:51
I put together a repo of traits that can be copy and pasted into a character profile:

https://github.com/Blake-Eryx/Character-Traits

**Closed** 2021-02-22 22:38 UTC
Labels: duplicate, enhancement
