### ISSUE TITLE
Crashhhh

### ISSUE THREAD

**Issue by AoriOjin** [olivierkes/manuskript#791] opened 2020-07-29 23:56 UTC
It opens the initial page, but then crashes when I click any of the options to start (can't open a file, can't create a novel or a blank page...). The only thing working is the bible thing xD

Anyway, I'm using Windows 10, and it was working perfectly until I told windows that manuskript files were to be always opened with manuskript, since then, that's only crash landing on you (well, on me actually). This bug is from the .zip we get at the website.
Well, I did run it from the cmd right now, here is what it tells me back:

Traceback (most recent call last):
  File "manuskript\ui\welcome.py", line 189, in createFile
  File "manuskript\ui\welcome.py", line 61, in getLastAccessedDirectory
  File "c:\python34\lib\encodings\cp850.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u2014' in position 52: character maps to <undefined>

I have way no idea what it means but I hope you can fix it soon, 'cause I NEED MANUSKRIPT SO BAD, IT'S THE PERFECT TOOL FOR WRITING T____T
I also would like to work with it in Manjaro, the repository seems to be not working there or something alike...? It doesn't even install so I don't know what happens. Though Manjaro doesn't have much of a community support, it's still the very fast of the OSs I've tried to work with graphic content.

Regardless of the bugs, lots of love from this brand new fan who wishes to start a comic with manuskript <3 I'll be sure to donate as soon as I can work with it.

**Comment by gedakc** [comment] 2020-07-30 17:02
You might search the [issues for the text "crash"](https://github.com/olivierkes/manuskript/issues?q=is%3Aissue+crash+) to see how others have addressed similar problems.

Always make a backup of your project first.

**Comment by worstje** [comment] 2020-07-30 22:22
Without looking at the source code, your problem seems to involve an em-dash (“—”) in the path / file name of your project. Try moving or renaming it, perhaps changing the em-dash in question to a boring normal hyphen (“-”) or removing it entirely.

When it comes to filenames, it is always useful to avoid more exotic symbols. It is ancient turtles all the way down in operating systems, and Windows and Unix systems differ in the way they store and treat filenames which causes problems with interoperability that are very hard to figure out and fix.

What is happening here appears to be a conversion of something (it could be the file path passed, or it could be the last accessed directory, I can't be bothered looking it up) into a format that does not understand the em dash, which is the practical equivalent of putting sand in your gas tank.

**Comment by AoriSeikou** [comment] 2020-08-19 22:29
Ok, so, I thank you both @worstje and @gedakc for replying and trying to help, but unfortunately none of this is working...
*
I tried to search for all types of crashes over the issues page and got a single similar result from the version 0.09 or so, someone of the staff said it was going to be fixed/rewritten to the version 0.10 and later confirmed that it was okay and closed the case. But because that was the only thing I could find I felt the need to open this request over here.

And I'm sorry to tell that there are no dashes on any document, I can't even create a document to begin with, I'm having the error simply by running the .exe, so there's no other way around unless nowing to code that is the cause of the problem I guess.
*
I noticed today (like, a monht later but yeah) that the .zip in the download page says Windows32, and I'm using a 64, perharps that is the cause of the problem, imcompatibility? I don't know much about this kind of stuff, but I know there is some internal differences, that may be an idea.

**Comment by AoriSeikou** [comment] 2020-09-01 15:39
Update: IT'S WORKING ON MANJARO yay go team Manuskript!!!
I'm really glad it's now working on at least 1 of my OSs so I can work with it, but I'll let this request open so the staff can know something weird went on and they can work to fix that.

**Comment by rodrigo-rufino** [comment] 2021-03-17 19:48
@TheJackiMonster do you know any fix for this? It's also happening to me.

**Comment by TheJackiMonster** [comment] 2021-03-18 00:27
I assume we need to improve the escape function for filenames further but it's just a guess. I currently don't have any Windows to reproduce it.

**Comment by rodrigo-rufino** [comment] 2021-03-18 01:20
I have found an workaround:
1. Installed the previous version
2. Created a project
3. Opened the new project with the latest version (the one with the bug) and now it's working fine.

**Closed** 2021-11-26 14:31 UTC
Labels: bug, windows
